name: 'Prepare bundle cache'

description: 'Sets up bundle cache for GitHub Actions'

outputs:
  cache-key:
    description: 'Cache key for the bundle'
    value: ${{ steps.restore-cache.outputs.cache-primary-key }}
  lockfile:
    description: 'Lockfile name'
    value: ${{ steps.lockfile.outputs.lockfile }}

runs:
  using: "composite"
  steps:
    - name: Generate unique Ruby environment key
      id: ruby-env-id
      shell: bash
      run: |
        id=$(ruby -e "puts RUBY_DESCRIPTION") # Includes patchlevel, os, and arch
        echo "id=$id" >> "$GITHUB_OUTPUT"
    - name: Generate lockfile
      id: lockfile
      shell: bash
      env:
        LOCKFILE: lockfile-${{ steps.ruby-env-id.outputs.id }}
      run: |
        bundle lock
        echo "lockfile=$LOCKFILE" >> "$GITHUB_OUTPUT"
    - name: Upload lockfile
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ steps.lockfile.outputs.lockfile }}
        path: "*.lock"
    - name: Restore cache
      uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      id: restore-cache
      with:
        key: bundle-${{ steps.ruby-env-id.outputs.id }}-${{ hashFiles('*.lock') }}
        path: "/usr/local/bundle"
    - if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Install the base Gemfile for this Ruby version
      shell: bash
      run: bundle install
    - if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Install all gemfiles/ for this Ruby version
      shell: bash
      run: bundle exec rake github:install_all_gemfiles
    - if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Save cache
      uses: actions/cache/save@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      with:
        key: "${{ steps.restore-cache.outputs.cache-primary-key }}"
        path: "/usr/local/bundle"
    - name: Verify base bundle
      run: bundle check
      shell: bash
