name: 'Restore, install (if needed), and save gems to the bundle cache'

description: 'Sets up bundle cache for GitHub Actions'

outputs:
  cache-key:
    description: 'Cache key for the bundle'
    value: ${{ steps.restore-cache.outputs.cache-primary-key }}
  lockfile:
    description: 'Lockfile artifact name'
    value: lockfile-${{ steps.restore-cache.outputs.cache-primary-key }}

runs:
  using: "composite"
  steps:
    - name: Generate lockfile
      shell: bash
      run: bundle lock
    - name: Restore cache
      id: restore-cache
      uses: ./.github/actions/bundle-restore
    - name: Upload lockfile
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: lockfile-${{ steps.restore-cache.outputs.cache-primary-key }}
        path: "*.lock"
    - if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Install the base Gemfile for this Ruby version
      shell: bash
      run: bundle install
    - if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Install all gemfiles/ for this Ruby version
      shell: bash
      run: bundle exec rake dependency:install[frozen]
    - if: steps.restore-cache.outputs.cache-hit != 'true'
      name: Save cache
      uses: ./.github/actions/bundle-save
      with:
        cache-key: ${{ steps.restore-cache.outputs.cache-primary-key }}
