module Datadog
  module Core
    module Remote
      module Transport
        module HTTP
          module API
            ROOT: "root"

            V7: "v0.7"

            def self?.defaults: () -> untyped

            class Instance < Core::Transport::HTTP::API::Instance
              include Config::API::Instance

              include Negotiation::API::Instance
            end

            class Spec < Core::Transport::HTTP::API::Spec
              include Config::API::Spec

              include Negotiation::API::Spec
            end
          end
        end
      end
    end
  end
end
