module Datadog
  module OpenFeature
    class Component
      @settings: Core::Configuration::Settings

      @agent_settings: Core::Configuration::AgentSettings

      @logger: Core::Logger

      @telemetry: Core::Telemetry::Component

      @engine: EvaluationEngine

      @worker: Exposures::Worker

      @flag_eval_metrics_hook: Hooks::FlagEvalMetricsHook?

      @flag_eval_evp_hook: Hooks::FlagEvalEVPHook?

      @flag_eval_evp_writer: FlagEvaluation::Writer?

      @span_enrichment_hook: Hooks::SpanEnrichmentHook?

      attr_reader engine: EvaluationEngine

      attr_reader flag_eval_metrics_hook: Hooks::FlagEvalMetricsHook?

      attr_reader flag_eval_evp_hook: Hooks::FlagEvalEVPHook?

      attr_reader span_enrichment_hook: Hooks::SpanEnrichmentHook?

      def self.build: (
        Core::Configuration::Settings settings,
        Core::Configuration::AgentSettings agent_settings,
        logger: Core::Logger,
        telemetry: Core::Telemetry::Component
      ) -> Component?

      def initialize: (
        Core::Configuration::Settings settings,
        Core::Configuration::AgentSettings agent_settings,
        logger: Core::Logger,
        telemetry: Core::Telemetry::Component
      ) -> void

      def shutdown!: () -> void

      private

      def create_flag_eval_metrics_hook: () -> Hooks::FlagEvalMetricsHook?

      def create_flag_eval_evp_hook: () -> Hooks::FlagEvalEVPHook?

      def create_span_enrichment_hook: () -> Hooks::SpanEnrichmentHook?
    end
  end
end
