module Datadog
  module OpenFeature
    class Component
      type configuration_wait_result = :ready | :timeout | :shutdown
      type configuration_event = :ready | :changed

      CONFIGURATION_READY: :ready

      CONFIGURATION_TIMEOUT: :timeout

      CONFIGURATION_SHUTDOWN: :shutdown

      CONFIGURATION_CHANGED: :changed

      @settings: Core::Configuration::Settings

      @agent_settings: Core::Configuration::AgentSettings

      @logger: Core::Logger

      @telemetry: Core::Telemetry::Component

      @engine: EvaluationEngine

      @worker: Exposures::Worker

      @flag_eval_metrics_hook: Hooks::FlagEvalMetricsHook?

      @flag_eval_evp_hook: Hooks::FlagEvalEVPHook?

      @flag_eval_evp_writer: FlagEvaluation::Writer?

      @span_enrichment_hook: Hooks::SpanEnrichmentHook?

      @configuration_mutex: ::Thread::Mutex

      @configuration_condition: ::Thread::ConditionVariable

      @configuration_received: bool

      @configuration_shutdown: bool

      @on_configuration_change: (^(configuration_event) -> void)?

      attr_reader engine: EvaluationEngine

      attr_reader flag_eval_metrics_hook: Hooks::FlagEvalMetricsHook?

      attr_reader flag_eval_evp_hook: Hooks::FlagEvalEVPHook?

      attr_reader span_enrichment_hook: Hooks::SpanEnrichmentHook?

      def self.build: (
        Core::Configuration::Settings settings,
        Core::Configuration::AgentSettings agent_settings,
        resolution: Configuration::Source::Resolution,
        on_configuration_change: ^(configuration_event) -> void,
        logger: Core::Logger,
        telemetry: Core::Telemetry::Component
      ) -> Component?

      def initialize: (
        Core::Configuration::Settings settings,
        Core::Configuration::AgentSettings agent_settings,
        ?on_configuration_change: (^(configuration_event) -> void)?,
        logger: Core::Logger,
        telemetry: Core::Telemetry::Component
      ) -> void

      def shutdown!: () -> void

      def reconfigure!: (::String? configuration) -> void

      def wait_for_configuration: () -> configuration_wait_result

      def configuration_received?: () -> bool

      private

      def create_flag_eval_metrics_hook: () -> Hooks::FlagEvalMetricsHook?

      def create_flag_eval_evp_hook: () -> Hooks::FlagEvalEVPHook?

      def create_span_enrichment_hook: () -> Hooks::SpanEnrichmentHook?
    end
  end
end
