module Datadog
  module OpenFeature
    module Ext
      INITIALIZING: ::String

      ERROR: ::String

      UNKNOWN_TYPE: ::String

      PROVIDER_FATAL: ::String

      PROVIDER_NOT_READY: ::String

      TYPE_MISMATCH: ::String

      PARSE_ERROR: ::String

      FLAG_NOT_FOUND: ::String

      TYPE_MISMATCH_ERROR: ::String

      CONFIGURATION_PARSE_ERROR: ::String

      CONFIGURATION_MISSING: ::String

      FLAG_UNRECOGNIZED_OR_DISABLED: ::String

      FLAG_DISABLED: ::String

      DEFAULT_ALLOCATION_NULL: ::String

      INTERNAL_ERROR: ::String
    end
  end
end
