module Datadog
  module OpenFeature
    module Ext
      INITIALIZING: ::String

      ERROR: ::String

      DEFAULT: ::String

      UNKNOWN_TYPE: ::String

      PARSE_ERROR: ::String

      GENERAL: ::String

      PROVIDER_FATAL: ::String

      PROVIDER_NOT_READY: ::String
    end
  end
end
