module Datadog
  module OpenFeature
    class NoopEvaluator
      def initialize: (::String?) -> void

      def get_assignment: (
        ::String flag_key,
        default_value: untyped,
        context: ::OpenFeature::SDK::EvaluationContext::fields_t,
        expected_type: ::Symbol
      ) -> ResolutionDetails
    end
  end
end

