module Datadog
  module Core
    module Workers
      module Async
        module Thread
          FORK_POLICY_STOP: :stop

          FORK_POLICY_RESTART: :restart

          SHUTDOWN_TIMEOUT: 1
          MUTEX_INIT: ::Mutex
          @error: ::Exception?
          @result: ::Object?
          @fork_policy: ::Object?
          @run_async: bool
          @pid: ::Integer?
          @mutex: ::Mutex?
          @mutex_after_fork: ::Mutex?
          @worker: ::Thread?

          def self.included: (Class | Module base) -> void
          module PrependedMethods
            def perform: (*::Object args) -> bool?

            private

            def started?: () -> bool
            def result=: (::Object?) -> ::Object?
            def start_async: () { () -> ::Object } -> bool?
          end

          attr_reader error: ::Exception?

          attr_reader result: ::Object?

          attr_writer fork_policy: ::Object?

          def join: (?(::Numeric | nil) timeout) -> bool

          def terminate: () -> (false | true)

          def run_async?: () -> bool

          def started?: () -> bool

          def running?: () -> bool

          def error?: () -> bool

          def completed?: () -> bool

          def failed?: () -> bool

          def forked?: () -> bool

          def fork_policy: () -> ::Object

          attr_writer result: ::Object?

          def mutex: () -> ::Mutex

          def after_fork: () -> nil

          private

          attr_reader pid: ::Integer?

          def mutex_after_fork: () -> ::Mutex

          def worker: () -> ::Thread?

          def start_async: () { () -> ::Object } -> bool?

          def start_worker: () { () -> ::Object } -> true

          def stop_fork: () -> bool?

          def restart_after_fork: () { () -> ::Object } -> bool?
        end
      end
    end
  end
end
