module Datadog
  module Core
    module Workers
      module Polling
        include Workers::IntervalLoop
        include Workers::Async::Thread
        prepend PrependedMethods

        DEFAULT_SHUTDOWN_TIMEOUT: 1

        def self.included: (Class | Module base) -> void

        module PrependedMethods
          def perform: (*untyped args) -> untyped
        end

        def stop: (?bool force_stop, ?::Integer | ::Float timeout) -> untyped |
                (*untyped args) -> untyped

        def enabled?: () -> bool

        def enabled=: (bool value) -> bool
      end
    end
  end
end
