module Datadog
  module AppSec
    module Contrib
      module Sinatra
        module Ext
          APP: "sinatra"

          ROUTE_INTERRUPT: :datadog_appsec_contrib_sinatra_route_interrupt
        end
      end
    end
  end
end
