module Datadog
  module AppSec
    module Contrib
      module Sinatra
        module AppSecSetupPatch
          def setup_middleware: (*untyped args) ?{ () -> untyped } -> untyped
        end

        module DefaultMiddlewarePatch
          def setup_middleware: (*untyped args) ?{ () -> untyped } -> untyped
        end

        module DispatchPatch
          @request: ::Sinatra::Request

          def dispatch!: () -> untyped
        end

        module RoutePatch
          @request: ::Sinatra::Request

          def process_route: (*untyped args) { (*untyped) -> untyped } -> untyped

          def params: () -> ::Hash[::String, any]
        end

        module Patcher
          def self?.patched?: () -> bool

          def self?.target_version: () -> Gem::Version?

          def self?.patch: () -> void

          def self?.patch_json?: () -> bool
        end
      end
    end
  end
end
