module Datadog
  module AppSec
    module Contrib
      module Sinatra
        type rack_env = ::Hash[::String, top]
        type rack_response = [::Integer, ::Hash[::String, ::String], ::Array[::String]]
        type rack_app = ^(rack_env) -> rack_response

        class RequestMiddleware
          @app: rack_app

          def initialize: (rack_app app, ?::Hash[::Symbol, top] opt) -> void

          def call: (rack_env env) -> rack_response
        end
      end
    end
  end
end
