module Datadog
  module AppSec
    module Contrib
      module Sinatra
        # Rack middleware for AppSec on Sinatra
        class RequestMiddleware
          def initialize: (untyped app, ?::Hash[untyped, untyped] opt) -> void

          def call: (untyped env) -> untyped
        end
      end
    end
  end
end
