module Datadog
  module AppSec
    module Contrib
      module Sinatra
        class RequestMiddleware
          @app: Rack::app

          def initialize: (Rack::app app, ?::Hash[::Symbol, any] opt) -> void

          def call: (Rack::env env) -> Rack::response
        end
      end
    end
  end
end
