module Datadog
  module AppSec
    class Component
      @processor: Processor?

      @telemetry: Core::Telemetry::Component

      @mutex: ::Mutex

      def self.build_appsec_component: (Core::Configuration::Settings settings, Core::Telemetry::Component telemetry) -> Component?

      private

      def self.incompatible_ffi_version?: () -> bool

      public

      attr_reader security_engine: AppSec::SecurityEngine::Engine?

      attr_reader telemetry: Core::Telemetry::Component

      def initialize: (AppSec::SecurityEngine::Engine security_engine, Core::Telemetry::Component telemetry) -> void

      def reconfigure: (config: ::Hash[::String, untyped], config_path: ::String) -> void

      def reconfigure_lock: () { (?) -> void } -> void

      def shutdown!: () -> void
    end
  end
end
