module Datadog
  module AppSec
    class Component
      @processor: Processor?

      @telemetry: Core::Telemetry::Component

      @mutex: ::Mutex

      def self.build_appsec_component: (Core::Configuration::Settings settings, Core::Telemetry::Component telemetry) -> Component?

      private

      def self.create_processor: (Core::Configuration::Settings settings, Core::Telemetry::Component telemetry) -> Processor?

      public

      attr_reader processor: Processor?

      attr_reader telemetry: Core::Telemetry::Component

      def initialize: (Processor processor, Core::Telemetry::Component telemetry) -> void

      def reconfigure: (ruleset: Processor::RuleMerger::rules, telemetry: Core::Telemetry::Component) -> void

      def reconfigure_lock: () { (?) -> void } -> void

      def shutdown!: () -> void
    end
  end
end
