module Datadog
  module AppSec
    # AppSec event
    module Event
      ALLOWED_REQUEST_HEADERS: untyped

      ALLOWED_RESPONSE_HEADERS: untyped

      # Record events for a trace
      #
      # This is expected to be called only once per trace for the rate limiter
      # to properly apply
      def self.record: (*untyped events) -> (nil | untyped)

      # rubocop:disable Metrics/MethodLength
      def self.record_via_span: (*untyped events) -> untyped
    end
  end
end
