module Datadog
  module AppSec
    module Event
      DERIVATIVE_SCHEMA_KEY_PREFIX: ::String

      DERIVATIVE_SCHEMA_MAX_COMPRESSED_SIZE: ::Integer

      ALLOWED_REQUEST_HEADERS: ::Array[::String]

      ALLOWED_RESPONSE_HEADERS: ::Array[::String]

      def self.record: (Tracing::SpanOperation span, *untyped events) -> void

      def self.record_via_span: (Tracing::SpanOperation span, *untyped events) -> void

      def self.build_service_entry_tags: (untyped event_group) -> ::Hash[::String, untyped]

      def self.tag_and_keep!: (untyped context, untyped waf_result) -> void

      private

      def self.json_parse: (untyped value) -> ::String?

      def self.add_distributed_tags: (untyped trace) -> void
    end
  end
end
