module Datadog
  module AppSec
    module Event
      ALLOWED_REQUEST_HEADERS: untyped

      ALLOWED_RESPONSE_HEADERS: untyped

      MAX_ENCODED_SCHEMA_SIZE: Numeric
      MIN_SCHEMA_SIZE_FOR_COMPRESSION: Numeric

      def self.record: (Datadog::Tracing::SpanOperation, *untyped events) -> (nil | untyped)

      def self.record_via_span: (Datadog::Tracing::SpanOperation, *untyped events) -> untyped

      def self.build_service_entry_tags: (Array[Hash[::Symbol, untyped]] event_group) -> Hash[::String, untyped]
                                       
      def self.add_tags: (Datadog::AppSec::Scope scope, Datadog::AppSec::WAF::Result waf_result) -> void
                       
      private

      def self.compressed_and_base64_encoded: (untyped value) -> untyped

      def self.json_parse: (untyped value) -> untyped

      def self.gzip: (untyped value) -> untyped
                   
      def self.add_distributed_tags: (Datadog::Tracing::TraceOperation trace) -> void
    end
  end
end
