module Datadog
  module AppSec
    module Ext
      INTERRUPT: Symbol
      SCOPE_KEY: String

      TAG_APPSEC_ENABLED: String
      TAG_APM_ENABLED: String
      TAG_APPSEC_EVENT: String
    end
  end
end
