module Datadog
  module AppSec
    class RateLimiter
      @rate_limiter: Datadog::Core::TokenBucket

      THREAD_KEY: :datadog_security_appsec_rate_limiter

      def self.thread_local: () -> RateLimiter

      def self.reset!: () -> void

      private

      def self.trace_rate_limit: () -> ::Integer

      public

      def initialize: (::Integer rate) -> void

      def limit: () { () -> untyped } -> void
    end
  end
end
