module Datadog
  module AppSec
    class ThreadSafeRef
      @current: untyped

      @finalizer: ::Symbol

      @counters: Hash[untyped, Integer]

      @outdated: Array[untyped]

      @mutex: ::Mutex

      def initialize: (WAF::Handle initial_obj, ?finalizer: Symbol) -> void

      def acquire: () -> untyped

      def release: (untyped obj) -> void

      def current=: (untyped obj) -> void

      private

      def finalize: (untyped obj) -> void
    end
  end
end
