module Datadog
  module Tracing
    module Contrib
      module ActiveJob
        module Events
          module RetryStopped
            include ActiveJob::Event

            EVENT_NAME: "retry_stopped.active_job"

            def self?.event_name: () -> untyped

            def self?.span_name: () -> untyped

            def self?.process: (untyped span, untyped event, untyped _id, untyped payload) -> untyped
          end
        end
      end
    end
  end
end
