module Datadog
  module AppSec
    module Contrib
      module Rails
        module Gateway
          class Request < Instrumentation::Gateway::Argument
            attr_reader request: untyped

            def initialize: (untyped request) -> void

            def env: () -> ::Hash[::String, untyped]

            def headers: () -> ::Hash[::String, ::String]

            def host: () -> ::String

            def user_agent: () -> ::String

            def remote_addr: () -> ::String

            def parsed_body: () -> ::Hash[::String, untyped]?

            def route_params: () -> ::Hash[::Symbol, untyped]
          end
        end
      end
    end
  end
end
