module Datadog
  module AppSec
    module Contrib
      module Rails
        module Gateway
          class Request < Instrumentation::Gateway::Argument
            class BodyMeasurement
              attr_accessor byte_length: Integer?
              attr_accessor collect_body: bool

              def initialize: (Integer? byte_length, bool collect_body) -> void
            end

            self.@rewind_rack_input: bool

            def self.rewind_rack_input?: () -> bool

            attr_reader request: untyped

            def initialize: (untyped request) -> void

            def env: () -> ::Hash[::String, untyped]

            def headers: () -> ::Hash[::String, ::String]

            def host: () -> ::String

            def user_agent: () -> ::String

            def remote_addr: () -> ::String

            def parsed_body: () -> ::Hash[::String, untyped]?

            def route_params: () -> ::Hash[::Symbol, untyped]

            def measure_body: (Integer limit) -> BodyMeasurement

            private

            def body_parameters_parsed?: () -> bool

            def measure_body!: (untyped io, limit: Integer) -> Integer?
          end
        end
      end
    end
  end
end
