module Datadog
  module Profiling
    module Ext
      module Forking
        def self.supported?: () -> untyped

        def self.apply!: () -> (false | untyped)
        module Kernel
          def fork: () { () -> untyped } -> untyped

          def at_fork: (untyped stage) ?{ () -> untyped } -> untyped

          def self?.datadog_at_fork_blocks: () -> untyped
        end
        module ProcessDaemonMonkeyPatch
          def daemon: (*untyped args) -> untyped
        end
      end
    end
  end
end
