module Datadog
    module Core
        module Environment
            module BaseHash
                @mutex: ::Thread::Mutex
                @current_hash: ::Integer?
                @current_container_hash: ::String?

                def self.compute: (::String container_tags_hash) -> ::Integer?

                def self.current: () -> ::Integer?

                def self.reset!: () -> nil?
            end
        end
    end
end