module Datadog
  module Core
    module Environment
      module Cgroup
        ENTRY_REGEX: Regexp

        class Entry
          attr_accessor hierarchy: String?
          attr_accessor controllers: String?
          attr_accessor path: String?
          attr_accessor inode: Integer?

          def initialize: (String? hierarchy, String? controllers, String? path, ?Integer? inode) -> void
        end

        def self?.entries: () -> Array[Entry]

        def self?.parse: (String entry_line) -> Entry

        def self?.inode_for: (String? controllers, String? path) -> Integer?
      end
    end
  end
end
