module Datadog
  module Core
    module Environment
      module ClassCount
        self.@class_count_available: bool

        def self?.value: () -> untyped

        def self?.available?: () -> untyped
      end
    end
  end
end
