module Datadog
  module Core
    module Environment
      module ClassCount
        self.@class_count_available: bool

        def self?.value: () -> ::Integer

        def self?.available?: () -> bool
      end
    end
  end
end
