module Datadog
  module Core
    module Environment
      module Container
        UUID_PATTERN: untyped

        CONTAINER_PATTERN: untyped

        PLATFORM_REGEX: untyped

        POD_REGEX: untyped

        CONTAINER_REGEX: untyped

        FARGATE_14_CONTAINER_REGEX: untyped

        class Descriptor < ::Struct[[String, String, String]]
          def self.new: (?String? platform, ?String? container_id, ?String? task_uid) -> instance

          attr_accessor platform: String
          attr_accessor container_id: String
          attr_accessor task_uid: String
        end

        @descriptor: Descriptor?

        def self?.platform: () -> untyped

        def self?.container_id: () -> untyped

        def self?.task_uid: () -> untyped

        def self?.descriptor: () -> untyped
      end
    end
  end
end
