module Datadog
  module Core
    module Environment
      module Ext
        LANG: String

        LANG_ENGINE: String

        LANG_INTERPRETER: String

        LANG_PLATFORM: String

        LANG_VERSION: String

        RUBY_ENGINE: String

        GEM_DATADOG_VERSION: String

        ENGINE_VERSION: String

        DD_SITE_STAGING: String
      end
    end
  end
end
