module Datadog
  module Core
    module Environment
      module Ext
        # Identity
        LANG: untyped

        LANG_ENGINE: untyped

        LANG_INTERPRETER: untyped

        LANG_PLATFORM: untyped

        LANG_VERSION: untyped

        RUBY_ENGINE: untyped

        # e.g. 'ruby', 'jruby', 'truffleruby'
        TRACER_VERSION: untyped

        # e.g for CRuby '3.0.1', for JRuby '9.2.19.0', for TruffleRuby '21.1.0'
        ENGINE_VERSION: untyped
      end
    end
  end
end
