module Datadog
  module Core
    module Environment
      module Git
        @git_repository_url: String?

        @git_commit_sha: String?

        def self?.git_repository_url: () -> String?

        def self?.git_commit_sha: () -> String?
      end
    end
  end
end
