module Datadog
  module Core
    module Environment
      module Platform
        def self?.architecture: () -> String
        def self?.hostname: () -> String?
        def self?.kernel_name: () -> String
        def self?.kernel_release: () -> String?
        def self?.kernel_version: () -> String?
      end
    end
  end
end
