module Datadog
  module Core
    module Environment
      module Process
        @serialized: ::String

        def serialized: () -> ::String

        private

        def entrypoint_workdir: () -> ::String

        def entrypoint_type: () -> ::String

        def entrypoint_name: () -> ::String

        def entrypoint_basedir: () -> ::String
      end
    end
  end
end
