module Datadog
  module Core
    module Environment
      module Process
        self.@serialized: ::String
        self.@tags: ::Array[::String]
        self.@rails_application_name: ::String?

        def self.serialized: () -> ::String

        def self.tags: () -> ::Array[::String]

        def self.rails_application_name=: (::String? name) -> void

        private

        def self.entrypoint_workdir: () -> ::String

        def self.entrypoint_type: () -> ::String

        def self.entrypoint_name: () -> ::String

        def self.entrypoint_basedir: () -> ::String
      end
    end
  end
end
