module Datadog
  module Core
    module Environment
      module Socket
        def self?.hostname: () -> untyped
        def self?.resolved_hostname: (untyped settings) -> String?
      end
    end
  end
end
