module Datadog
  module Core
    module Environment
      # Retrieves number of threads from runtime
      module ThreadCount
        def self?.value: () -> untyped

        def self?.available?: () -> untyped
      end
    end
  end
end
