module Datadog
  module Core
    module Environment
      module VariableHelpers
        extend ::Datadog::Core::Environment::VariableHelpers

        def env_to_bool: (::String | ::Array[::String] var, ?bool? default, ?deprecation_warning: bool) -> bool?

        private

        def decode_array: (::String | ::Array[::String] var, bool deprecation_warning) -> ::String?
      end
    end
  end
end
