module Datadog
  module Core
    # Namespace for handling application environment
    module Environment
      # Defines helper methods for environment
      module VariableHelpers
        extend ::Datadog::Core::Environment::VariableHelpers

        def env_to_bool: (untyped var, ?untyped? default) -> untyped

        def env_to_int: (untyped var, ?untyped? default) -> untyped

        def env_to_float: (untyped var, ?untyped? default) -> untyped

        def env_to_list: (untyped var, ?untyped default) -> untyped

        private

        def decode_array: (untyped var) -> untyped
      end
    end
  end
end
