module Datadog
  module Core
    module Environment
      module VariableHelpers
        extend self

        def env_to_bool: ((String | Array[String]) var, ?untyped default, ?deprecation_warning: bool) -> untyped

        private

        def decode_array: ((String | Array[String]) var, bool deprecation_warning) -> String?
      end
    end
  end
end
