module Datadog
  module Core
    module Environment
      module VMCache
        def self?.global_constant_state: () -> untyped
        def self?.global_method_state: () -> untyped
        def self?.constant_cache_invalidations: () -> untyped
        def self?.constant_cache_misses: () -> untyped

        def self?.available?: () -> untyped
      end
    end
  end
end
