module Datadog
  module Core
    module Environment
      module VMCache
        def self?.global_constant_state: () -> Integer?
        def self?.global_method_state: () -> Integer?
        def self?.constant_cache_invalidations: () -> Integer?
        def self?.constant_cache_misses: () -> Integer?

        def self?.available?: () -> bool
      end
    end
  end
end
