module Datadog
  module AIGuard
    def self.enabled?: () -> bool

    def self.api_client: () -> APIClient?

    def self.evaluate: (*Evaluation::Message messages, ?allow_raise: bool) -> Evaluation::Response

    def self.message: (role: ::String | ::Symbol, content: ::String) -> Evaluation::Message

    def self.tool_call: (::String tool_name, id: ::String | ::Numeric, arguments: ::String) -> Evaluation::Message

    def self.tool_output: (tool_call_id: ::String | ::Numeric, content: ::String) -> Evaluation::Message
  end
end
