module Datadog
  module AppSec
    def self.enabled?: () -> bool

    def self.active_context: () -> Context?

    def self.telemetry: () -> Core::Telemetry::Component

    def self.processor: () -> Processor?

    def self.reconfigure: (ruleset: Processor::RuleMerger::rules, telemetry: Core::Telemetry::Component) -> void

    def self.reconfigure_lock: () { (?) -> untyped } -> void

    def self.perform_api_security_check?: () -> bool

    private

    def self.components: () -> Core::Configuration::Components
  end
end
