module Datadog
  module DI
    type instrumentation_kind = :line | :method
    INSTRUMENTED_COUNTERS_LOCK: Mutex

    self.@instrumented_count: ::Hash[instrumentation_kind, ::Integer]

    def self.enabled?: () -> bool

    def self.all_iseqs: () -> Array[RubyVM::InstructionSequence]
    def self.file_iseqs: () -> Array[RubyVM::InstructionSequence]
    def self.exception_message: (Exception exception) -> untyped
    EXCEPTION_BACKTRACE_LOCATIONS: UnboundMethod
    EXCEPTION_BACKTRACE: UnboundMethod
    def self.iseq_type: (RubyVM::InstructionSequence iseq) -> Symbol?

    def self.in_probe?: () -> bool
    def self.enter_probe: () -> nil
    def self.leave_probe: () -> nil
    def self.array_empty?: (::Array[untyped]) -> bool
    def self.hash_empty?: (::Hash[untyped, untyped]) -> bool
    def self.invoke_proc: (Proc proc, *untyped args) -> untyped

    def self.component: () -> Component

    def self.instrumented_count: (?instrumentation_kind? kind) -> Integer

    def self.instrumented_count_inc: (instrumentation_kind kind) -> void

    def self.instrumented_count_dec: (instrumentation_kind kind) -> void

    private

    def self.validate_kind!: (instrumentation_kind kind) -> void
  end
end
