module Datadog
  module OpenFeature
    self.@adopted_providers: Hash[Provider, bool]?

    def self.enabled?: () -> bool

    def self.engine: () -> EvaluationEngine?

    def self.activate_provider: (Provider provider) -> [Component?, String?]

    def self.deactivate_provider: (Provider provider) -> void

    def self.reattach: (Activation activation) -> void
  end
end
