module Datadog
  module OpenFeature
    def self.enabled?: () -> bool

    def self.engine: () -> EvaluationEngine?

    def self.activate_provider: (Provider provider) -> [Component?, String?]
  end
end
