module Datadog
  module SymbolDatabase
    @mutex: untyped

    @component: untyped

    def self.component: () -> Component?

    def self.set_component: (Component? component) -> void

    def self.enabled?: () -> bool
  end
end
