name: 'Test'

description: 'Run the test suite in batches'

inputs:
  alias:
    description: 'Runtime alias'
    required: true
  container-id:
    description: 'Container Identifier'
    required: true

runs:
  using: "composite"
  steps:
  - name: Configure Git
    run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    shell: bash

  - name: Configure RSpec
    run: ln -s .rspec-local.example .rspec-local
    shell: bash

  - run: bundle exec rake github:run_batch_tests
    shell: bash
    env:
      COVERAGE_DIR: coverage/versions/${{ inputs.alias }}/${{ inputs.container-id }}

  - name: Display debug info
    if: ${{ !cancelled() }}
    shell: bash
    run: |
      df -h

  - name: Debug with SSH connection
    if: ${{ failure() && runner.debug == '1' }}
    uses: mxschmitt/action-tmate@c0afd6f790e3a5564914980036ebf83216678101 # v3.19.0
    with:
      limit-access-to-actor: true
      # This mode will wait at the end of the job for a user to connect and then to terminate the tmate session.
      # If no user has connected within 10 minutes after the post-job step started,
      # it will terminate the tmate session and quit gracefully.
      detached: true

  - name: Validate test agent data
    if: ${{ !cancelled() }}
    run: ruby .github/scripts/test_agent_check.rb
    shell: bash

  - name: Upload junit reports
    if: ${{ !cancelled() }}
    uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
    with:
      name: junit-${{ inputs.alias }}-${{ inputs.container-id }}
      path: tmp/rspec/*.xml

  - name: Upload coverage data
    uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
    with:
      name: coverage-${{ inputs.alias }}-${{ inputs.container-id }}
      path: coverage
      include-hidden-files: true  # Coverage data generated by SimpleCov are hidden
