name: 'Build and Test'

# TODO: Improve  description
description: 'Configure test suite in batches'

inputs:
  alias:
    description: 'Runtime alias'
    required: true
  container-id:
    description: 'Container Identifier'
    required: true

runs:
  using: "composite"
  steps:
  - name: Configure Git
    run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    shell: bash

  - run: bundle exec rake github:run_batch_build
    shell: bash

  - name: Configure RSpec
    run: ln -s .rspec-local.example .rspec-local
    shell: bash

  - run: bundle exec rake github:run_batch_tests
    shell: bash
    env:
      COVERAGE_DIR: coverage/versions/${{ inputs.alias }}/${{ inputs.container-id }}

  - name: Debug with SSH connection
    if: ${{ failure() && runner.debug == '1' }}
    uses: mxschmitt/action-tmate@7b6a61a73bbb9793cb80ad69b8dd8ac19261834c # v3.19.0
    with:
      limit-access-to-actor: true
      # This mode will wait at the end of the job for a user to connect and then to terminate the tmate session.
      # If no user has connected within 10 minutes after the post-job step started,
      # it will terminate the tmate session and quit gracefully.
      detached: true

  - name: Validate test agent data
    if: ${{ !cancelled() }}
    run: ruby .github/scripts/test_agent_check.rb
    shell: bash

  - name: Upload junit reports
    if: ${{ !cancelled() }}
    uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
    with:
      name: junit-${{ inputs.alias }}-${{ inputs.container-id }}
      path: tmp/rspec/*.xml

  - name: Upload coverage data
    uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
    with:
      name: coverage-${{ inputs.alias }}-${{ inputs.container-id }}
      path: coverage
      include-hidden-files: true  # Coverage data generated by SimpleCov are hidden
