# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/climate_control/all/climate_control.rbi
#
# climate_control-0.2.0

module ClimateControl
  def self.env; end
  def self.modify(environment_overrides, &block); end
end
class ClimateControl::Environment
  def [](*args, &block); end
  def []=(*args, &block); end
  def delete(*args, &block); end
  def env; end
  def initialize; end
  def synchronize; end
  def to_hash(*args, &block); end
  extend Forwardable
end
class ClimateControl::UnassignableValueError < ArgumentError
end
class ClimateControl::Modifier
  def cache_environment_after_block; end
  def clone_environment; end
  def copy_overrides_to_environment; end
  def delete_keys_that_do_not_belong; end
  def initialize(env, environment_overrides = nil, &block); end
  def keys_changed_by_block; end
  def keys_to_remove; end
  def prepare_environment_for_block; end
  def process; end
  def revert_changed_keys; end
  def run_block; end
  def stringify_keys(env); end
end
class ClimateControl::Modifier::OverlappingKeysWithChangedValues
  def initialize(hash_1, hash_2); end
  def keys; end
  def overlapping_keys; end
end
