# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/elasticsearch/all/elasticsearch.rbi
#
# elasticsearch-8.1.2

module Elasticsearch
end
class Elasticsearch::Client
  def api_key(arguments); end
  def elasticsearch_validation_request; end
  def encode(api_key); end
  def initialize(arguments = nil, &block); end
  def method_missing(name, *args, &block); end
  def respond_to_missing?(method_name, *args); end
  def setup_cloud_host(cloud_id, user, password, port); end
  def verify_elasticsearch; end
  def verify_with_version_or_header(version, headers); end
  include Elasticsearch::API
  include Elasticsearch::API::Common
end
class Elasticsearch::UnsupportedProductError < StandardError
  def initialize(message = nil); end
end
module Elastic
  def self.client_meta_version; end
end
