# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-around/all/minitest-around.rbi
#
# minitest-around-0.5.0

module MinitestAround
end
class Minitest::Test < Minitest::Runnable
  def run_without_around; end
end
module Minitest::Spec::DSL
  def around(*args, &block); end
end
module Minitest
end
module Minitest::Around
end
