# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/minitest-stub_any_instance/all/minitest-stub_any_instance.rbi
#
# minitest-stub_any_instance-1.0.2

class BasicObject
  def self.stub_any_instance(name, val_or_callable, &block); end
end
