# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/os/all/os.rbi
#
# os-1.1.4

class OS
  def config; end
  def self.app_config_path(name); end
  def self.bits; end
  def self.config; end
  def self.cpu_count; end
  def self.cygwin?; end
  def self.dev_null; end
  def self.doze?; end
  def self.freebsd?; end
  def self.host; end
  def self.host_cpu; end
  def self.host_os; end
  def self.hwprefs_available?; end
  def self.iron_ruby?; end
  def self.java?; end
  def self.jruby?; end
  def self.linux?; end
  def self.mac?; end
  def self.open_file_command; end
  def self.osx?; end
  def self.parse_os_release; end
  def self.posix?; end
  def self.report; end
  def self.rss_bytes; end
  def self.ruby_bin; end
  def self.windows?; end
  def self.x?; end
end
class OS::Underlying
  def self.bsd?; end
  def self.docker?; end
  def self.linux?; end
  def self.windows?; end
end
