# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pimpmychangelog/all/pimpmychangelog.rbi
#
# pimpmychangelog-0.1.3

module PimpMyChangelog
end
class PimpMyChangelog::Pimper
  def better_changelog; end
  def changelog; end
  def initialize(user, project, changelog); end
  def linkify_changelog(changelog); end
  def links_definitions(issues, contributors); end
  def project; end
  def user; end
end
class PimpMyChangelog::Parser
  def changelog; end
  def content; end
  def contributors; end
  def initialize(changelog); end
  def issues; end
end
class GitRemote
  def fetch_url; end
  def initialize(url = nil); end
  def project; end
  def run_command; end
  def user; end
end
class PimpMyChangelog::CLI
  def changelog_path; end
  def initialize; end
  def project; end
  def read_changelog; end
  def run; end
  def self.run!; end
  def user; end
  def write_changelog(content); end
end
