module Datadog
  module Tracing
    module Contrib
      module ActiveJob
        module DataStreams
          def serialize: () -> ::Hash[::String, untyped]

          def deserialize: (::Hash[::String, untyped] job_data) -> void
        end
      end
    end
  end
end
