module Datadog
  module Tracing
    module Contrib
      module ActiveJob
        module Event
          def self.included: (untyped base) -> untyped
          module ClassMethods
            def span_options: () -> untyped

            def configuration: () -> untyped

            def set_common_tags: (untyped span, untyped payload) -> untyped
          end
        end
      end
    end
  end
end
