module Datadog
  module Tracing
    module DataStreams
      class PathwayCodec
        PROPAGATION_KEY: "dd-pathway-ctx"

        PROPAGATION_KEY_BASE64: "dd-pathway-ctx-base64"
        def self.encode: (untyped ctx, untyped carrier) -> (nil | untyped)
        def self.decode: (untyped carrier, untyped processor) -> (nil | untyped)
      end
    end
  end
end
