# frozen_string_literal: true

module Datadog
  module OpenTelemetry
    module API
      module Baggage
        def initialize: (?trace: Datadog::Tracing::TraceOperation?) -> void

        # Returns a new context with empty baggage
        def clear: (?context: untyped) -> untyped

        # Returns the corresponding value for key
        def value: (String key, ?context: untyped) -> String?

        # Returns all baggage values
        def values: (?context: untyped) -> Hash[String, String]

        # Returns a new context with new key-value pair
        def set_value: (String key, String value, ?metadata: String?, ?context: untyped) -> untyped

        # Returns a new context with value at key removed
        def remove_value: (String key, ?context: untyped) -> untyped
      end
    end
  end
end