# frozen_string_literal: true

module Datadog
  module OpenTelemetry
    module API
      module Baggage
        @trace: Datadog::Tracing::TraceOperation?

        def initialize: (?trace: Datadog::Tracing::TraceOperation?) -> void

        def clear: (?context: OpenTelemetry::Context) -> OpenTelemetry::Context

        def value: (String key, ?context: OpenTelemetry::Context) -> String?

        def values: (?context: OpenTelemetry::Context) -> Hash[String, String]

        def set_value: (String key, String value, ?metadata: String?, ?context: OpenTelemetry::Context) -> OpenTelemetry::Context

        def remove_value: (String key, ?context: OpenTelemetry::Context) -> OpenTelemetry::Context
      end
    end
  end
end
