module Datadog
  module Transport
    module HTTP
      module API
        # A mapping of API version => API Routes/Instance
        class Map < Hash[untyped, untyped]
          include Fallbacks
        end
      end
    end
  end
end
