module Datadog
  module Tracing
    module Contrib
      module SuckerPunch
        module Patcher
          include Contrib::Patcher

          def self?.target_version: () -> untyped

          def self?.patch: () -> untyped

          def self?.get_option: (untyped option) -> untyped
        end
      end
    end
  end
end
