module Datadog
  module Profiling
    module TraceIdentifiers
      class Helper
        @endpoint_collection_enabled: bool
        @supported_apis: Array[untyped]

        DEFAULT_SUPPORTED_APIS: ::Array[untyped]

        def initialize: (tracer: Datadog::Tracing::Tracer?, endpoint_collection_enabled: bool, ?supported_apis: untyped) -> void

        def trace_identifiers_for: (::Thread thread) -> untyped
      end
    end
  end
end
