module Datadog
  module AppSec
    module Contrib
      module Sinatra
        module Gateway
          class RouteParams < Instrumentation::Gateway::Argument
            @params: ::Hash[::String, any]

            attr_reader params: ::Hash[::String, any]

            def initialize: (::Hash[::String, any] params) -> void
          end
        end
      end
    end
  end
end
