module Datadog
  module AppSec
    module Contrib
      module Sinatra
        module Gateway
          module Watcher
            def self.watch: () -> void

            def self.watch_request_dispatch: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> void

            def self.watch_request_routed: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> void

            def self.watch_response_body_json: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> void
          end
        end
      end
    end
  end
end
