module Datadog
  module Tracing
    module Pipeline
      class SpanProcessor
        def initialize: (?untyped? operation) ?{ () -> untyped } -> void
        def call: (untyped trace) -> untyped
      end
    end
  end
end
