module Datadog
  module AIGuard
    module Contrib
      module Rack
        class RequestMiddleware
          NETWORK_CLIENT_IP_TAG: ::String

          @app: ::Rack::app

          def initialize: (::Rack::app app, ?::Hash[::Symbol, any] opt) -> void

          def call: (::Rack::env env) -> ::Rack::response

          private

          def consume_ai_guard_executed_flag: () -> bool

          def tag_client_ip: (::Rack::env env) -> void
        end
      end
    end
  end
end
