module Datadog
  module Profiling
    module Collectors
      # Native (C-only) methods for this class. Instance-level types live inline in the `.rb` file.
      class IdleSamplingHelper
        def self._native_stop: (Datadog::Profiling::Collectors::IdleSamplingHelper self_instance) -> true

        def self._native_reset: (Datadog::Profiling::Collectors::IdleSamplingHelper self_instance) -> true

        def self._native_idle_sampling_loop: (IdleSamplingHelper self_instance, CpuAndWallTimeWorker cpu_and_wall_time_worker_instance) -> true
      end
    end
  end
end
