module Datadog
  module Profiling
    module Collectors
      class OldStack < Core::Worker
        include Core::Workers::Polling

        def initialize: (
          OldRecorder recorder,
          max_frames: ::Integer,
          trace_identifiers_helper: Datadog::Profiling::TraceIdentifiers::Helper,
          ?ignore_thread: ::Proc?,
          ?max_time_usage_pct: ::Float,
          ?max_threads_sampled: ::Integer,
          ?thread_api: untyped,
          ?cpu_time_provider: untyped,
          ?fork_policy: untyped,
          ?interval: ::Float,
          ?enabled: bool,
        ) -> void
      end
    end
  end
end
