module Datadog
  module Profiling
    module Collectors
      class Stack
        def self._native_filenames_available?: () -> bool

        def self._native_ruby_native_filename: () -> ::String?
      end
    end
  end
end
