module Datadog
  module Tracing
    module Contrib
      module HTTP
        module Distributed
          class Propagation < Tracing::Distributed::Propagation
            def initialize: () -> void
          end
        end
      end
    end
  end
end
