# frozen_string_literal: true

module Datadog
  module Profiling
    module Ext
      ENV_ENABLED = "DD_PROFILING_ENABLED"
      ENV_UPLOAD_TIMEOUT = "DD_PROFILING_UPLOAD_TIMEOUT"
      ENV_MAX_FRAMES = "DD_PROFILING_MAX_FRAMES"
      ENV_ENDPOINT_COLLECTION_ENABLED = "DD_PROFILING_ENDPOINT_COLLECTION_ENABLED"
      ENV_CODE_PROVENANCE_ENABLED = "DD_PROFILING_CODE_PROVENANCE_ENABLED"
      ENV_ALLOCATION_COUNTING_ENABLED = "DD_PROFILING_ALLOCATION_COUNTING_ENABLED"
      ENV_WAITING_FOR_GVL_THRESHOLD_NS = "DD_PROFILING_WAITING_FOR_GVL_THRESHOLD_NS"
      ENV_EXPERIMENTAL_CPU_INTERVAL_MS = "DD_PROFILING_EXPERIMENTAL_CPU_INTERVAL_MS"

      # WARNING: This should not be used, only for internal testing
      ENV_AGENTLESS = "DD_PROFILING_AGENTLESS" # rubocop:disable CustomCops/EnvStringValidationCop
      module Transport
        module HTTP
          FORM_FIELD_TAG_PROFILER_VERSION = "profiler_version"

          CODE_PROVENANCE_FILENAME = "code-provenance.json"
        end
      end
    end
  end
end
