module Datadog
  module Core
    module Transport
      module HTTP
        module API
          class Endpoint
            attr_reader verb: untyped

            attr_reader path: untyped

            def initialize: (untyped verb, untyped path) -> void

            def call: (untyped env) { (untyped) -> untyped } -> untyped
          end
        end
      end
    end
  end
end
