module Datadog
  module Core
    module Transport
      module HTTP
        module API
          class Instance
            @endpoint: Endpoint

            @adapter: untyped

            @headers: untyped

            attr_reader adapter: untyped

            attr_reader headers: untyped

            attr_reader endpoint: Endpoint

            def initialize: (Endpoint endpoint, untyped adapter, ?::Hash[untyped, untyped] options) -> void

            def encoder: () -> untyped

            def call: (untyped env) -> untyped
          end
        end
      end
    end
  end
end
