module Datadog
  module Core
    module Transport
      module HTTP
        module API
          class Instance
            @endpoint: untyped

            @adapter: untyped

            @headers: untyped

            attr_reader adapter: untyped

            attr_reader headers: untyped

            attr_reader endpoint: untyped

            def initialize: (untyped endpoint, untyped adapter, ?::Hash[untyped, untyped] options) -> void

            def encoder: () -> untyped

            def call: (untyped env) -> untyped
          end
        end
      end
    end
  end
end
