module Datadog
  module Profiling
    module Pprof
      class Builder
        DEFAULT_ENCODING: "UTF-8"

        DESC_FRAME_OMITTED: "frame omitted"

        DESC_FRAMES_OMITTED: "frames omitted"

        attr_reader functions: untyped

        attr_reader locations: untyped

        attr_reader mappings: untyped

        attr_reader sample_types: untyped

        attr_reader samples: untyped

        attr_reader string_table: untyped

        def initialize: () -> void
        def initialize_locations_hash: () -> untyped

        def encode_profile: (untyped profile) -> untyped

        def build_profile: (start: untyped, finish: untyped) -> untyped

        def build_value_type: (untyped `type`, untyped unit) -> untyped

        def build_locations: (untyped backtrace_locations, untyped length) -> untyped

        def build_location: (untyped id, untyped backtrace_location) -> untyped

        def build_line: (untyped function_id, untyped line_number) -> untyped

        def build_function: (untyped id, untyped filename, untyped function_name) -> untyped

        def build_mapping: (untyped id, untyped filename) -> untyped
      end
    end
  end
end
