module Datadog
  module Profiling
    module Pprof
      class Converter
        attr_reader builder: untyped
        def self.sample_value_types: () -> untyped

        def initialize: (untyped builder, untyped sample_type_mappings) -> void

        def group_events: (untyped events) { (untyped) -> untyped } -> untyped

        def add_events!: (untyped events) -> untyped

        def sample_value_index: (untyped `type`) -> untyped

        def build_event_values: (untyped event) -> untyped

        def debug_statistics: () -> nil
        EventGroup: untyped
        class UnknownSampleTypeMappingError < StandardError
          attr_reader type: untyped

          def initialize: (untyped `type`) -> void

          def message: () -> ::String
        end

        def new_group: (untyped event, untyped values) -> untyped

        def update_group: (untyped event_group, untyped event, untyped values) -> untyped
      end
    end
  end
end
