module Perftools
  module Profiles
    Profile: untyped

    ValueType: untyped

    Sample: untyped

    Label: untyped

    Mapping: untyped

    Location: untyped

    Line: untyped

    Function: untyped
  end
end
