module Datadog
  module Profiling
    module Pprof
      class StackSample < Converter
        SAMPLE_TYPES: { cpu_time_ns: ::Array[untyped], wall_time_ns: ::Array[untyped] }

        def self.sample_value_types: () -> untyped

        def initialize: (*untyped _) -> void

        def add_events!: (untyped stack_samples) -> untyped

        def stack_sample_group_key: (untyped stack_sample) -> untyped
        def update_most_recent_trace_sample: (untyped stack_sample) -> (nil | untyped)

        def build_samples: (untyped stack_samples) -> untyped

        def build_sample: (untyped stack_sample, untyped values) -> untyped

        def build_event_values: (untyped stack_sample) -> untyped

        def build_sample_labels: (untyped stack_sample) -> untyped

        def debug_statistics: () -> ::String
      end
    end
  end
end
