module Datadog
  module Profiling
    module Pprof
      class Template
        DEFAULT_MAPPINGS: ::Hash[untyped, untyped]

        attr_reader builder: untyped

        attr_reader converters: untyped

        attr_reader sample_type_mappings: untyped

        def self.for_event_classes: (untyped event_classes) -> untyped

        def initialize: (untyped mappings) -> void

        def add_events!: (untyped event_class, untyped events) -> untyped

        def debug_statistics: () -> untyped

        def to_pprof: (start: untyped, finish: untyped) -> untyped
        class NoProfilingEventConversionError < ArgumentError
          attr_reader type: untyped

          def initialize: (untyped `type`) -> void

          def message: () -> ::String
        end
        class UnknownSampleTypeMappingError < ArgumentError
          attr_reader type: untyped

          def initialize: (untyped `type`) -> void

          def message: () -> ::String
        end
      end
    end
  end
end
