# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec/datadog/core/ddsketch_pprof/ddsketch.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec/datadog/core/ddsketch_pprof/ddsketch.proto", syntax: :proto3) do
    add_message "test.DDSketch" do
      optional :mapping, :message, 1, "test.IndexMapping"
      optional :positiveValues, :message, 2, "test.Store"
      optional :negativeValues, :message, 3, "test.Store"
      optional :zeroCount, :double, 4
    end
    add_message "test.IndexMapping" do
      optional :gamma, :double, 1
      optional :indexOffset, :double, 2
      optional :interpolation, :enum, 3, "test.IndexMapping.Interpolation"
    end
    add_enum "test.IndexMapping.Interpolation" do
      value :NONE, 0
      value :LINEAR, 1
      value :QUADRATIC, 2
      value :CUBIC, 3
    end
    add_message "test.Store" do
      map :binCounts, :sint32, :double, 1
      repeated :contiguousBinCounts, :double, 2
      optional :contiguousBinIndexOffset, :sint32, 3
    end
  end
end

module Test
  DDSketch = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.DDSketch").msgclass
  IndexMapping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.IndexMapping").msgclass
  IndexMapping::Interpolation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.IndexMapping.Interpolation").enummodule
  Store = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Store").msgclass
end
