module Datadog
  module Transport
    module HTTP
      module Adapters
        class Net
          attr_reader hostname: untyped

          attr_reader port: untyped

          attr_reader timeout: untyped

          attr_reader ssl: untyped

          DEFAULT_TIMEOUT: 30

          def initialize: (?untyped? hostname, ?untyped? port, **untyped options) -> void

          def self.build: (untyped agent_settings) -> untyped

          def open: () ?{ () -> untyped } -> untyped

          def call: (untyped env) -> untyped

          def get: (untyped env) -> untyped

          def post: (untyped env) -> untyped

          def url: () -> ::String

          class UnknownHTTPMethod < StandardError
            attr_reader verb: untyped

            def initialize: (untyped verb) -> void

            def message: () -> ::String
          end

          class Response
            include Datadog::Transport::Response

            attr_reader http_response: untyped

            def initialize: (untyped http_response) -> void

            def payload: () -> untyped

            def code: () -> untyped

            def ok?: () -> untyped

            def unsupported?: () -> untyped

            def not_found?: () -> untyped

            def client_error?: () -> untyped

            def server_error?: () -> untyped

            def inspect: () -> ::String
          end
        end
      end
    end
  end
end
