module Datadog
  module Core
    module Telemetry
      module V2
        class AppClientConfigurationChange < Request
          @configuration_changes: Enumerable[[String, Numeric | bool | String]]

          @origin: String

          def initialize: (Enumerable[[String, Numeric | bool | String]] configuration_changes, ?origin: String) -> void

          def to_h: () -> Hash[Symbol, Object]

          private

          def payload: () -> Hash[Symbol, Array[Hash[Symbol, Numeric | bool | String]]]
        end
      end
    end
  end
end
