module Datadog
  module Core
    module Telemetry
      module V2
        class Request
          @request_type: String

          def initialize: (String request_type) -> void

          def to_h: () -> Hash[Symbol, Object]
        end
      end
    end
  end
end
