dependencies:
  - Gemfile
  - '*.gemfile'
  - Appraisals
  - datadog.gemspec
  - tasks/appraisal.rake
  - tasks/dependency.rake
  - .github/workflows/lock-dependency.yml
  - lib/datadog/version.rb
  - appraisal/**
  - gemfiles/**
