dependencies:
  - Gemfile
  - '*.gemfile'
  - datadog.gemspec
  - tasks/dependency.rake
  - tasks/prelock.rb
  - tasks/security_capabilities.rb
  - tasks/appraisal_conversion.rb
  - .github/workflows/lock-dependency.yml
  - lib/datadog/version.rb
  - appraisal/**
  - gemfiles/**
