# Configuration for GitHub Action `.github/workflows/pull-request-labeler.yml`.
# See https://github.com/marketplace/actions/labeler for more information.

ai-guard:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/ai_guard.rb'
    - 'lib/datadog/ai_guard/**'

core:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/core.rb'
    - 'lib/datadog/core/**'

docs:
- changed-files:
  - all-globs-to-all-files: ['**/*.md']

dev/testing:
- changed-files:
  - all-globs-to-all-files: ['{spec/**,integration/**,benchmarks/**}']

profiling:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/profiling.rb'
    - 'lib/datadog/profiling/**'
    - 'ext/datadog_profiling_native_extension/**'

ci-app:
- changed-files:
  - any-glob-to-any-file: ['lib/datadog/ci/**']

# Changes to Data Streams Monitoring
dsm:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/data_streams.rb'
    - 'lib/datadog/data_streams/**'

openfeature:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/open_feature.rb'
    - 'lib/datadog/open_feature/**'

# Changes to Database Monitoring
dbm:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/tracing/contrib/propagation/sql_comment.rb'
    - 'lib/datadog/tracing/contrib/propagation/sql_comment/**'
    - 'lib/datadog/tracing/contrib/{pg,mysql2,trilogy}/**'

logging:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/core/logging/**'
    - 'lib/datadog/tracing/correlation.rb'
    - 'lib/datadog/tracing/contrib/**/log_injection.rb'
    - 'lib/datadog/tracing/contrib/{lograge,semantic_logger}/**'
    - 'lib/datadog/opentelemetry/logs.rb'
    - 'lib/datadog/opentelemetry/sdk/logs_exporter.rb'

serverless:
- changed-files:
  - any-glob-to-any-file: ['lib/datadog/appsec/contrib/aws_lambda/**']

# Changes to ASM
appsec:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/appsec.rb'
    - 'lib/datadog/appsec/**'

tracing:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/tracing.rb'
    - 'lib/datadog/tracing/**'

integrations:
- changed-files:
  - any-glob-to-any-file: ['{lib/datadog/tracing/contrib/**,lib/datadog/appsec/contrib/**}']

dev/github:
- changed-files:
  - all-globs-to-all-files: ['.github/**']

dev/ci:
- changed-files:
  - all-globs-to-all-files: ['.gitlab-ci.yml']

# Version bump pull request
release:
- changed-files:
  - all-globs-to-all-files: ['{CHANGELOG.md,lib/datadog/version.rb}']

# Changes to OpenTelemetry
otel:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/opentelemetry.rb'
    - 'lib/datadog/opentelemetry/**'

# Changes to Single Step Instrumentation
single-step:
- changed-files:
  - any-glob-to-any-file: ['lib-injection/**']

# Changes to Dynamic Instrumentation or Symbol Database
debugger:
- changed-files:
  - any-glob-to-any-file:
    - 'lib/datadog/di.rb'
    - 'lib/datadog/di/**'
    - 'lib/datadog/symbol_database.rb'
    - 'lib/datadog/symbol_database/**'
