module Datadog
  module AppSec
    module Contrib
      module GraphQL
        module Reactive
          module Multiplex
            ADDRESSES: ::Array[::String]

            def self.publish: (AppSec::Reactive::Engine engine, AppSec::Contrib::GraphQL::Gateway::Multiplex gateway_multiplex) -> boolish

            def self.subscribe: (AppSec::Reactive::Engine engine, AppSec::Contrib::GraphQL::Gateway::Multiplex waf_context) -> void
          end
        end
      end
    end
  end
end
