module Datadog
  module Tracing
    module Sampling
      class RateSampler < Sampler
        KNUTH_FACTOR: ::Integer

        @sampler: Core::KnuthSampler
        @decision: ::String?

        def initialize: (?::Float | ::Integer sample_rate, ?decision: ::String?) -> void

        def sample_rate: (*untyped _) -> ::Float

        def sample_rate=: (::Float | ::Integer sample_rate) -> void

        def sample?: (TraceOperation trace) -> bool

        def sample!: (TraceOperation trace) -> bool
      end
    end
  end
end
