module Datadog
  module Tracing
    module Contrib
      module ActionMailer
        module Events
          ALL: ::Array[untyped]

          def self?.all: () -> untyped

          def self?.subscriptions: () -> untyped

          def self?.subscribe!: () -> untyped
        end
      end
    end
  end
end
