require 'datadog/demo_env'

source "https://rubygems.org"

gem 'ffi'
gem 'google-protobuf'

# Choose correct specs for 'datadog' demo environment
gem 'datadog', *Datadog::DemoEnv.gem_spec('datadog')

gem "debug", platforms: %i[ mri mingw x64_mingw ]
