#!/bin/bash
set -euo pipefail

# CHANGELOG.md may only change on a bump_to_version_* (release) or changelog_fix_* (break-glass) branch.

if [[ -z "${HEAD_REF:-}" ]]; then
    echo "Error: HEAD_REF environment variable is not set"
    exit 1
fi

if [[ -z "${BASE_SHA:-}" ]]; then
    echo "Error: BASE_SHA environment variable is not set"
    exit 1
fi

changed_files=$(git diff --no-renames --name-only "${BASE_SHA}"...HEAD)

touches_changelog=false
if grep -qx 'CHANGELOG.md' <<< "${changed_files}"; then
  touches_changelog=true
fi

is_release_branch=false
if [[ "${HEAD_REF}" =~ ^bump_to_version_ ]]; then
  is_release_branch=true
fi

if [[ "${touches_changelog}" = true && "${is_release_branch}" != true && ! "${HEAD_REF}" =~ ^changelog_fix_ ]]; then
  echo "::error::This pull request modifies CHANGELOG.md directly. CHANGELOG.md is generated by the" \
    "release-prep workflow and must only change on a release PR (branch bump_to_version_*)." \
    "Please revert the CHANGELOG.md changes and describe the change in the PR's \"Change log entry\"" \
    "section instead. For a formatting-only fix to CHANGELOG.md itself, open the PR from a branch" \
    "named changelog_fix_* instead."
  exit 1
fi

if [[ "${is_release_branch}" = true && "${touches_changelog}" != true ]]; then
  echo "::error::This pull request is on a release branch (bump_to_version_*) but does not modify" \
    "CHANGELOG.md. Release PRs must update CHANGELOG.md alongside the version bump."
  exit 1
fi
