#!/bin/bash
set -euo pipefail

# CHANGELOG.md may only change on a bump_to_version_* (release) or changelog_fix_* (break-glass) branch.

if [[ -z "${HEAD_REF:-}" ]]; then
    echo "Error: HEAD_REF environment variable is not set"
    exit 1
fi

if [[ -z "${HEAD_SHA:-}" ]]; then
    echo "Error: HEAD_SHA environment variable is not set"
    exit 1
fi

if [[ -z "${BASE_REF:-}" ]]; then
    echo "Error: BASE_REF environment variable is not set"
    exit 1
fi

if ! git rev-parse --verify --quiet "${HEAD_SHA}^{commit}" >/dev/null; then
    echo "Error: pull request commit ${HEAD_SHA} is not present in the local checkout"
    exit 1
fi

base_ref="refs/remotes/origin/${BASE_REF}"
if ! git rev-parse --verify --quiet "${base_ref}^{commit}" >/dev/null; then
    echo "Error: base branch ${BASE_REF} is not present in the local checkout"
    exit 1
fi

if ! merge_base=$(git merge-base "${HEAD_SHA}" "${base_ref}"); then
    echo "Error: no common ancestor between ${HEAD_SHA} and ${base_ref}"
    exit 1
fi

# HEAD is the merge ref, whose history carries base-branch commits made after the pull
# request's recorded base SHA, so a diff anchored at HEAD reports base-branch CHANGELOG.md
# release bumps as pull request changes. Diff the pull request head from its merge base
# with the current base tip instead, matching the pull request's Files changed view.
changed_files=$(git diff --no-renames --name-only "${merge_base}" "${HEAD_SHA}")

touches_changelog=false
if grep -qx 'CHANGELOG.md' <<< "${changed_files}"; then
  touches_changelog=true
fi

is_release_branch=false
if [[ "${HEAD_REF}" =~ ^bump_to_version_ ]]; then
  is_release_branch=true
fi

if [[ "${touches_changelog}" = true && "${is_release_branch}" != true && ! "${HEAD_REF}" =~ ^changelog_fix_ ]]; then
  message=$(cat <<'EOF'
This pull request modifies CHANGELOG.md directly. CHANGELOG.md is generated by the release-prep
workflow and must only change on a release PR (branch bump_to_version_*). Please revert the
CHANGELOG.md changes and describe the change in the PR's "Change log entry" section instead. For a
formatting-only fix to CHANGELOG.md itself, open the PR from a branch named changelog_fix_* instead.
EOF
  )
  echo "::error::${message//$'\n'/ }"
  exit 1
fi

if [[ "${is_release_branch}" = true && "${touches_changelog}" != true ]]; then
  message=$(cat <<'EOF'
This pull request is on a release branch (bump_to_version_*) but does not modify CHANGELOG.md.
Release PRs must update CHANGELOG.md alongside the version bump.
EOF
  )
  echo "::error::${message//$'\n'/ }"
  exit 1
fi
