require 'rubygems'
require 'json'
require 'bundler'

LIB_PATH = File.expand_path('../../lib', __dir__).freeze
GEMFILES_DIR = 'gemfiles/'.freeze
OUTPUT_DOC = 'docs/integration_versions.md'.freeze
OUTPUT_DATA = 'docs/integration_versions.json'.freeze

$LOAD_PATH.unshift(LIB_PATH) unless $LOAD_PATH.include?(LIB_PATH)
require 'datadog'

class GemfileProcessor
  def initialize(directory: GEMFILES_DIR)
    unless Dir.exist?(directory)
      warn("Directory #{directory} does not exist")
    end
    @directory = directory
    @min_gems = { 'ruby' => {} }
    @max_gems = { 'ruby' => {} }
    @gem_sources = { 'ruby' => {} }
    @supported_versions = []
  end

  def process
    parse_gemfiles
    process_integrations
    include_hardcoded_versions
    write_markdown_output
    write_json
  end

  private

  def parse_gemfiles
    gemfiles = Dir.glob(File.join(@directory, '*'))
    gemfiles.each do |gemfile_name|
      runtime = File.basename(gemfile_name).split('_').first
      next unless runtime == 'ruby'
      # parse the gemfile
      if gemfile_name.end_with?('.gemfile.lock')
        process_lockfile(gemfile_name, runtime)
      end
    end

  end

  def process_lockfile(gemfile_name, runtime)
    lockfile_contents = File.read(gemfile_name)
    parser = Bundler::LockfileParser.new(lockfile_contents)
    parser.specs.each do |spec|
      gem_name = spec.name
      version = spec.version.to_s
      update_gem_versions(runtime, gem_name, version, false, gem_source(spec))
    end
  end

  def update_gem_versions(runtime, gem_name, version, unspecified, source = nil)
    return unless version_valid?(version, unspecified)

    @gem_sources[runtime][gem_name] = source

    gem_version = Gem::Version.new(version) unless unspecified
    # Update minimum gems
    if not unspecified
      if @min_gems[runtime][gem_name].nil? || gem_version < Gem::Version.new(@min_gems[runtime][gem_name])
        @min_gems[runtime][gem_name] = version
      end
    end

    # Update maximum gems
    if unspecified
      @max_gems[runtime][gem_name] = Float::INFINITY
    else
      if @max_gems[runtime][gem_name].nil? || (@max_gems[runtime][gem_name] != Float::INFINITY && gem_version > Gem::Version.new(@max_gems[runtime][gem_name]))
        @max_gems[runtime][gem_name] = version
      end
    end
  end

  def gem_source(spec)
    remote = spec.source.remotes.first if spec.source.respond_to?(:remotes)
    return unless remote

    remote.respond_to?(:host) ? remote.host : remote.to_s
  end

  # Helper: Validate the version format
  def version_valid?(version, unspecified)
    return true if unspecified
    return false if version.nil? || version.strip.empty?
    Gem::Version.new(version)
    true
  rescue ArgumentError
    puts "#{version} is invalid format."
    false
  end

  def process_integrations
    Datadog::Tracing::Contrib::REGISTRY.each do |entry|
      integration = entry.name.to_s
      integration_class = entry.klass.class
      package = integration_class.respond_to?(:gem_name) ? integration_class.gem_name : integration

      @supported_versions << {
        integration: integration,
        package: package,
        source: @gem_sources['ruby'][package],
        min_tested: @min_gems['ruby'][package],
        max_tested: @max_gems['ruby'][package],
      }
    end
  end

  def include_hardcoded_versions
    @supported_versions.concat(THIRD_PARTY)

    # `makara` is part of `activerecord`
    @supported_versions << {
      integration: 'makara',
      package: 'makara',
      source: @gem_sources['ruby']['makara'],
      min_tested: @min_gems['ruby']['makara'],
      max_tested: @max_gems['ruby']['makara'],
    }
  end

  def self.third_party_integration(integration, support_url)
    {
      integration: integration,
      package: nil,
      source: nil,
      min_tested: nil,
      max_tested: nil,
      support_kind: 'third_party',
      _support_md: "[3rd-party support](#{support_url})",
    }
  end

  THIRD_PARTY = {
    'httpx' => 'https://honeyryderchuck.gitlab.io/httpx/',
  }.map { |name, url| third_party_integration(name, url) }.freeze

  def write_markdown_output
    comment = <<~COMMENT
      <!--
      # Please do NOT manually edit this file.
      # This file is generated by `bundle exec ruby .github/scripts/update_supported_versions.rb`

      ### Supported Versions Table ###

      This markdown file is generated from the minimum and maximum versions of the integrations we support, as tested in our `gemfile.lock` lockfiles.
      For a list of available integrations, and their supported version ranges, refer to the following:
      -->
    COMMENT
    column_widths = {
      integration: 24,
      ruby_min: 19,
      ruby_max: 19,
    }
    columns = {
      integration: "Integration",
      ruby_min: "Ruby Min",
      ruby_max: "Ruby Max",
    }

    adjusted_widths = columns.transform_values.with_index do |title, index|
      [title.length, column_widths.values[index]].max
    end

    header = "| " + columns.map { |key, title| title.ljust(adjusted_widths[key]) }.join(" | ") + " |"
    separator = "|-" + adjusted_widths.map { |_, width| "-" * width }.join("-|-") + "-|"
    rows = @supported_versions.sort_by { |support| support[:integration].downcase }.map do |support|
      integration_name = support[:integration].ljust(column_widths[:integration])
      ruby_min = doc_version(support, :min_tested).ljust(column_widths[:ruby_min])
      ruby_max = doc_version(support, :max_tested).ljust(column_widths[:ruby_max])

      "| #{integration_name} | #{ruby_min} | #{ruby_max} |"
    end

    File.open(OUTPUT_DOC, 'w') do |file|
      file.puts comment
      file.puts header
      file.puts separator
      rows.each { |row| file.puts row }
    end
  end

  def write_json
    supported_versions = @supported_versions
      # Remove internal fields.
      .map { |support| support.reject { |key, _| key.to_s.start_with?('_') } }
      .sort_by { |support| support[:integration].downcase }
    File.write(OUTPUT_DATA, "#{JSON.pretty_generate(supported_versions)}\n")
  end

  def doc_version(support, key)
    support[:_support_md] || support[key] || 'None'
  end
end

GemfileProcessor.new.process
