module Datadog
  module Core
    module Telemetry
      class Client
        attr_reader emitter: untyped

        attr_reader enabled: untyped

        attr_reader unsupported: untyped

        attr_reader worker: untyped

        include Core::Utils::Forking
        def initialize: (?enabled: bool) -> void

        def disable!: () -> untyped

        def dynamic_configuration_change!: (Enumerable[[String, Numeric | bool | String]] changes) -> void

        def started!: () -> (nil | untyped)

        def emit_closing!: () -> (nil | untyped)

        def stop!: () -> (nil | untyped)

        def integrations_change!: () -> (nil | untyped)

        private

        def heartbeat!: () -> (nil | untyped)
      end
    end
  end
end
