module Datadog
  module Core
    module Telemetry
      class Client
        @dependency_collection: bool
        @started: bool
        @stopped: bool

        attr_reader emitter: untyped

        attr_reader enabled: bool

        attr_reader unsupported: bool

        attr_reader worker: untyped

        include Core::Utils::Forking

        def initialize: (heartbeat_interval_seconds: Numeric, dependency_collection: bool, enabled: bool) -> void

        def disable!: () -> untyped

        def client_configuration_change!: (Enumerable[[String, Numeric | bool | String]] changes) -> void

        def started!: () -> (nil | untyped)

        def emit_closing!: () -> (nil | untyped)

        def stop!: () -> (nil | untyped)

        def integrations_change!: () -> (nil | untyped)

        private

        def heartbeat!: () -> (nil | untyped)
      end
    end
  end
end
