module Datadog
  module Core
    module Telemetry
      module Collector
        include Datadog::Core::Configuration
        def additional_payload: () -> untyped
        def application: () -> untyped
        def configurations: () -> untyped
        def dependencies: () -> untyped
        def host: () -> untyped
        def integrations: () -> untyped
        def runtime_id: () -> untyped
        def tracer_time: () -> untyped

        private

        TARGET_OPTIONS: ::Array["ci.enabled" | "logger.level" | "profiling.advanced.code_provenance_enabled" | "profiling.advanced.endpoint.collection.enabled" | "profiling.enabled" | "runtime_metrics.enabled" | "tracing.analytics.enabled" | "tracing.propagation_style_inject" | "tracing.propagation_style_extract" | "tracing.enabled" | "tracing.log_injection" | "tracing.partial_flush.enabled" | "tracing.partial_flush.min_spans_threshold" | "tracing.priority_sampling" | "tracing.report_hostname" | "tracing.sampling.default_rate" | "tracing.sampling.rate_limit"]

        def additional_payload_variables: () -> untyped

        def format_configuration_value: (untyped value) -> untyped

        def env: () -> untyped

        def service_name: () -> untyped

        def service_version: () -> untyped

        def library_version: () -> untyped

        def products: () -> untyped

        def profiler: () -> { version: untyped }

        def appsec: () -> { version: untyped }

        def agent_transport: () -> untyped

        def instrumented_integrations: () -> untyped

        def instrumented?: (untyped integration) -> untyped

        def patched?: (untyped integration) -> untyped

        def integration_auto_instrument?: (untyped integration) -> untyped

        def integration_compatible?: (untyped integration) -> untyped

        def integration_version: (untyped integration) -> (untyped | nil)

        def patch_error: (untyped integration) -> untyped
      end
    end
  end
end
