module Datadog
  module Core
    module Telemetry
      class Component
        @enabled: bool
        @dependency_collection: bool
        @started: bool
        @stopped: bool
        @worker: Datadog::Core::Telemetry::Worker

        attr_reader enabled: bool

        include Core::Utils::Forking

        def initialize: (heartbeat_interval_seconds: Numeric, dependency_collection: bool, ?enabled: bool) -> void

        def disable!: () -> void

        def client_configuration_change!: (Enumerable[[String, Numeric | bool | String]] changes) -> void

        def started!: () -> void

        def emit_closing!: () -> void

        def stop!: () -> void

        def integrations_change!: () -> void
      end
    end
  end
end
