module Datadog
  module Core
    module Telemetry
      class Emitter
        attr_reader http_transport: untyped

        extend Core::Utils::Forking
        def initialize: (?http_transport: untyped) -> void
        def request: (String request_type, data: Object?, payload: Hash[Symbol, untyped]?) -> Datadog::Core::Telemetry::Http::Adapters::Net::Response
        def self.sequence: () -> untyped
      end
    end
  end
end
