module Datadog
  module Core
    module Telemetry
      class Event
        include Telemetry::Collector

        API_VERSION: "v1"

        attr_reader api_version: untyped

        def initialize: () -> void
        def telemetry_request: (request_type: untyped, seq_id: untyped) -> untyped

        private

        def payload: (untyped request_type) -> untyped

        def app_started: () -> untyped

        def app_integrations_change: () -> untyped
      end
    end
  end
end
