module Datadog
  module Core
    module Telemetry
      module Event
        extend Core::Utils::Forking

        self.@sequence: Datadog::Core::Utils::Sequence

        def self.configuration_sequence: () -> Datadog::Core::Utils::Sequence
      end
    end
  end
end
