module Datadog
  module Core
    module Telemetry
      module Event
        # common to app-started and app-client-configuration-change
        extend Core::Utils::Forking

        self.@sequence: Datadog::Core::Utils::Sequence
      end
    end
  end
end
