module Datadog
  module Core
    module Telemetry
      class Heartbeat < Core::Worker
        include Core::Workers::Polling
        include Core::Workers::Async::Thread
        include Core::Workers::Async::Thread::PrependedMethods
        include Core::Workers::IntervalLoop

        def initialize: (?enabled: bool, heartbeat_interval_seconds: Numeric) ?{ () -> void } -> void

        def loop_wait_before_first_iteration?: () -> bool?

        private

        def start: () -> void
      end
    end
  end
end
