module Datadog
  module Core
    module Telemetry
      class Heartbeat < Core::Worker
        include Core::Workers::Polling

        DEFAULT_INTERVAL_SECONDS: 60

        def initialize: (?enabled: bool, ?interval: untyped) ?{ () -> untyped } -> void

        def loop_wait_before_first_iteration?: () -> true

        private

        def start: () -> untyped
      end
    end
  end
end
