module Datadog
  module Core
    module Telemetry
      module Logging
        module DatadogStackTrace
          GEM_ROOT: String

          def self.from: (Exception exception) -> String?
        end

        extend Datadog::Core::Telemetry::Logging

        def report: (Exception exception, level: Symbol, ?description: String?) -> void

        def error: (String description) -> void

        private

        def dispatch: (Datadog::Core::Telemetry::Event::Log event) -> void
      end
    end
  end
end
