module Datadog
  module Core
    module Telemetry
      module Logger
        def self.report: (Exception exception, ?level: Symbol, ?description: String?) -> void

        def self.error: (String description) -> void

        private

        def self.instance: () -> Datadog::Core::Telemetry::Component?
      end
    end
  end
end
