module Datadog
  module Core
    module Telemetry
      class MetricWorker < Core::Worker
        include Core::Workers::Polling
        include Core::Workers::IntervalLoop
        include Core::Workers::Async::Thread
        prepend Core::Workers::Polling::PrependedMethods

        def initialize: (heartbeat_interval_seconds: untyped, ?enabled: bool) { () -> untyped } -> void

        def loop_wait_before_first_iteration?: () -> true

        private

        def start: () -> untyped
      end
    end
  end
end
