module Datadog
  module Core
    module Telemetry
      class Worker < Core::Worker
        include Core::Workers::Polling
        include Core::Workers::IntervalLoop
        include Core::Workers::Async::Thread
        prepend Core::Workers::Polling::PrependedMethods

        DEFAULT_INTERVAL_SECONDS: 60

        def initialize: (enabled: bool, heartbeat_interval_seconds: untyped) ?{ () -> untyped } -> void

        def loop_wait_before_first_iteration?: () -> true

        private

        def start: () -> untyped
      end
    end
  end
end
