module Datadog
  module Core
    module Telemetry
      class Worker
        include Core::Workers::Polling
        include Core::Workers::Async::Thread
        include Core::Workers::Async::Thread::PrependedMethods
        include Core::Workers::IntervalLoop
        include Core::Workers::Queue

        @emitter: Emitter

        def initialize: (?enabled: bool, heartbeat_interval_seconds: Numeric, emitter: Emitter) -> void

        def start: () -> void

        private

        def heartbeat!: () -> void
      end
    end
  end
end
