extends: default

rules:
  document-start: disable
  line-length: disable

  indentation:
    spaces: consistent
    indent-sequences: consistent

  comments:
    min-spaces-from-content: 1

  truthy:
    check-keys: false # Avoids `on:` key being marked as a boolean
