source 'https://rubygems.org'

gemspec

# Add debugger for pry that's compatible with 0.10.4
gem 'pry-nav', git: 'https://github.com/nixme/pry-nav.git', branch: 'master'
# This file was generated by Appraisal

gem 'rails', '6.0.3.2'
gem 'redis-rack-cache', '2.2.1' # For caching
gem 'pry'