source 'https://rubygems.org'

gemspec

# Add debugger for pry that's compatible with 0.10.4
gem 'pry-nav', git: 'https://github.com/nixme/pry-nav.git', branch: 'master'
# All published versions of codecov require Ruby 2.4+
gem 'codecov', git: 'https://github.com/DataDog/codecov-ruby.git', branch: 'support-ruby-2.0+'
# This file was generated by Appraisal
