module Datadog
  module Core
    module Remote
      class Configuration
        # Path stores path information
        class Path
          class ParseError < StandardError
          end

          RE: ::Regexp

          def self.parse: (::String path) -> Path

          attr_reader source: ::String

          attr_reader org_id: ::Integer?

          attr_reader product: ::String

          attr_reader config_id: ::String

          attr_reader name: ::String

          def initialize: (source: ::String, product: ::String, config_id: ::String, name: ::String, ?org_id: ::Integer?) -> void

          def to_s: () -> ::String

          def ==: (Path other) -> bool

          def hash: () -> ::Integer

          def eql?: (Path other) -> bool
        end
      end
    end
  end
end
