module Datadog
  module Tracing
    module Contrib
      module Dalli
        module Ext
          ENV_COMMAND_ENABLED: ::String

          ENV_ENABLED: "DD_TRACE_DALLI_ENABLED"

          ENV_ANALYTICS_ENABLED: "DD_TRACE_DALLI_ANALYTICS_ENABLED"

          ENV_ANALYTICS_SAMPLE_RATE: "DD_TRACE_DALLI_ANALYTICS_SAMPLE_RATE"

          ENV_PEER_SERVICE: "DD_TRACE_DALLI_PEER_SERVICE"
          ENV_SERVICE_NAME: "DD_TRACE_DALLI_SERVICE_NAME"

          PEER_SERVICE_SOURCES: Array[String]
          QUANTIZE_MAX_CMD_LENGTH: 100

          DEFAULT_PEER_SERVICE_NAME: "memcached"

          SPAN_COMMAND: "memcached.command"

          SPAN_TYPE_COMMAND: "memcached"

          TAG_COMMAND: "memcached.command"

          TAG_COMPONENT: "dalli"

          TAG_OPERATION_COMMAND: "command"

          TAG_SYSTEM: "memcached"
        end
      end
    end
  end
end
