module Datadog
  module Tracing
    module Contrib
      module Dalli
        module Instrumentation
          def self.included: (untyped base) -> untyped
          module InstanceMethods
            def request: (untyped op, *untyped args) -> untyped

            private

            def datadog_configuration: () -> untyped
          end
        end
      end
    end
  end
end
