module Datadog
  module Tracing
    module Contrib
      module Dalli
        module Quantize
          def self?.format_command: (untyped operation, untyped args) -> untyped
        end
      end
    end
  end
end
