module Datadog
  module Tracing
    module Configuration
      module Dynamic
        class LogInjectionEnabled < SimpleOption
          def initialize: () -> void
        end
        class TracingHeaderTags < SimpleOption
          def initialize: () -> void

          def call: (Array[Hash[String, String]]? tracing_header_tags) -> Datadog::Core::Telemetry::Event::telemetry_value
        end
        class TracingSamplingRate < SimpleOption
          def initialize: () -> void
          def call: ((Integer | Float)? tracing_sampling_rate) -> Datadog::Core::Telemetry::Event::telemetry_value

          def configuration_object: () -> Core::Configuration::Options::InstanceMethods
        end

        class TracingSamplingRules < SimpleOption
          def initialize: () -> void
          def call: (Array[Hash[String, untyped]]? tracing_sampling_rules) -> Datadog::Core::Telemetry::Event::telemetry_value
          def configuration_object: () -> Core::Configuration::Options::InstanceMethods
        end

        # Correct type is `OPTIONS: Array[[String, String, Option]]`
        # but steep can't recognize that.
        OPTIONS: Array[Array[(String | Option)]]
      end
    end
  end
end
