module Datadog
  module Tracing
    module Configuration
      module Settings
        def self.extended: (untyped base) -> untyped

        def self.otlp_headers_parser: (String env_var_name) -> ^(String?) -> Hash[String, String]
      end
    end
  end
end
