module Datadog
  module OpenFeature
    module Configuration
      module Source
        class Resolution
          @enabled: bool

          attr_reader source: String

          def initialize: (String source, enabled: bool) -> void

          def enabled?: () -> bool
        end
      end
    end
  end
end
