module Datadog
  module OpenFeature
    module Configuration
      module Source
        class Resolution
          @enabled: bool

          attr_reader source: String

          def initialize: (enabled: bool, source: String) -> void

          def enabled?: () -> bool
        end
      end
    end
  end
end
