module Datadog
  module Tracing
    module Metadata
      module ChangeTracking
        include Tagging

        def set_tag: (untyped key, ?untyped value) -> untyped
        def clear_tag: (untyped key) -> untyped
        def set_metric: (untyped key, untyped value) -> untyped
        def clear_metric: (untyped key) -> untyped

        private

        def metric_tag?: (untyped key, untyped value) -> bool
        def metadata_change_ignored?: (untyped key) -> bool
        def publish_metadata_change: (untyped previous_value, untyped key) -> untyped
      end
    end
  end
end
