module Datadog
  module Tracing
    module Metadata
      module MetaStruct
        def set_meta_struct: (Hash[String, untyped] meta_struct) -> void

        def meta_struct: () -> Hash[String, untyped]
      end
    end
  end
end
