module Datadog
  module Tracing
    module Metadata
      module Metastruct
        type metastruct = Hash[String, untyped]

        def metastruct=: (metastruct second) -> void

        def deep_merge_metastruct!: (metastruct second) -> void

        def get_metastruct_field: (String key) -> untyped

        def metastruct: () -> metastruct
      end
    end
  end
end
