module Datadog
  module Core
    module Transport
      module HTTP
        # Namespace for API components
        module API
          # Default API versions
          ROOT: "root"

          def self?.defaults: () -> untyped
        end
      end
    end
  end
end
