module Datadog
  module Core
    module Transport
      module HTTP
        # Builds new instances of Transport::HTTP::Client
        class Builder
          REGISTRY: untyped

          attr_reader apis: untyped

          attr_reader api_options: untyped

          attr_reader default_adapter: untyped

          attr_reader default_api: untyped

          attr_reader default_headers: untyped

          def initialize: () { (untyped) -> untyped } -> void

          def adapter: (untyped config, *untyped args, **untyped kwargs) -> untyped

          def headers: (?::Hash[untyped, untyped] values) -> untyped

          # Adds a new API to the client
          # Valid options:
          #  - :adapter
          #  - :default
          #  - :fallback
          #  - :headers
          def api: (untyped key, untyped spec, ?::Hash[untyped, untyped] options) -> untyped

          def default_api=: (untyped key) -> untyped

          def to_transport: (untyped klass) -> untyped

          def to_api_instances: () -> untyped

          def api_instance_class: () -> untyped

          # Raised when the API key does not match known APIs.
          class UnknownApiError < StandardError
            attr_reader key: untyped

            def initialize: (untyped key) -> void

            def message: () -> ::String
          end

          # Raised when the identifier cannot be matched to an adapter.
          class UnknownAdapterError < StandardError
            attr_reader type: untyped

            def initialize: (untyped `type`) -> void

            def message: () -> ::String
          end

          # Raised when an adapter cannot be resolved for an API instance.
          class NoAdapterForApiError < StandardError
            attr_reader key: untyped

            def initialize: (untyped key) -> void

            def message: () -> ::String
          end

          # Raised when built without defining APIs.
          class NoApisError < StandardError
            def message: () -> "No APIs configured for transport!"
          end

          # Raised when client built without defining a default API.
          class NoDefaultApiError < StandardError
            def message: () -> "No default API configured for transport!"
          end
        end
      end
    end
  end
end
