module Datadog
  module Core
    module Transport
      module HTTP
        # HTTP transport behavior for agent feature negotiation
        module Negotiation
          # Response from HTTP transport for agent feature negotiation
          class Response
            include Datadog::Transport::HTTP::Response

            include Core::Transport::Negotiation::Response

            def initialize: (untyped http_response, ?::Hash[untyped, untyped] options) -> void
          end

          # Extensions for HTTP client
          module Client
            def send_info_payload: (untyped request) -> untyped
          end

          module API
            # Extensions for HTTP API Spec
            module Spec
              attr_reader info: untyped

              def info=: (untyped endpoint) -> untyped

              def send_info: (untyped env) ?{ () -> untyped } -> untyped

              # Raised when traces sent but no traces endpoint is defined
              class NoNegotiationEndpointDefinedError < StandardError
                attr_reader spec: untyped

                def initialize: (untyped spec) -> void

                def message: () -> "No info endpoint is defined for API specification!"
              end
            end

            # Extensions for HTTP API Instance
            module Instance
              def send_info: (untyped env) -> untyped

              # Raised when traces sent to API that does not support traces
              class NegotiationNotSupportedError < StandardError
                attr_reader spec: untyped

                def initialize: (untyped spec) -> void

                def message: () -> "Info not supported for this API!"
              end
            end

            # Endpoint for negotiation
            class Endpoint < Datadog::Transport::HTTP::API::Endpoint
              def initialize: (untyped path) -> void

              def call: (untyped env) ?{ () -> untyped } -> untyped
            end
          end
        end
      end
    end
  end
end
