module Datadog
  module OpenFeature
    module Transport
      module Exposures
        class EncodedParcel
          include Datadog::Core::Transport::Parcel

          def encode_with: (Core::Encoding::Encoder) -> ::String
        end

        class Request < Datadog::Core::Transport::Request
          attr_reader headers: ::Hash[::Symbol, untyped]

          def initialize: (OpenFeature::Transport::Exposures::EncodedParcel, ?::Hash[::Symbol, untyped]?) -> void
        end

        class Transport
          attr_reader apis: Core::Transport::HTTP::API::Map

          attr_reader client: OpenFeature::Transport::HTTP::Client

          attr_reader default_api: ::String

          attr_reader logger: Core::Logger

          def initialize: (Core::Transport::HTTP::API::Map, ::String, ?logger: Core::Logger) -> void

          def send_exposures: (::Hash[::Symbol, untyped], ?headers: ::Hash[::Symbol, untyped]?) -> Core::Transport::Response
        end
      end
    end
  end
end
