module Datadog
  module OpenFeature
    module Transport
      module HTTP
        def self?.build: (
          agent_settings: Core::Configuration::AgentSettings,
          logger: Core::Logger,
          ?headers: ::Hash[::Symbol, untyped]?
        ) ?{ (Core::Transport::HTTP::Builder) -> void } -> OpenFeature::Transport::Exposures::Transport
      end
    end
  end
end
