module Datadog
  module AppSec
    module Contrib
      module Sinatra
        module Configuration
          # Custom settings for the Rack integration
          class Settings < Datadog::AppSec::Contrib::Configuration::Settings
          end
        end
      end
    end
  end
end
