module Datadog
  module Core
    module ErrorTracking
      class Component
        @tracer: untyped
        @instrumented_files: untyped

        @modules_to_instrument: untyped
        @filter_function: untyped
        @handled_exc_tracker: untyped

        @module_path_getter: untyped

        attr_accessor handled_exc_tracker: untyped

        attr_accessor module_path_getter: untyped

        attr_accessor tracer: untyped

        attr_accessor modules_to_instrument: untyped

        attr_accessor instrumented_files: untyped

        def initialize: (tracer: untyped, instrumentation_scope: untyped, modules_to_instrument: untyped) -> void
        def start: () -> untyped
        def shutdown!: () -> untyped
        def _generate_span_event: (untyped exception) -> untyped

        def add_instrumented_file: (untyped file_path) -> untyped
      end
    end
  end
end
