module Datadog
  module Profiling
    module Encoding
      module Profile
        module Protobuf
          def self?.encode: (event_count: untyped, event_groups: untyped, start: untyped, finish: untyped) -> untyped
        end
      end
    end
  end
end
