module Datadog
  module Tracing
  module Transport
    module IO
      class Response
        include Datadog::Core::Transport::Response

        attr_reader result: untyped

        def initialize: (untyped result) -> void

        def ok?: () -> true
      end
    end
  end
end
end
