# frozen_string_literal: true

require 'json'
require 'pp' # rubocop:disable Lint/RedundantRequireStatement

# Pretty print setup
class ConfigPrinter < ::PP
  # Apply Ruby 3.4 `pp_hash_pair` method on all versions for consistency
  # https://github.com/ruby/pp/commit/59844ba65aee5a0c1ef29bc79188228e03463d1d
  # This way we can run this task on any version of Ruby
  # On versions older than 3.4, the result would look like {:key=>'value'}
  def pp_hash_pair(k, v)
    if Symbol === k
      sym_s = k.inspect
      if sym_s[1].match?(/["$@!]/) || sym_s[-1].match?(/[%&*+\-\/<=>@\]^`|~]/)
        text "#{k.to_s.inspect}:"
      else
        text "#{k}:"
      end
    else
      pp k
      text ' '
      text '=>'
    end
    group(1) {
      breakable
      pp v
    }
  end

  def self.pp(data)
    output = +''
    q = new(output, 124)
    q.group(8) do
      q.pp(data)
    end
    q.flush
    output
  end
end

namespace :local_config_map do
  # We only keep env vars as strings
  data = JSON.parse(File.read('supported-configurations.json')).transform_keys(&:to_sym)
  data[:supportedConfigurations].each_value { |config| config.transform_keys!(&:to_sym) }
  alias_to_canonical = data[:aliases].each_with_object({}) do |(canonical, alias_list), h|
    alias_list.each do |alias_name|
      raise "The alias #{alias_name} is already used for #{h[alias_name]}." if h[alias_name]

      h[alias_name] = canonical
    end
  end
  data = data.map { |k, v| [k, v.sort.to_h] }.to_h
  alias_to_canonical = alias_to_canonical.sort.to_h

  # Read the data from the JSON file and generate ahead-of-time map for supported configurations, aliases and deprecations
  task :generate do
    File.write(
      'lib/datadog/core/configuration/supported_configurations.rb',
      <<~RUBY
        # frozen_string_literal: true

        # This file is auto-generated by `rake local_config_map:generate`, do not change manually!
        # Please refer to `docs/AccessEnvironmentVariables.md` for more information.

        module Datadog
          module Core
            module Configuration
              SUPPORTED_CONFIGURATIONS =
                #{ConfigPrinter.pp(data[:supportedConfigurations])}.freeze

              ALIASES =
                #{ConfigPrinter.pp(data[:aliases])}.freeze

              DEPRECATIONS =
                #{ConfigPrinter.pp(data[:deprecations])}.freeze

              ALIAS_TO_CANONICAL =
                #{ConfigPrinter.pp(alias_to_canonical)}.freeze
            end
          end
        end
      RUBY
    )
  end
end
