#!/bin/sh
here="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
hooks="$(dirname -- "$here")"
compiled="$hooks/compiled/require-skill"

if [ -x "$compiled" ]; then
    exec "$compiled" "$@"
fi

exec ruby --disable-gems "$hooks/require-skill.rb" "$@"
