module Datadog
  module Core
    module Transport
      module HTTP
        module Adapters
          class Test
            attr_reader buffer: untyped

            attr_reader status: untyped

            def initialize: (?untyped? buffer, **untyped options) -> void

            def call: (untyped env) -> untyped

            def buffer?: () -> untyped

            def add_request: (untyped env) -> (untyped | nil)

            def set_status!: (untyped status) -> untyped

            def url: () -> nil

            class Response
              include Datadog::Core::Transport::Response

              attr_reader body: untyped

              attr_reader code: untyped

              def initialize: (untyped code, ?untyped? body) -> void

              def payload: () -> untyped

              def ok?: () -> untyped

              def unsupported?: () -> untyped

              def not_found?: () -> untyped

              def client_error?: () -> untyped

              def server_error?: () -> untyped

              def inspect: () -> ::String
            end
          end
        end
      end
    end
  end
end
