module Datadog
  module Core
    module Transport
      module Ext
        module HTTP
          ADAPTER: :http

          DEFAULT_HOST: "127.0.0.1"

          DEFAULT_PORT: 8126

          HEADER_CONTAINER_ID: ::String

          HEADER_DD_API_KEY: ::String

          HEADER_CLIENT_COMPUTED_TOP_LEVEL: ::String

          HEADER_META_LANG: ::String

          HEADER_META_LANG_VERSION: ::String

          HEADER_META_LANG_INTERPRETER: ::String

          HEADER_META_TRACER_VERSION: ::String
        end

        module Test
          ADAPTER: :test
        end

        module UnixSocket
          ADAPTER: :unix

          DEFAULT_PATH: "/var/run/datadog/apm.socket"

          DEFAULT_TIMEOUT_SECONDS: 1
        end
      end
    end
  end
end
