module Datadog
  module Core
    module Transport
      # Namespace for HTTP transport components
      module HTTP
        # NOTE: Due to... legacy reasons... This class likes having a default `AgentSettings` instance to fall back to.
        # Because we generate this instance with an empty instance of `Settings`, the resulting `AgentSettings` below
        # represents only settings specified via environment variables + the usual defaults.
        #
        # DO NOT USE THIS IN NEW CODE, as it ignores any settings specified by users via `Datadog.configure`.
        DO_NOT_USE_ENVIRONMENT_AGENT_SETTINGS: untyped

        # Builds a new Transport::HTTP::Client
        def self?.new: (untyped klass) ?{ (untyped) -> untyped } -> untyped

        # Builds a new Transport::HTTP::Client with default settings
        # Pass a block to override any settings.
        def self?.root: (?agent_settings: untyped, **untyped options) { (untyped) -> untyped } -> untyped

        def self?.default_headers: () -> untyped

        def self?.default_adapter: () -> untyped

        def self?.default_hostname: (?logger: untyped) -> untyped

        def self?.default_port: (?logger: untyped) -> untyped

        def self?.default_url: (?logger: untyped) -> nil
      end
    end
  end
end
