module Datadog
  module Core
    module Transport
      class Parcel
        @data: untyped

        @content_type: untyped

        @content_encoding: untyped

        def initialize: (untyped data, ?content_type: untyped?, ?content_encoding: untyped?) -> void

        attr_reader data: untyped

        def length: () -> untyped

        attr_reader content_type: untyped

        attr_reader content_encoding: untyped
      end
    end
  end
end
