module Datadog
  module Core
    module Transport
      module Parcel
        attr_reader data: untyped

        def initialize: (untyped data) -> void

        def encode_with: (untyped encoder) -> untyped
      end
    end
  end
end
