module Datadog
  module Core
    module Transport
      module Response
        def payload: () -> nil

        def ok?: () -> nil

        def unsupported?: () -> nil

        def not_found?: () -> nil

        def client_error?: () -> nil

        def server_error?: () -> nil

        def internal_error?: () -> nil

        def inspect: () -> ::String
      end

      class InternalErrorResponse
        include Response

        attr_reader error: untyped

        def initialize: (untyped error) -> void

        def internal_error?: () -> true

        def inspect: () -> ::String
      end
    end
  end
end
