module Datadog
  module Core
    module Remote
      module Transport
        module Config
          class Request < Datadog::Core::Transport::Request
          end

          module Response
            attr_reader roots: untyped

            attr_reader targets: untyped

            attr_reader target_files: untyped

            attr_reader client_configs: untyped

            attr_reader empty: bool

            def empty?: () -> bool
          end

          class Transport < Core::Transport::Transport
            def send_config: (untyped payload) -> untyped
          end
        end
      end
    end
  end
end
