module Datadog
  module Core
    module Remote
      module Transport
        module HTTP
          def self?.root: (agent_settings: untyped, ?logger: untyped, ?api_version: untyped?, ?headers: untyped?) ?{ (untyped) -> untyped } -> untyped
          def self?.v7: (agent_settings: untyped, ?logger: untyped, ?api_version: untyped?, ?headers: untyped?) ?{ (untyped) -> untyped } -> untyped
        end
      end
    end
  end
end
