module Datadog
  module Core
    module Remote
      module Transport
        module HTTP
          def self?.new: (untyped klass) { (?) -> untyped } -> untyped
          def self?.root: (agent_settings: untyped, **untyped options) ?{ (untyped) -> untyped } -> untyped
          def self?.v7: (agent_settings: untyped, **untyped options) ?{ (untyped) -> untyped } -> untyped

          def self?.default_headers: () -> untyped

          def self?.default_adapter: () -> untyped
        end
      end
    end
  end
end
