module Datadog
  module AppSec
    module Configuration
      # Settings
      module Settings
        extend Datadog::Core::Configuration::Base::ClassMethods
        include Datadog::Core::Configuration::Base::InstanceMethods
        extend Datadog::Core::Configuration::Options::ClassMethods
        include Datadog::Core::Configuration::Options::InstanceMethods

        DEFAULT_OBFUSCATOR_KEY_REGEX: ::String
        DEFAULT_OBFUSCATOR_VALUE_REGEX: ::String
        APPSEC_VALID_TRACK_USER_EVENTS_MODE: ::Array[String]
        APPSEC_VALID_TRACK_USER_EVENTS_ENABLED_VALUES: ::Array[String]

        def self.extended: (untyped base) -> untyped

        def self.add_settings!: (untyped base) -> untyped

        def enabled:  -> bool
      end
    end
  end
end
