module Datadog
  module Tracing
    module Contrib
      module Excon
        module Patcher
          include Contrib::Patcher

          def self?.target_version: () -> untyped

          def self?.patch: () -> untyped

          def self?.add_middleware: () -> untyped
        end
      end
    end
  end
end
