name: 'Generate bundle cache key'

description: 'Create a gem cache key for all lockfiles for the current version of Ruby'

outputs:
  cache-key:
    description: 'Cache key for the bundle'
    value: ${{ steps.generate.outputs.cache-key }}

runs:
  using: composite
  steps:
    - name: Generate cache key
      id: generate
      shell: bash
      run: |
        ruby_env="$(ruby -e 'puts RUBY_DESCRIPTION')-$(bundle --version)"
        hash="${{ hashFiles(
          '.github/actions/bundle-cache-key/action.yml',
          'Gemfile*.lock',
          'gemfiles/*.gemfile.lock',
          'tasks/github.rake',
          'tasks/dependency.rake',
          'tasks/appraisal_conversion.rb'
        ) }}"
        echo "cache-key=bundle-${ruby_env}-${hash}" >> "$GITHUB_OUTPUT"
