module Datadog
  module AppSec
    module Contrib
      module Excon
        module Patcher
          def self?.patched?: () -> bool

          def self?.target_version: () -> ::Gem::Version

          def self?.patch: () -> bool
        end
      end
    end
  end
end
