module Datadog
  module AppSec
    module Contrib
      module Excon
        class SSRFDetectionMiddleware
          def request_call: (::Excon::Middleware::Base::datum data) -> Excon::Middleware::Base::datum

          def response_call: (::Excon::Middleware::Base::datum data) -> ::Excon::Middleware::Base::datum

          private

          def request_url: (::Excon::Middleware::Base::datum data) -> ::String

          def normalize_headers: (::Hash[::String, ::String | ::Array[::String]]? headers) -> ::Hash[::String, ::String]

          def handle: (SecurityEngine::result result, context: Context) -> void
        end
      end
    end
  end
end
