module Datadog
  module AppSec
    module Contrib
      module Excon
        class SSRFDetectionMiddleware
          SAMPLE_BODY_KEY: ::Symbol

          def request_call: (::Excon::Middleware::Base::datum data) -> Excon::Middleware::Base::datum

          def response_call: (::Excon::Middleware::Base::datum data) -> ::Excon::Middleware::Base::datum

          private

          def mark_body_sampling!: (::Excon::Middleware::Base::datum data, context: Context) -> void

          def parse_body: (Utils::HTTP::Body::body body, content_type: ::String?) -> ::Helpers::json?

          def request_url: (::Excon::Middleware::Base::datum data) -> ::String

          def normalize_headers: (::Hash[::String, ::String | ::Array[::String]]? headers) -> ::Hash[::String, ::String]

          def handle: (SecurityEngine::result result, context: Context) -> void
        end
      end
    end
  end
end
