module Datadog
  module AppSec
    module Utils
      module HTTP
        module Body
          type body = ::String | ::StringIO | ::IO | nil

          def self.parse: (body, media_type: MediaType) -> ::Helpers::json?
        end
      end
    end
  end
end
