module Datadog
  module AppSec
    module Utils
      module HTTP
        module BodyReader
          def self?.read: (untyped body, limit: Integer, ?rewind_before_read: bool) -> String?

          def self?.read_stream: (Utils::HTTP::_RewindableIO body, limit: Integer, rewind_before_read: bool) -> String?
                               | (Utils::HTTP::_ReadableIO body, limit: Integer, ?rewind_before_read: false) -> String

          private

          def self?.rewind: (Utils::HTTP::_ReadableIO body) -> false
                          | (Utils::HTTP::_RewindableIO body) -> bool
        end
      end
    end
  end
end
