module Datadog
  module AppSec
    module Utils
      module HTTP
        class MediaType
          WILDCARD: ::String

          TOKEN_RE: ::Regexp

          PARAMETER_RE: ::Regexp

          MEDIA_TYPE_RE: ::Regexp

          attr_reader type: ::String

          attr_reader subtype: ::String

          attr_reader parameters: ::Hash[::String, ::String]

          def self.parse: (::String?) -> MediaType?

          def initialize: (type: ::String, subtype: ::String, ?parameters: ::Hash[::String, ::String]) -> void

          def to_s: () -> ::String
        end
      end
    end
  end
end
