module Datadog
  module AppSec
    module Utils
      module HTTP
        module URLEncoded
          DEFAULT_BYTESIZE_LIMIT: ::Integer

          AMPERSAND_BYTE: ::Integer

          EQUALS_BYTE: ::Integer

          def self.parse: (::String?, ?limit: ::Integer) -> ::Hash[::String, (::String | ::Array[::String?])?]

          def self.set_param_value: (::Hash[::String, (::String | ::Array[::String?])?], ::String, segment_start: ::Integer, segment_end: ::Integer, equals_index: ::Integer) -> void
        end
      end
    end
  end
end
