module Datadog
  module Tracing
    module Contrib
      module DataStreams
        module Configuration
          class Settings
            @processor: untyped

            def initialize: () -> void

            attr_reader processor: untyped
          end
        end
      end
    end
  end
end
