require 'datadog/demo_env'

source "https://rubygems.org"

gem 'puma'
gem 'unicorn'
gem 'sinatra', '>= 2.2.4', '< 3'
gem 'sinatra-router', '>= 0.3.0'

gem 'dogstatsd-ruby'
# Choose correct specs for 'datadog' demo environment
gem 'datadog', *Datadog::DemoEnv.gem_spec('datadog')

# Development
if RUBY_VERSION >= '3.1'
  gem "debug", platforms: %i,mri mingw x64_mingw,
else
  gem "byebug", platforms: %w,mri,
end
gem 'pry-byebug'
gem 'rspec'
gem 'rspec-wait'
gem 'webrick'
gem 'rackup'
