name: 'Restore bundle cache'

# TODO: Improve description
description: 'Restores bundle cache for GitHub Actions'

inputs:
  lockfile:
    description: 'Name of the lockfile artifact to download'
    required: true
  cache-key:
    description: 'Cache key for bundle'
    required: true

runs:
  using: composite
  steps:
  - name: Download lockfile
    uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
    with:
      name: ${{ inputs.lockfile }}

  - name: Restore cache
    uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
    id: restore-cache
    with:
      key: "${{ inputs.cache-key }}"
      path: "/usr/local/bundle"

  - run: bundle check
    shell: bash
