name: 'Restore bundle cache'

description: 'Restores bundle cache for GitHub Actions'

inputs:
  namespace:
    description: 'Separate different cache gemsets'
    required: false
    default: 'full'

outputs:
  cache-hit:
    description: 'Was the cache present?'
    value: ${{ steps.restore-cache.outputs.cache-hit }}
  cache-primary-key:
    description: 'Cache key for the exact bundle'
    value: ${{ steps.cache-key.outputs.cache-primary-key }}

runs:
  using: composite
  steps:
    - name: Generate cache key
      id: cache-key
      uses: ./.github/actions/bundle-cache-key
      with:
        namespace: ${{ inputs.namespace }}
    - name: Restore cache
      uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      id: restore-cache
      with:
        path: "/usr/local/bundle"
        key: ${{ steps.cache-key.outputs.cache-primary-key }}
        restore-keys: |
          ${{ steps.cache-key.outputs.cache-secondary-key }}
