name: 'Restore bundle cache'

description: 'Restores bundle cache for GitHub Actions'

outputs:
  cache-hit:
    description: 'Was the cache present?'
    value: ${{ steps.restore-cache.outputs.cache-hit }}
  cache-primary-key:
    description: 'Cache key for the exact bundle'
    value: ${{ steps.cache-key.outputs.cache-primary-key }}
  cache-secondary-key:
    description: 'Cache key for this version of Ruby+Bundler'
    value: ${{ steps.cache-key.outputs.cache-primary-key }}

runs:
  using: composite
  steps:
    - name: Generate cache key
      id: cache-key
      uses: ./.github/actions/bundle-cache-key
    - name: Restore cache
      uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
      id: restore-cache
      with:
        key: ${{ steps.cache-key.outputs.cache-primary-key }}
        path: "/usr/local/bundle"
