name: 'Restore bundle cache'

# TODO: Improve description
description: 'Restores bundle cache for GitHub Actions'

inputs:
  lockfile:
    description: 'Name of the lockfile artifact to download'
    required: true
  cache-key:
    description: 'Cache key for bundle'
    required: true

runs:
  using: composite
  steps:
  - name: Download lockfile
    uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
    with:
      name: ${{ inputs.lockfile }}

  - name: Restore cache
    uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
    id: restore-cache
    with:
      key: "${{ inputs.cache-key }}"
      path: "/usr/local/bundle"

  - run: bundle check
    shell: bash
