name: 'Restore bundle cache'

# TODO: Improve description
description: 'Restores bundle cache for GitHub Actions'

inputs:
  lockfile:
    description: 'Name of the lockfile artifact to download'
    required: true
  cache-key:
    description: 'Cache key for bundle'
    required: true

runs:
  using: composite
  steps:
  - name: Download lockfile
    uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
    with:
      name: ${{ inputs.lockfile }}

  - name: Restore cache
    uses: actions/cache/restore@8b402f58fbc84540c8b491a91e594a4576fec3d7 # v5.0.2
    id: restore-cache
    with:
      key: "${{ inputs.cache-key }}"
      path: "/usr/local/bundle"

  - run: bundle check
    shell: bash
