module Datadog
  module Tracing
    module Contrib
      module Redis
        module Patcher
          include Contrib::Patcher
          module InstancePatch
            def self.included: (untyped base) -> untyped
            module InstanceMethods
              def datadog_pin=: (untyped pin) -> untyped
            end
          end
          module ClientPatch
            def self.included: (untyped base) -> untyped
            module InstanceMethods
              private

              attr_reader redis_instance: untyped
            end
          end

          def self?.default_tags: () -> untyped

          def self?.patch: () -> untyped
        end
      end
    end
  end
end
