module Datadog
  module Tracing
    module Contrib
      module Redis
        module Quantize
          type command = ::String | ::Symbol | ::Array[command]

          PLACEHOLDER: "?"

          TOO_LONG_MARK: "..."

          VALUE_MAX_LEN: 50

          CMD_MAX_LEN: 500

          AUTH_COMMANDS: ::Array[::String]

          MIGRATE_COMMANDS: ::Array[::String]

          HELLO_COMMANDS: ::Array[::String]

          KEYS_COMMANDS: ::Array[::String]

          MULTI_VERB_COMMANDS: untyped

          def self?.format_arg: (untyped arg) -> untyped

          def self?.format_command_args: (untyped command_args) -> ("AUTH ?" | untyped)

          def self?.get_verb: (untyped command_args) -> (nil | untyped | ::String)

          def self?.obfuscate_auth_args!: (command command_args) -> void

          def self?.resolve_command_args: (untyped command_args) -> untyped
        end
      end
    end
  end
end
