module Datadog
  module AppSec
    module Contrib
      module Faraday
        module ConnectionPatch : ::Faraday::Connection
          def initialize: (*untyped) ?{ (::Faraday::Connection) -> void } -> void
        end
      end
    end
  end
end
