module Datadog
  module AppSec
    module Contrib
      module Faraday
        class Integration
          include Datadog::AppSec::Contrib::Integration
          extend Datadog::AppSec::Contrib::Integration::ClassMethods

          MINIMUM_VERSION: ::Gem::Version

          def self.version: () -> ::Gem::Version?

          def self.loaded?: () -> bool

          def self.compatible?: () -> bool

          def self.auto_instrument?: () -> bool

          def patcher: () -> singleton(Patcher)
        end
      end
    end
  end
end
