module Datadog
  module AppSec
    module Contrib
      module Faraday
        module RackBuilderPatch : ::Faraday::RackBuilder
          def adapter: (*untyped) -> ::Faraday::RackBuilder::Handler?
        end
      end
    end
  end
end
