module Datadog
  module AppSec
    module Contrib
      module Faraday
        class SSRFDetectionMiddleware < ::Faraday::Middleware
          SAMPLE_BODY_KEY: ::Symbol

          def call: (::Faraday::Env env) -> untyped

          private

          def on_complete: (::Faraday::Env env, context: Context) -> void

          def mark_body_sampling!: (::Faraday::Env env, context: Context) -> void

          def parse_body: (Utils::HTTP::Body::body body, content_type: ::String?) -> untyped

          def normalize_headers: (::Faraday::Utils::Headers? headers) -> ::Hash[::String, ::String]

          def handle: (SecurityEngine::result result, context: Context) -> void
        end
      end
    end
  end
end
