module Datadog
  module Tracing
    module Sampling
      module Span
        module Ext
          DEFAULT_SAMPLE_RATE: ::Float
          DEFAULT_MAX_PER_SECOND: -1
          TAG_MECHANISM: "_dd.span_sampling.mechanism"
          TAG_RULE_RATE: "_dd.span_sampling.rule_rate"
          TAG_MAX_PER_SECOND: "_dd.span_sampling.max_per_second"
        end
      end
    end
  end
end
