module Datadog
  module SymbolDatabase
    module Transport
      module HTTP
        SYMBOLS_ENDPOINT: API::Endpoint

        def self.symbols: (
          agent_settings: ::Datadog::Core::Configuration::AgentSettings,
          logger: untyped,
          ?headers: Hash[String, String]?
        ) ?{ (untyped) -> void } -> SymbolDatabase::Transport::Symbols::Transport
      end
    end
  end
end
