module Datadog
  module AppSec
    module Monitor
      module Reactive
        module SetUser
          ADDRESSES: ::Array[::String]

          def self.publish: (AppSec::Reactive::Engine engine, AppSec::Instrumentation::Gateway::User user) -> untyped

          def self.subscribe: (AppSec::Reactive::Engine engine, untyped waf_context) { (untyped) -> untyped } -> untyped
        end
      end
    end
  end
end
