module Datadog
  module AppSec
    module Metrics
      module Telemetry
        ACTION_BLOCK: ::String
        ACTION_REDIRECT: ::String
        BLOCK_SUCCESS: ::String
        BLOCK_IRRELEVANT: ::String

        def self?.report_rasp: (Ext::rasp_rule_type type, SecurityEngine::result result, ?phase: ::String?) -> void
      end
    end
  end
end
