module Datadog
  module AppSec
    module Metrics
      module TelemetryExporter
        def self?.export_waf_request_metrics: (Metrics::Collector::Store metrics, AppSec::Context context) -> void

        def self?.export_api_security_metrics: (schema_extracted: bool, web_framework: String?) -> void
      end
    end
  end
end
