module Datadog
  module AppSec
    module Contrib
      module Devise
        module Patches
          module SignupTrackingPatch
            def create: () -> untyped

            private

            def record_successful_signup: (AppSec::Context context, untyped resource) -> void

            def resource_params: () -> untyped
          end
        end
      end
    end
  end
end
