module Datadog
  module AppSec
    module Contrib
      module Devise
        module Patches
          module SigninTrackingPatch
            @_datadog_appsec_skip_track_login_event: bool?

            attr_accessor authentication_hash: ::Hash[::Symbol, any]

            def validate: (any resource) ?{ () -> any } -> bool

            private

            def record_successful_signin: (::Datadog::AppSec::Context context, untyped resource) -> void

            def record_failed_signin: (::Datadog::AppSec::Context context, untyped resource) -> void
          end
        end
      end
    end
  end
end
