module Datadog
  module AppSec
    module Contrib
      module Devise
        module Patches
          module SkipSigninTrackingPatch
            @_datadog_appsec_skip_track_login_event: bool

            def validate: (*untyped args) -> untyped
          end
        end
      end
    end
  end
end
