# Select base image
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Add gem
COPY . /vendor/dd-trace-rb

# Install dependencies
# Setup specific version of ddtrace, if specified.
ENV DD_DEMO_ENV_GEM_LOCAL_DDTRACE /vendor/dd-trace-rb
RUN bundle install
