require 'datadog/demo_env'

source "https://rubygems.org"

gem 'ffi'
gem 'google-protobuf'

gem 'opentelemetry-sdk'

# Choose correct specs for 'datadog' demo environment
gem 'datadog', *Datadog::DemoEnv.gem_spec('datadog')

if RUBY_VERSION >= '3.1'
  gem "debug", platforms: %i,mri mingw x64_mingw,
else
  gem "byebug", platforms: %w,mri,
end
gem 'rspec'
