require 'datadog/demo_env'

source "https://rubygems.org"

gem 'ffi'
gem 'google-protobuf'

gem 'opentelemetry-sdk'

# Choose correct specs for 'ddtrace' demo environment
gem 'ddtrace', *Datadog::DemoEnv.gem_spec('ddtrace')

gem 'byebug'
gem 'rspec'
