module Datadog
  module Tracing
    module Contrib
      module Utils
        module Quantization
          module HTTP
            PLACEHOLDER: "?"
            PRESERVED_PATH_SEGMENT: ::Regexp
            API_VERSION_PATH_SEGMENT: ::Regexp
            RFC3986_URL_BASE: ::Regexp

            def self?.url: (untyped url, ?::Hash[untyped, untyped] options) -> untyped

            def self?.path: (untyped path, ?::Hash[untyped, untyped] options) -> ::String

            def self?.base_url: (untyped url, ?::Hash[untyped, untyped] options) -> (untyped | "")

            def self?.url!: (untyped url, ?::Hash[untyped, untyped] options) -> untyped

            def self?.query: (untyped query, ?::Hash[untyped, untyped] options) -> untyped

            def self?.query!: (untyped query, ?::Hash[untyped, untyped] options) -> ("" | untyped)
            def self?.collect_query: (untyped query, ?::Hash[untyped, untyped] options) { (untyped, untyped, untyped) -> untyped } -> untyped
            def self?.obfuscate_query: (untyped query, ?::Hash[untyped, untyped] options) -> untyped

            OBFUSCATOR_WITH: "<redacted>"
            OBFUSCATOR_REGEX: ::Regexp
          end
        end
      end
    end
  end
end
