module Datadog
  module CI
    module Contrib
      module Minitest
        module Ext
          APP: "minitest"

          ENV_ENABLED: "DD_TRACE_MINITEST_ENABLED"

          ENV_OPERATION_NAME: "DD_TRACE_MINITEST_OPERATION_NAME"

          FRAMEWORK: "minitest"

          OPERATION_NAME: "minitest.test"

          SERVICE_NAME: "minitest"

          TEST_TYPE: "test"
        end
      end
    end
  end
end
