module Datadog
  module Utils
    # Acts as a unique dictionary of objects
    class ObjectSet
      # You can provide a block that defines how the key
      # for this message type is resolved.
      def initialize: (?::Integer seed) { () -> untyped } -> untyped

      # Submit an array of arguments that define the message.
      # If they match an existing message, it will return the
      # matching object. If it doesn't match, it will yield to
      # the block with the next ID & args given.
      def fetch: (*untyped args) { (untyped, untyped) -> untyped } -> untyped

      def length: () -> untyped

      def objects: () -> untyped

      def freeze: () -> untyped
    end
  end
end
