module Datadog
  module AppSec
    module Instrumentation
      class Gateway
        type middleware_result = untyped
        type final_call_result = untyped
        type final_call = ^() -> final_call_result
        type stack = ::Proc
        type argument = Gateway::Argument | ::String | ::Array[Gateway::Argument]

        type stack_result = ::Array[nil | middleware_result | final_call_result]

        @middlewares: ::Hash[::String, ::Array[Middleware]]
        @pushed_events: ::Hash[::String, bool]

        def initialize: () -> void

        def push: (::String name, argument env) ?{ () -> final_call_result } -> stack_result

        def watch: ("sinatra.request.dispatch", ::Symbol key) { (stack, ::Datadog::AppSec::Contrib::Sinatra::Gateway::Request) -> stack_result } -> void
                 | ("sinatra.request.routed", ::Symbol key) { (stack, [::Datadog::AppSec::Contrib::Sinatra::Gateway::Request, ::Datadog::AppSec::Contrib::Sinatra::Gateway::RouteParams]) -> stack_result } -> void
                 | ("sinatra.response.body.json", ::Symbol key) { (stack, Gateway::DataContainer) -> stack_result } -> void
                 | (::String name, ::Symbol key) { (stack, argument) -> stack_result } -> void

        def pushed?: (::String name) -> bool
      end

      self.@gateway: Gateway

      def self.gateway: () -> Gateway
    end
  end
end
