module Datadog
  module AIGuard
    module Contrib
      module Rails
        module Patcher
          BEFORE_INITIALIZE_ONLY_ONCE_PER_APP: untyped

          def self?.patched?: () -> bool

          def self?.target_version: () -> untyped

          def self?.patch: () -> void

          def self?.patch_before_initialize: () -> untyped

          def self?.before_initialize: (untyped app) -> untyped

          def self?.add_middleware: (untyped app) -> untyped

          def self?.include_middleware?: (untyped middleware, untyped app) -> bool
        end
      end
    end
  end
end
