module Datadog
  module CI
    module Ext
      module Environment
        TAG_JOB_NAME: "ci.job.name"

        TAG_JOB_URL: "ci.job.url"

        TAG_PIPELINE_ID: "ci.pipeline.id"

        TAG_PIPELINE_NAME: "ci.pipeline.name"

        TAG_PIPELINE_NUMBER: "ci.pipeline.number"

        TAG_PIPELINE_URL: "ci.pipeline.url"

        TAG_PROVIDER_NAME: "ci.provider.name"

        TAG_STAGE_NAME: "ci.stage.name"

        TAG_WORKSPACE_PATH: "ci.workspace_path"

        TAG_CI_ENV_VARS: "_dd.ci.env_vars"

        PROVIDERS: ::Array[::Array["APPVEYOR" | :extract_appveyor] | ::Array["TF_BUILD" | :extract_azure_pipelines] | ::Array["BITBUCKET_COMMIT" | :extract_bitbucket] | ::Array["BUDDY" | :extract_buddy] | ::Array["BUILDKITE" | :extract_buildkite] | ::Array["CIRCLECI" | :extract_circle_ci] | ::Array["GITHUB_SHA" | :extract_github_actions] | ::Array["GITLAB_CI" | :extract_gitlab] | ::Array["JENKINS_URL" | :extract_jenkins] | ::Array["TEAMCITY_VERSION" | :extract_teamcity] | ::Array["TRAVIS" | :extract_travis] | ::Array["BITRISE_BUILD_SLUG" | :extract_bitrise]]

        def self?.tags: (untyped env) -> untyped

        def self?.normalize_ref: (untyped name) -> untyped

        def self?.filter_sensitive_info: (untyped url) -> (untyped | nil)

        def self?.extract_appveyor: (untyped env) -> ::Hash[untyped, "appveyor" | untyped]

        def self?.extract_azure_pipelines: (untyped env) -> ::Hash[untyped, "azurepipelines" | untyped]

        def self?.extract_bitbucket: (untyped env) -> ::Hash[untyped, untyped | "bitbucket"]

        def self?.extract_buddy: (untyped env) -> ::Hash[untyped, "buddy" | ::String | untyped]

        def self?.extract_buildkite: (untyped env) -> ::Hash[untyped, untyped | ::String | "buildkite"]

        def self?.extract_circle_ci: (untyped env) -> ::Hash[untyped, untyped | ::String | "circleci"]

        def self?.extract_github_actions: (untyped env) -> ::Hash[untyped, untyped | ::String | "github"]

        def self?.extract_gitlab: (untyped env) -> ::Hash[untyped, untyped | "gitlab"]

        def self?.extract_jenkins: (untyped env) -> ::Hash[untyped, untyped | "jenkins"]

        def self?.extract_teamcity: (untyped env) -> ::Hash[untyped, "teamcity" | untyped]

        def self?.extract_travis: (untyped env) -> ::Hash[untyped, untyped | ::String | "travisci"]

        def self?.extract_bitrise: (untyped env) -> ::Hash[untyped, "bitrise" | untyped]

        def self?.extract_user_defined_git: (untyped env) -> untyped

        def self?.git_commit_users: () -> untyped

        def self?.git_repository_url: () -> untyped

        def self?.git_commit_message: () -> untyped

        def self?.git_branch: () -> untyped

        def self?.git_commit_sha: () -> untyped

        def self?.git_tag: () -> untyped

        def self?.git_base_directory: () -> untyped

        def self?.exec_git_command: (untyped cmd) -> (nil | untyped)

        def self?.extract_local_git: () -> untyped

        def self?.branch_or_tag: (untyped branch_or_tag) -> ::Array[untyped]

        def self?.extract_name_email: (untyped name_and_email) -> (::Array[untyped] | ::Array[nil | untyped])
      end
    end
  end
end
