module Datadog
  module Core
    class BorrowingTokenBucket
      include RefillableBucket

      def initialize: (::Float | ::Integer rate, ?max_tokens: ::Numeric) -> void

      def available?: () -> bool

      def consume: (?size: ::Numeric) -> void
    end
  end
end
