module Datadog
  module Core
    module Configuration
      def configuration: () -> Settings

      def tracer: () -> Datadog::Tracing::Tracer

      def logger: () -> Datadog::Core::Logger
    end
  end
end
