module Datadog
  module Core
    module Configuration
      def tracer: () -> Datadog::Tracing::Tracer

      def logger: () -> Datadog::Core::Logger

      def configuration: () -> Datadog::Core::Configuration::Settings
    end
  end
end
