module Datadog
  module Core
    # Encoding module that encodes data for the AgentTransport
    module Encoding
      # Encoder interface that provides the logic to encode traces and service
      # @abstract
      module Encoder
        def content_type: () -> String

        def encode: (untyped obj) -> String

        def join: (Array[untyped] encoded_data) -> String

        def decode: (String obj)-> untyped
      end

      # Encoder for the JSON format
      module JSONEncoder
        extend Encoder

        CONTENT_TYPE: String

        def self?.content_type: () -> String

        def self?.encode: (untyped obj) -> String

        def self?.join: (Array[untyped] encoded_data) -> String

        def self?.decode: (String obj)-> untyped
      end

      # Encoder for the Msgpack format
      module MsgpackEncoder
        extend Encoder

        CONTENT_TYPE: String

        def self?.content_type: () -> String

        def self?.encode: (untyped obj) -> String

        def self?.join: (Array[untyped] encoded_data) -> String

        def self?.decode: (String obj)-> untyped
      end
    end
  end
end
