module Datadog
  module Core
    class Error
      attr_reader type: String

      attr_reader message: String

      attr_reader backtrace: String

      interface _ContainsMessage
        def message: () -> String
      end

      def self.build_from: ((Error | Array[untyped] | ::Exception | _ContainsMessage | ::String) value) -> Error

      private
      def self.full_backtrace: (Exception ex) -> String
      def self.backtrace_for: (Exception ex, String backtrace) -> void

      public

      def initialize: (?Object? `type`, ?Object? message, ?Object? backtrace) -> void

      BlankError: Error
      ContainsMessage: ^(Object) -> bool
    end
  end
end
