module Datadog
  module Core
    module FeatureFlags
      class Error < StandardError
      end

      class Configuration
        def self.new: (String json_str) -> Configuration

        def get_assignment: (String flag_key, Symbol expected_type, Hash[String, untyped] context) -> ResolutionDetails
      end

      class ResolutionDetails
        def value: () -> untyped

        def variant: () -> String?

        def allocation_key: () -> String?

        def reason: () -> String

        def error?: () -> bool

        def error_code: () -> String?

        def error_message: () -> String?

        def log?: () -> bool

        def flag_metadata: () -> Hash[String, String]
      end
    end
  end
end
