module Datadog
  module Core
    class KnuthSampler
      UINT64_MAX: ::Integer

      UINT64_MODULO: ::Integer

      DEFAULT_KNUTH_FACTOR: ::Integer

      @knuth_factor: ::Integer

      @rate: ::Float

      @threshold: ::Float

      attr_reader rate: ::Float

      def initialize: (?::Float | ::Integer rate, ?knuth_factor: ::Integer) -> void

      def rate=: (::Float | ::Integer rate) -> void

      def sample?: (::Integer input) -> bool
    end
  end
end
