module Datadog
  module Core
    class ProcessDiscovery
      def self._native_store_tracer_metadata: (
        schema_version: Integer,
        runtime_id: String,
        tracer_language: String,
        tracer_version: String,
        hostname: String,
        service_name: String,
        service_env: String,
        service_version: String
      ) -> Integer # C file descriptor
    end

    def self._native_close_tracer_memfd: (Integer fd) -> nil

    def self.get_metadata: (Datadog::Core::Configuration::Settings settings) -> Hash[Symbol, String | Integer]
  end
end
