module Datadog
  module Core
    module RefillableBucket
      @rate: ::Float | ::Integer

      @max_tokens: ::Numeric

      @tokens: ::Numeric

      @last_refill: ::Numeric

      attr_reader rate: ::Float | ::Integer

      attr_reader max_tokens: ::Numeric

      attr_reader tokens: ::Numeric

      attr_reader last_refill: ::Numeric

      def initialize: (::Float | ::Integer rate, ::Numeric max_tokens) -> void

      def available_tokens: () -> ::Numeric

      private

      def refill: () -> void

      def refill_tokens: (::Numeric size) -> void
    end
  end
end
