module Datadog
  module Core
    module TagBuilder
      type tags = ::Hash[::String, ::String]

      self.@fixed_environment_tags: tags

      def self.fixed_environment_tags: () -> tags

      def self.tags: (Datadog::Core::Configuration::Settings settings) -> tags

      def self.serialize_tags: (tags tags) -> ::String
    end
  end
end
