module Datadog
  module Core
    module Utils
      extend Forking

      EMPTY_STRING: untyped
      def self.truncate: (untyped value, untyped size, ?untyped omission) -> untyped
      def self.utf8_encode: (untyped str, ?binary: bool, ?placeholder: untyped) -> untyped
      def self.without_warnings: () { () -> untyped } -> untyped
      def self.extract_host_port: (untyped host_port) -> (nil | ::Array[untyped])
    end
  end
end
