name: Feature Request (Low Priority)
description: Create a public Feature Request. Note that these may not be addressed as quickly as the helpdesk and that looking up account information will be difficult.
title: "[FEATURE]: "
labels: community, feature-request
body:
  - type: input
    attributes:
      label: Gem Name
      description: "If your feature request is to add instrumentation support for a Ruby gem please provide the gem name here"
      placeholder: mysql
    validations:
      required: false

  - type: input
    attributes:
      label: Gem Version(s)
      description: "Please provide the version of the above gem here"
      placeholder: 2.9.1
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe the goal of the feature
      description: A clear and concise goal of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: |
        Please add a clear and concise description of your problem.
        E.g. I'm unable to instrument my database queries...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here
    validations:
      required: false

  - type: textarea
    attributes:
      label: How does Datadog help you?
      description: "Optionally, tell us why and how you're using datadog, and what your overall experience with it is!"
    validations:
      required: false
