module Datadog
  module AppSec
    module Contrib
      module GraphQL
        module Gateway
          class Execute < Instrumentation::Gateway::Argument
            @variables: untyped

            attr_reader variables: untyped

            def initialize: (untyped query) -> void
          end
        end
      end
    end
  end
end
