module Datadog
  module AppSec
    module Contrib
      module GraphQL
        module Gateway
          module Watcher
            def self.watch: () -> untyped

            def self.watch_multiplex: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> Hash[String, Datadog::AppSec::Instrumentation::Gateway::Middleware]?
          end
        end
      end
    end
  end
end
