module Datadog
  module AppSec
    module Contrib
      module GraphQL
        module Gateway
          module Watcher
            def self.watch: () -> void

            def self.watch_multiplex: (?AppSec::Instrumentation::Gateway gateway) -> void
          end
        end
      end
    end
  end
end
