module Datadog
  module OpenFeature
    module Exposures
      class Batch
        attr_reader context: ::Hash[::Symbol, untyped]
        attr_reader exposures: ::Array[untyped]

        def initialize: (context: ::Hash[::Symbol, untyped], exposures: ::Array[untyped]?) -> void

        def add: (untyped) -> void

        def empty?: () -> bool

        def to_h: () -> ::Hash[::Symbol, untyped]

        private

        def sanitize_context: (::Hash[::Symbol, untyped]?) -> ::Hash[::Symbol, untyped]

        def serialized_exposures: () -> ::Array[untyped]
      end
    end
  end
end
