module Datadog
  module OpenFeature
    module Exposures
      class BatchBuilder
        @context: ::Hash[::Symbol, ::String]

        def initialize: (Core::Configuration::Settings settings) -> void

        def payload_for: (::Array[Event] events) -> ::Hash[::Symbol, untyped]

        private

        def build_context: (Core::Configuration::Settings settings) -> ::Hash[::Symbol, ::String]

        def extract_env: (Core::Configuration::Settings settings) -> ::String?

        def extract_service: (Core::Configuration::Settings settings) -> ::String?

        def extract_version: (Core::Configuration::Settings settings) -> ::String?
      end
    end
  end
end

