module Datadog
  module OpenFeature
    module Exposures
      BufferBaseClass: Core::Buffer::ThreadSafe | Core::Buffer::CRuby

      # NOTE: We need to have interface instead of the actual class
      class Buffer < Core::Buffer::Random
        DEFAULT_LIMIT: ::Integer

        def initialize: (?::Integer) -> void

        def drain!: () -> [::Array[Object], ::Integer]
      end
    end
  end
end
