module Datadog
  module OpenFeature
    module Exposures
      class Buffer < Core::Buffer::CRuby
        DEFAULT_LIMIT: ::Integer

        def initialize: (?::Integer) -> void

        def drain!: () -> [::Array[Object], ::Integer]

        def replace!: (Object) -> Object?
      end
    end
  end
end
