module Datadog
  module OpenFeature
    module Exposures
      module Context
        def build: (
          ?service: ::String?,
          ?env: ::String?,
          ?version: ::String?,
          ?geo: ::Hash[::Symbol, ::String?]?
        ) -> ::Hash[::Symbol, untyped]

        def self.build: (
          ?service: ::String?,
          ?env: ::String?,
          ?version: ::String?,
          ?geo: ::Hash[::Symbol, ::String?]?
        ) -> ::Hash[::Symbol, untyped]

        private def present?: (untyped) -> bool

        private def self.present?: (untyped) -> bool
      end
    end
  end
end
