module Datadog
  module OpenFeature
    module Exposures
      class Deduplicator
        DEFAULT_CACHE_LIMIT: ::Integer

        @cache: ::Datadog::Core::Utils::LRUCache
        @mutex: ::Mutex

        def initialize: (?limit: ::Integer) -> void

        def duplicate?: (::String, ::String) -> bool
      end
    end
  end
end


