module Datadog
  module OpenFeature
    module Exposures
      class Deduplicator
        DEFAULT_CACHE_LIMIT: ::Integer

        def initialize: (?limit: ::Integer) -> void

        def duplicate?: (Models::Event event) -> bool

        private

        def digest: (::String?, ::String?) -> ::Integer
      end
    end
  end
end


