module Datadog
  module OpenFeature
    module Exposures
      class Event
        ALLOWED_FIELD_TYPES: ::Array[::Class]

        TARGETING_KEY_FIELD: ::String

        @payload: ::Hash[::Symbol, untyped]

        def self.build: (
          ResolutionDetails result,
          flag_key: ::String,
          context: ::OpenFeature::SDK::EvaluationContext
        ) -> Event

        def initialize: (::Hash[::Symbol, untyped]) -> void

        def allocation_key: () -> ::String?

        def flag_key: () -> ::String?

        def variation_key: () -> ::String?

        def targeting_key: () -> ::String?

        def to_h: () -> ::Hash[::Symbol, untyped]

        def self.current_timestamp_ms: () -> ::Integer

        def self.extract_attributes: (::OpenFeature::SDK::EvaluationContext) -> ::Hash[::String, untyped]
      end
    end
  end
end
