module Datadog
  module OpenFeature
    module Exposures
      class Event
        attr_reader allocation_key: ::String
        attr_reader flag_key: ::String
        attr_reader subject_attributes: ::Hash[untyped, untyped]
        attr_reader subject_id: ::String
        attr_reader subject_type: ::String?
        attr_reader timestamp: ::Integer
        attr_reader variant_key: ::String

        def initialize: (
          timestamp: ::Integer | ::Time,
          allocation_key: ::String,
          flag_key: ::String,
          variant_key: ::String,
          subject_id: ::String,
          subject_type: ::String?,
          subject_attributes: ::Hash[untyped, untyped]?
        ) -> void

        def to_h: () -> ::Hash[::Symbol, untyped]

        private

        def normalize_timestamp: (::Integer | ::Time) -> ::Integer

        def sanitize_attributes: (::Hash[untyped, untyped]?) -> ::Hash[untyped, untyped]

        def subject_hash: () -> ::Hash[::Symbol, untyped]

        def validate_required_fields: () -> void
      end
    end
  end
end
