module Datadog
  module OpenFeature
    module Exposures
      class Worker
        include Core::Workers::Queue
        include Core::Workers::Polling
        # NOTE: Steep is not picking it up on itself with included metaprogramming
        include Core::Workers::Async::Thread
        include Core::Workers::IntervalLoop

        GRACEFUL_SHUTDOWN_EXTRA_SECONDS: ::Integer

        GRACEFUL_SHUTDOWN_WAIT_INTERVAL_SECONDS: ::Float

        DEFAULT_FLUSH_INTERVAL_SECONDS: ::Integer

        DEFAULT_BUFFER_LIMIT: ::Integer

        @logger: Core::Logger
        @transport: Transport::HTTP
        @telemetry: Core::Telemetry::Component
        @batch_builder: BatchBuilder

        def initialize: (
          settings: Core::Configuration::Settings,
          transport: Transport::HTTP,
          telemetry: Core::Telemetry::Component,
          logger: Core::Logger,
          ?flush_interval_seconds: ::Integer,
          ?buffer_limit: ::Integer
        ) -> void

        def start: () -> void

        def stop: (?bool, ?::Integer) -> bool

        def enqueue: (Event::t event) -> bool

        def dequeue: () -> [::Array[Event::t], ::Integer]

        def graceful_shutdown: () -> bool

        private

        def loop_base_interval=: (::Integer) -> ::Integer

        def running?: () -> bool

        def forked?: () -> bool

        def perform: (*untyped) -> void

        def send_events: (::Array[Event::t], ::Integer) -> Core::Transport::Response?
      end
    end
  end
end
