module Datadog
  module Core
    module Configuration
      class AgentSettings
        # IPv6 regular expression from
        # https://stackoverflow.com/questions/53497/regular-expression-that-matches-valid-ipv6-addresses
        # Does not match IPv4 addresses.
        IPV6_REGEXP: ::Regexp

        def initialize: (?adapter: untyped, ?ssl: untyped, ?hostname: untyped, ?port: untyped, ?uds_path: untyped, ?timeout_seconds: untyped) -> void

        attr_reader adapter: :net_http | :unix
        attr_reader ssl: untyped
        attr_reader hostname: untyped
        attr_reader port: untyped
        attr_reader uds_path: untyped
        attr_reader timeout_seconds: untyped

        def url: () -> ::String
      end
    end
  end
end
