module Datadog
  module Core
    module Configuration
      module ConfigHelper
        type env_hash = RBS::Unnamed::ENVClass | Hash[String, String]

        @log_deprecations_called_with: Hash[String, bool]

        def get_environment_variable: (String name, ?String? default_value, ?env_vars: env_hash) -> String?

        def log_deprecated_environment_variables: (?env_vars: env_hash, ?source: String) -> void

        private

        @dd_test_environment: bool?

        def dd_test_environment!: () -> void
      end
    end
  end
end
