module Datadog
  module Core
    module Configuration
      module ConfigHelper
        type env_hash = RBS::Unnamed::ENVClass | Hash[String, String]

        def get_environment_variable: (String name, ?String? default_value, ?env_vars: env_hash, ?source: String) -> String?

        private

        @log_deprecations_called_with: Hash[String, bool]
        @config_helper_logger: Core::Logger
        @dd_test_environment: bool?

        def log_deprecations: (env_hash, String) -> void
        def alias_to_canonical: () -> Hash[String, String]
      end
    end
  end
end
