module Datadog
  module Core
    module Configuration
      module Ext
        module Diagnostics
          ENV_DEBUG_ENABLED: "DD_TRACE_DEBUG"

          ENV_HEALTH_METRICS_ENABLED: "DD_HEALTH_METRICS_ENABLED"

          ENV_STARTUP_LOGS_ENABLED: "DD_TRACE_STARTUP_LOGS"
        end

        module Metrics
          ENV_DEFAULT_PORT: "DD_METRIC_AGENT_PORT"
        end
      end
    end
  end
end
