module Datadog
  module Core
    module Configuration
      class OptionDefinitionSet < Hash[untyped, untyped]
        def dependency_order: () -> untyped

        def dependency_graph: () -> untyped
      end
    end
  end
end
