module Datadog
  module Core
    module Configuration
      class OptionDefinition
        type parent_type = Options::_ClassMethods

        type settings_context = Options::_Settings
        type settings_execution_context = settings_context & ::Object
        type option_type = Object?
        type generic_proc = (^(?) [self: settings_execution_context] -> any)
        type default_value = any
        type env_parser_proc = (^(String env_value) [self: settings_execution_context] -> Option::env_value)
        type after_set_proc = (^(option_type value, option_type old_value, Option::Precedence::Value precedence) [self: settings_execution_context] -> void)
        type resetter_proc = (^(option_type value) [self: settings_execution_context] -> option_type)
        type setter_proc = (^(option_type new_value, option_type old_value) [self: settings_execution_context] -> option_type)

        type meta = {
          ?default: default_value?,
          ?default_proc: generic_proc?,
          ?env: String?,
          ?env_parser: env_parser_proc?,
          ?after_set: after_set_proc?,
          ?resetter: resetter_proc?,
          ?setter: setter_proc?,
          ?type: Symbol?,
          ?type_options: Hash[Symbol, untyped]
        }

        type meta_with_type_options = {
          ?default: default_value?,
          ?default_proc: generic_proc?,
          ?env: String?,
          ?env_parser: env_parser_proc?,
          ?after_set: after_set_proc?,
          ?resetter: resetter_proc?,
          ?setter: setter_proc?,
          ?type: Symbol?,
          type_options: Hash[Symbol, untyped]
        }

        IDENTITY: setter_proc

        attr_reader default: default_value?

        attr_reader default_proc: generic_proc?

        attr_reader env: String?

        attr_reader env_parser: env_parser_proc?

        attr_reader name: Symbol

        attr_reader after_set: after_set_proc?

        attr_reader resetter: resetter_proc?

        attr_reader setter: setter_proc

        attr_reader type: Symbol?

        attr_reader type_options: Hash[Symbol, untyped]

        @parent: parent_type?

        def initialize: (String | Symbol name, meta_with_type_options meta, ?parent_type? parent) ?{ (option_type new_value, option_type old_value) [self: settings_execution_context] -> option_type } -> void

        def build: (settings_context context) -> Option

        class Builder
          class InvalidOptionError < StandardError
          end

          attr_reader helpers: Hash[Symbol, generic_proc]

          @parent: parent_type?

          @env: String?
          @env_parser: env_parser_proc?
          @default: default_value?
          @default_proc: generic_proc?
          @helpers: Hash[Symbol, generic_proc]
          @name: Symbol
          @after_set: after_set_proc?
          @resetter: resetter_proc?
          @setter: setter_proc
          @type: Symbol?
          @type_options: Hash[Symbol, untyped]

          def initialize: (String | Symbol name, ?parent_type? parent, ?meta options) ?{ (Builder) -> void } -> void

          def env: (String? value) -> void

          def env_parser: () ?{ (String env_value) [self: settings_execution_context] -> Option::env_value } -> void

          # can also be a class that includes Configuration::Base for new settings
          def default: (?(default_value) value) ?{ (settings_execution_context settings) [self: settings_execution_context] -> option_type } -> void

          def default_proc: () ?{ (?) [self: settings_execution_context] -> untyped } -> void

          def type: (Symbol? value, ?nilable: bool) -> Symbol?

          def helper: (Symbol name, *untyped _args) { (?) [self: settings_execution_context] -> untyped } -> void

          def after_set: () ?{ (option_type value, option_type old_value, Option::Precedence::Value precedence) [self: settings_execution_context] -> void } -> void

          def resetter: () ?{ (option_type value) [self: settings_execution_context] -> option_type } -> void

          def setter: () { (option_type new_value, option_type old_value) [self: settings_execution_context] -> option_type } -> void

          def apply_options!: (?meta options) -> void

          def to_definition: () -> OptionDefinition

          def meta: () -> meta

          private

          def validate_options!: () -> void
        end

        private
      end
    end
  end
end
