module Datadog
  module Core
    module Configuration
      module Options
        extend _ClassMethods
        include _InstanceMethods

        def self.included: (Class | Module base) -> void

        interface _ClassMethods
          def options: () -> Hash[Symbol, OptionDefinition]

          def settings_path: () -> ::String?

          def option: (Symbol name, ?OptionDefinition::attributes attributes) ?{ (OptionDefinition::Builder) -> void } -> OptionDefinition
        end

        interface _InstanceMethods
          def options: () -> Hash[Symbol, Option]

          def set_option: (Symbol name, Object? value, ?precedence: Option::Precedence::Value) -> Object?

          def unset_option: (Symbol name, ?precedence: Option::Precedence::Value) -> void

          def get_option: (Symbol name) -> Object?

          def reset_option: (Symbol name) -> void

          def option_defined?: (Symbol name) -> bool

          def using_default?: (Symbol name) -> bool

          def options_hash: () -> Hash[Symbol, Object?]

          def reset_options!: () -> void
        end

        interface _SettingsClass
          include _ClassMethods
        end

        interface _Settings
          include _InstanceMethods

          def assert_valid_option!: (Symbol name) -> void

          def class: () -> _SettingsClass

          def instance_exec: [U] (*untyped args) { (?) [self: OptionDefinition::settings_execution_context] -> U } -> U

          def instance_eval: [U] () { (OptionDefinition::settings_execution_context settings) [self: OptionDefinition::settings_execution_context] -> U } -> U
        end

        module ClassMethods
          include _ClassMethods

          @options: Hash[Symbol, OptionDefinition]
          @settings_path: ::String?

          private

          def default_helpers: (Symbol | String name) -> Hash[Symbol, OptionDefinition::generic_proc]

          def define_helpers: (Hash[Symbol, OptionDefinition::generic_proc] helpers) -> void

          # Fake methods to make it work with RBS. RBS cannot understand that this module is only used in a class context.
          def superclass: () -> untyped
          def define_method: (Symbol name) { (?) [self: OptionDefinition::settings_execution_context] -> untyped } -> untyped
        end

        module InstanceMethods
          extend _ClassMethods
          include _InstanceMethods

          @options: Hash[Symbol, Option]

          private

          def resolve_option: (Symbol name) -> Option

          def assert_valid_option!: (Symbol name) -> void
        end

        class InvalidOptionError < StandardError
        end
      end
    end
  end
end
