module Datadog
  module Core
    module Configuration
      class Settings
        include Base

        def initialize: (*untyped _) -> untyped

        def logger=: (untyped logger) -> untyped

        def runtime_metrics: (?untyped? options) -> untyped

        def appsec: (?untyped? options) -> Datadog::AppSec::Configuration::Settings
      end
    end
  end
end
