module Datadog
  module Core
    module Configuration
      module StableConfig
        class Configurator
          def initialize: -> void
          def get: -> Array[Hash[Symbol, String | Symbol]]
        end

        @configuration: Array[Hash[Symbol, String | Symbol]]

        def self.extract_configuration: -> Array[Hash[Symbol, String | Symbol]]
        def self.configuration: -> Array[Hash[Symbol, String | Symbol]]
      end
    end
  end
end
