module Datadog
  module Core
    module Configuration
      module StableConfig
        LOG_ONLY_ONCE: Datadog::Core::Utils::OnlyOnce

        type stable_config = {
          ?logs: String?,
          ?local: {
            config: Hash[String, String],
            ?id: String
          },
          ?fleet: {
            config: Hash[String, String],
            ?id: String
          }
        }

        class Configurator
          def initialize: -> void
          def get: -> stable_config
        end

        @configuration: stable_config

        def self.extract_configuration: -> stable_config
        def self.configuration: -> stable_config
        def self.log_result: (Datadog::Core::Logger logger) -> void
      end
    end
  end
end
