module Datadog
  module Core
    module Configuration
      type env_var_name = String
      type config = Hash[Symbol, Array[String]]

      SUPPORTED_CONFIGURATIONS: Hash[env_var_name, config]
      ALIASES: Hash[env_var_name, Array[env_var_name]]
      DEPRECATIONS: Hash[env_var_name, String]
      ALIAS_TO_CANONICAL: Hash[env_var_name, env_var_name]
    end
  end
end
