module Datadog
  module Tracing
    module Contrib
      module Aws
        module Service
          class Base
            MESSAGE_ATTRIBUTES_LIMIT: int

            def add_tags: (untyped span, untyped params) -> nil
          end
        end
      end
    end
  end
end
