module Datadog
  module Tracing
    module Contrib
      module Aws
        module Service
          class DynamoDB < Base
            def add_tags: (untyped span, untyped params) -> untyped
          end
        end
      end
    end
  end
end
