module Datadog
  module Core
    module Telemetry
      module V1
        class AppEvent
          attr_reader additional_payload: untyped

          attr_reader configuration: untyped

          attr_reader dependencies: untyped

          attr_reader integrations: untyped
          def initialize: (?additional_payload: untyped?, ?configuration: untyped?, ?dependencies: untyped?, ?integrations: untyped?) -> void

          def to_h: () -> untyped

          private

          def map_hash: (untyped hash) -> untyped

          def map_array: (untyped arr) -> untyped
        end
      end
    end
  end
end
