module Datadog
  module Core
    module Telemetry
      module V1
        class Application
          ERROR_NIL_LANGUAGE_NAME_MESSAGE: ":language_name must not be nil"

          ERROR_NIL_LANGUAGE_VERSION_MESSAGE: ":language_version must not be nil"

          ERROR_NIL_SERVICE_NAME_MESSAGE: ":service_name must not be nil"

          ERROR_NIL_TRACER_VERSION_MESSAGE: ":tracer_version must not be nil"

          attr_reader env: untyped

          attr_reader language_name: untyped

          attr_reader language_version: untyped

          attr_reader products: untyped

          attr_reader runtime_name: untyped

          attr_reader runtime_patches: untyped

          attr_reader runtime_version: untyped

          attr_reader service_name: untyped

          attr_reader service_version: untyped

          attr_reader tracer_version: untyped
          def initialize: (language_name: untyped, language_version: untyped, service_name: untyped, tracer_version: untyped, ?env: untyped?, ?products: untyped?, ?runtime_name: untyped?, ?runtime_patches: untyped?, ?runtime_version: untyped?, ?service_version: untyped?) -> void

          def to_h: () -> untyped

          private
          def validate: (language_name: untyped, language_version: untyped, service_name: untyped, tracer_version: untyped) -> untyped
        end
      end
    end
  end
end
