module Datadog
  module Core
    module Telemetry
      module V1
        class Configuration
          ERROR_NIL_NAME_MESSAGE: ":name must not be nil"

          attr_reader name: untyped

          attr_reader value: untyped
          def initialize: (name: untyped, ?value: untyped?) -> void
        end
      end
    end
  end
end
