module Datadog
  module Core
    module Telemetry
      module V1
        class Dependency
          ERROR_NIL_NAME_MESSAGE: ":name must not be nil"

          attr_reader hash: untyped

          attr_reader name: untyped

          attr_reader version: untyped
          def initialize: (name: untyped, ?version: untyped?, ?hash: untyped?) -> void

          def to_h: () -> untyped
        end
      end
    end
  end
end
