module Datadog
  module Core
    module Telemetry
      module V1
        class Host
          attr_reader container_id: untyped

          attr_reader hostname: untyped

          attr_reader kernel_name: untyped

          attr_reader kernel_release: untyped

          attr_reader kernel_version: untyped

          attr_reader os_version: untyped

          attr_reader os: untyped
          def initialize: (?container_id: untyped?, ?hostname: untyped?, ?kernel_name: untyped?, ?kernel_release: untyped?, ?kernel_version: untyped?, ?os_version: untyped?, ?os: untyped?) -> void

          def to_h: () -> untyped
        end
      end
    end
  end
end
