module Datadog
  module Core
    module Telemetry
      module V1
        class InstallSignature
          @install_id: untyped

          @install_type: untyped

          @install_time: untyped

          attr_reader install_id: untyped

          attr_reader install_type: untyped

          attr_reader install_time: untyped
          def initialize: (install_id: untyped, install_type: untyped, install_time: untyped) -> void

          def to_h: () -> untyped
        end
      end
    end
  end
end
