module Datadog
  module Core
    module Telemetry
      module V1
        class Integration
          ERROR_NIL_ENABLED_MESSAGE: ":enabled must not be nil"

          ERROR_NIL_NAME_MESSAGE: ":name must not be nil"

          attr_reader auto_enabled: untyped

          attr_reader compatible: untyped

          attr_reader enabled: untyped

          attr_reader error: untyped

          attr_reader name: untyped

          attr_reader version: untyped
          def initialize: (enabled: untyped, name: untyped, ?auto_enabled: untyped?, ?compatible: untyped?, ?error: untyped?, ?version: untyped?) -> void

          def to_h: () -> untyped

          private
          def validate: (enabled: untyped, name: untyped) -> untyped
        end
      end
    end
  end
end
