module Datadog
  module Core
    module Telemetry
      module V1
        class Product
          attr_reader appsec: untyped

          attr_reader profiler: untyped
          def initialize: (?appsec: untyped?, ?profiler: untyped?) -> void

          def to_h: () -> untyped
        end
      end
    end
  end
end
