module Datadog
  module Core
    module Telemetry
      module V1
        class TelemetryRequest
          ERROR_NIL_API_VERSION_MESSAGE: ":api_version must not be nil"

          ERROR_NIL_APPLICATION_MESSAGE: ":application must not be nil"

          ERROR_NIL_HOST_MESSAGE: ":host must not be nil"

          ERROR_NIL_PAYLOAD_MESSAGE: ":payload must not be nil"

          ERROR_NIL_REQUEST_TYPE_MESSAGE: ":request_type must not be nil"

          ERROR_NIL_RUNTIME_ID_MESSAGE: ":runtime_id must not be nil"

          ERROR_NIL_SEQ_ID_MESSAGE: ":seq_id must not be nil"

          ERROR_NIL_TRACER_TIME_MESSAGE: ":tracer_time must not be nil"

          attr_reader api_version: untyped

          attr_reader application: untyped

          attr_reader debug: untyped

          attr_reader host: untyped

          attr_reader payload: untyped

          attr_reader request_type: untyped

          attr_reader runtime_id: untyped

          attr_reader seq_id: untyped

          attr_reader session_id: untyped

          attr_reader tracer_time: untyped
          def initialize: (api_version: untyped, application: untyped, host: untyped, payload: untyped, request_type: untyped, runtime_id: untyped, seq_id: untyped, tracer_time: untyped, ?debug: untyped?, ?session_id: untyped?) -> void

          def to_h: () -> untyped

          private
          def validate: (api_version: untyped, application: untyped, host: untyped, payload: untyped, request_type: untyped, runtime_id: untyped, seq_id: untyped, tracer_time: untyped) -> untyped
        end
      end
    end
  end
end
