require 'datadog/demo_env'

source "https://rubygems.org"

gem 'ffi'
gem 'google-protobuf'

# Choose correct specs for 'ddtrace' demo environment
gem 'ddtrace', *Datadog::DemoEnv.gem_spec('ddtrace')

gem 'byebug'

# Testing/CI
gem 'rspec'

gem 'datadog-instrumentation', git: 'https://github.com/DataDog/datadog-instrumentation-ruby', branch: 'master'
