module Datadog
  module AppSec
    class Processor
      module Actions
        self.@actions: Array[Hash[String, untyped]]

        def self.actions: () -> Array[Hash[String, untyped]]

        def self.fetch_configuration: (String action) -> Hash[String, untyped]?

        def self.merge: (Array[Hash[String, untyped]] actions_to_merge) -> Array[Hash[String, untyped]]?

        private
        def self.reset: () -> void
      end
    end
  end
end
