module Datadog
  module OpenTelemetry
    module Trace
      module Span
        # DEV: Pending OpenTelemetry::SDK typechecking

        def set_attribute: (::String key, ::String | bool | ::Numeric | ::Array[::String | ::Numeric | bool] value) -> untyped # ::OpenTelemetry::SDK::Trace::Span
        alias []= set_attribute
        def add_attributes: (::Hash[::String, ::String | bool | ::Numeric | ::Array[::String | ::Numeric | bool]] attributes) -> untyped # ::OpenTelemetry::SDK::Trace::Span
        # def status=: (::OpenTelemetry::Trace::Status s s) -> void
        def status=: (untyped s) -> void

        private

        def datadog_set_attribute: (String key) -> void
      end
    end
  end
end
