module Datadog
  module Tracing
    module Contrib
      module Kafka
        module Events
          module ConsumerGroup
            module Heartbeat
              include Kafka::Event

              extend Kafka::ConsumerEvent

              extend Kafka::ConsumerGroupEvent

              EVENT_NAME: "heartbeat.consumer.kafka"

              def self.process: (untyped span, untyped _event, untyped _id, untyped payload) -> untyped

              def self?.span_name: () -> untyped

              def self?.span_options: () -> untyped
            end
          end
        end
      end
    end
  end
end
