module Datadog
  module Tracing
    module Contrib
      module Kafka
        module Events
          module ConsumerGroup
            module LeaveGroup
              include Kafka::Event

              extend Kafka::ConsumerEvent

              extend Kafka::ConsumerGroupEvent

              EVENT_NAME: "leave_group.consumer.kafka"

              def self?.span_name: () -> untyped

              def self?.span_options: () -> untyped
            end
          end
        end
      end
    end
  end
end
