module Datadog
  module Tracing
    module Transport
      module HTTP
        class Client < Core::Transport::HTTP::Client
          include Datadog::Tracing::Transport::Statistics
          include Datadog::Tracing::Transport::HTTP::Statistics
        end
      end
    end
  end
end
