module Datadog
  module Tracing
    module Transport
      module HTTP
        module Traces
          class Response
            @service_rates: untyped

            @trace_count: untyped

            include Datadog::Core::Transport::HTTP::Response

            include Datadog::Tracing::Transport::Traces::Response

            def initialize: (untyped http_response, ?::Hash[untyped, untyped] options) -> void
          end
          class Client < Core::Transport::HTTP::Client
          end

          module API
            class Endpoint < Datadog::Core::Transport::HTTP::API::Endpoint
              @service_rates: untyped

              HEADER_CONTENT_TYPE: "Content-Type"

              HEADER_TRACE_COUNT: "X-Datadog-Trace-Count"

              SERVICE_RATE_KEY: "rate_by_service"

              def initialize: (untyped path, untyped encoder, ?::Hash[untyped, untyped] options) -> void

              def service_rates?: () -> untyped

              def call: (untyped env) { (?) -> untyped } -> untyped
            end
          end
        end
      end
    end
  end
end
