module Datadog
  module Debugging
    module Configuration
      # Settings
      module Settings
        extend Datadog::Core::Configuration::Base::ClassMethods
        include Datadog::Core::Configuration::Base::InstanceMethods
        extend Datadog::Core::Configuration::Options::ClassMethods
        include Datadog::Core::Configuration::Options::InstanceMethods

        def self.extended: (untyped base) -> untyped

        def self.add_settings!: (untyped base) -> untyped

        def self.enabled:  -> bool
      end
    end
  end
end
