module Datadog
  module Core
    module Telemetry
      module Http
        class Transport
          @adapter: Http::Adapters::Net

          attr_reader host: String

          attr_reader port: Integer

          attr_reader ssl: bool

          attr_reader path: String

          def initialize: () -> void

          def request: (request_type: String, payload: String) -> Datadog::Core::Telemetry::Http::Adapters::Net::response

          private

          def headers: (request_type: untyped, ?api_version: untyped) -> ::Hash[untyped, untyped]

          def adapter: () -> Http::Adapters::Net
        end
      end
    end
  end
end
