require 'datadog/demo_env'

source "https://rubygems.org"

gem 'puma'
gem 'unicorn'
gem 'sinatra', '>= 2.2.4', '< 3'

gem 'dogstatsd-ruby'
# Choose correct specs for 'datadog' demo environment
gem 'datadog', *Datadog::DemoEnv.gem_spec('datadog')

# Development
gem 'pry-byebug'
# gem 'pry-stack_explorer', platform: :ruby
# gem 'rbtrace'
# gem 'ruby-prof'
gem 'rspec'
gem 'rspec-wait'
gem 'webrick'
gem 'rackup'
