require 'datadog/demo_env'

source "https://rubygems.org"

gem 'puma'
gem 'unicorn'
gem 'sinatra', '>= 2.2.4', '< 3'

gem 'dogstatsd-ruby'
# Choose correct specs for 'ddtrace' demo environment
gem 'ddtrace', *Datadog::DemoEnv.gem_spec('ddtrace')

# Needed for ddtrace profiling
google_protobuf_versions = [
  '~> 3.0',
  '!= 3.7.0.rc.2',
  '!= 3.7.0.rc.3',
  '!= 3.7.0',
  '!= 3.7.1',
  '!= 3.8.0.rc.1',
  '!= 3.24.0.rc.1',
]
if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.4')
  gem 'google-protobuf', *google_protobuf_versions
else
  # Bundler resolves incorrect version (too new, incompatible with Ruby <= 2.3)
  gem 'google-protobuf', *google_protobuf_versions, '< 3.19.2'
end

# Development
gem 'pry-byebug'
# gem 'pry-stack_explorer', platform: :ruby
# gem 'rbtrace'
# gem 'ruby-prof'
gem 'rspec'
gem 'rspec-wait'
gem 'webrick' if RUBY_VERSION >= '2.3' # Older Rubies can just use the built-in version of webrick
gem 'rackup'
