module Datadog
  module AppSec
    module Contrib
      module GraphQL
        module AppSecTrace
          def execute_multiplex: (multiplex: untyped) -> untyped
        end
      end
    end
  end
end
