module Datadog
  module Core
    module Remote
      module Tie
        PASS: Boot

        @mutex: ::Thread::Mutex
        @boot_key: [ ::Integer, ::Integer ]?

        class Boot < ::Struct[[Symbol, Numeric]]
          def initialize: (Symbol? barrier, Numeric? time) -> void

          attr_reader barrier: Symbol
          attr_reader time: Numeric
        end

        def self.boot: () -> Boot?

        def self.reset_for_tests!: () -> void
      end
    end
  end
end
