module Datadog
  module Core
    module Remote
      module Tie
        PASS: Boot

        @mutex: ::Thread::Mutex
        @booted_in_pid: ::Integer?
        @booted_remote_id: ::Integer?

        class Boot < ::Struct[[Component::Barrier, Numeric]]
          def initialize: (Component::Barrier? barrier, Numeric? time) -> void

          attr_reader barrier: Component::Barrier
          attr_reader time: Numeric
        end

        def self.boot: () -> Boot?

        def self.reset_for_tests!: () -> void
      end
    end
  end
end
