module Datadog
  module Core
    module Remote
      module Tie
        class Boot < ::Struct[[Component::Barrier, Numeric]]
          def initialize: (Component::Barrier? barrier, Numeric? time) -> void

          attr_reader barrier: Component::Barrier
          attr_reader time: Numeric
        end

        def self.boot: () -> Boot?
      end
    end
  end
end
