module Datadog
  module Core
    module Remote
      class Worker
        attr_reader logger: ::Logger

        @logger: ::Logger
        @starting: bool
        @started: bool
        @stopped: bool
        @thr: Thread?
        @interval: ::Float
        @mutex: ::Thread::Mutex
        @block: (^() -> void)

        def initialize: (interval: ::Float, logger: ::Logger) { () -> void } -> void

        def start: () -> void

        def stop: () -> void

        def started?: () -> bool

        private

        def poll: (::Float interval) -> void

        def call: () -> void
      end
    end
  end
end
