module Datadog
  module Tracing
    module Contrib
      module ActionView
        module Instrumentation
          module PartialRenderer
            def render: (*untyped args) ?{ () -> untyped } -> untyped

            def render_partial: (*untyped args) -> untyped

            def datadog_render_partial: (untyped template) -> untyped

            private

            attr_accessor active_datadog_span: untyped

            def with_datadog_span: (untyped span) { () -> untyped } -> untyped
            module RailsLessThan4
              include PartialRenderer

              def datadog_template: (*untyped args) -> untyped
            end
          end
        end
      end
    end
  end
end
