module Datadog
  module Tracing
    module Contrib
      module ActionView
        module Instrumentation
          module TemplateRenderer
            module Rails31Plus
              def render: (*untyped args) ?{ () -> untyped } -> untyped

              def render_template: (*untyped args) -> untyped

              def datadog_render_template: (untyped template, untyped layout_name) -> untyped

              private

              attr_accessor active_datadog_span: untyped

              def with_datadog_span: (untyped span) { () -> untyped } -> untyped
            end
            module RailsLessThan4
              include Rails31Plus

              def datadog_parse_args: (untyped template, untyped layout_name, *untyped args) -> ::Array[untyped]
            end
          end
        end
      end
    end
  end
end
