module Datadog
  module AppSec
    module Contrib
      module Configuration
        class Settings
          include Datadog::Core::Configuration::Base

          include Datadog::Core::Environment::VariableHelpers
          extend Datadog::Core::Environment::VariableHelpers
          extend Datadog::Core::Configuration::Options::ClassMethods
        end
      end
    end
  end
end
