module Datadog
  module Tracing
    module Contrib
      module Configurable
        def self.included: (untyped base) -> untyped
        module InstanceMethods
          def configuration: (?::Symbol matcher) -> untyped
          def resolve: (untyped value) -> untyped
          def configurations: () -> untyped
          def configure: (?::Symbol matcher, ?::Hash[untyped, untyped] options) ?{ () -> untyped } -> untyped
          def reset_configuration!: () -> untyped
          def default_configuration: () -> untyped
          def new_configuration: () -> untyped
          def resolver: () -> untyped
        end
      end
    end
  end
end
