module Datadog
  module Tracing
    module Contrib
      module Ext
        module DB
          TAG_INSTANCE: "db.instance"

          TAG_USER: "db.user"

          TAG_SYSTEM: "db.system"

          TAG_STATEMENT: "db.statement"

          TAG_ROW_COUNT: "db.row_count"
        end

        module RPC
          TAG_SYSTEM: "rpc.system"

          TAG_SERVICE: "rpc.service"

          TAG_METHOD: "rpc.method"
        end

        module Messaging
          TAG_KAFKA_BOOTSTRAP_SERVERS: "messaging.kafka.bootstrap.servers"
          TAG_SYSTEM: "messaging.system"

          TAG_RABBITMQ_ROUTING_KEY: "messaging.rabbitmq.routing_key"
        end

        module SpanAttributeSchema
          PEER_SERVICE_SOURCE_AWS: Array[string]
          PEER_SERVICE_SOURCE_DB: Array[string]
          PEER_SERVICE_SOURCE_MSG: Array[string]
          PEER_SERVICE_SOURCE_RPC: Array[string]
        end
      end
    end
  end
end
