module Datadog
  module Tracing
    module Contrib
      module SpanAttributeSchema
        PEER_SERVICE_SOURCE_DB: Array[string]
        PEER_SERVICE_SOURCE_DEFAULT: Array[string]
        PEER_SERVICE_SOURCE_MSG: Array[string]
        PEER_SERVICE_SOURCE_RPC: Array[string]

        def self?.fetch_service_name: (string env, string default) -> bool

        def not_empty_tag?: (string) -> bool

        def set_peer_service: -> bool

        def set_peer_service?: -> bool

        def set_peer_service_from_source: -> bool
      end
    end
  end
end
