module Datadog
  module Tracing
    module Contrib
      module SpanAttributeSchema
        NO_SOURCE: Array[string]
        REFLEXIVE_SOURCES: Array[string]

        def self?.fetch_service_name: (string env, string default) -> bool

        def self.filter_peer_service_sources: (SpanOperation span, Array[string] sources) -> Array[string]

        def self.not_empty_tag?: (string tag) -> bool

        def self.set_peer_service!: (SpanOperation span, Array[string] sources) -> bool

        def self.set_peer_service_from_source: (SpanOperation span, Array[string] sources) -> [string, string]
      end
    end
  end
end
