module Datadog
  module Tracing
    module Contrib
      class StatusCodeMatcher
        REGEX_PARSER: ::Regexp

        def initialize: (untyped range) -> void

        def include?: (untyped exception_status) -> untyped

        def to_s: () -> untyped

        private

        def set_range: () -> untyped

        def error_responses: () -> untyped

        def handle_statuses: () -> untyped
      end
    end
  end
end
