module Datadog
  module Tracing
    module Contrib
      class StatusRangeMatcher
        type range_type = Array[Integer | Range[Integer]]

        @ranges: range_type

        attr_reader ranges: range_type

        def initialize: (Integer | Range[Integer] | range_type ranges) -> void

        def +: (StatusRangeMatcher other) -> StatusRangeMatcher

        alias concat +

        def include?: (Integer status) -> bool
      end
    end
  end
end
