module Datadog
  module Core
    module Crashtracking
      module AgentBaseUrl
        IPV6_REGEXP: Regexp
        def self.resolve: (Datadog::Core::Configuration::AgentSettingsResolver::AgentSettings) -> ::String?
      end
    end
  end
end
