module Datadog
  module AppSec
    module APISecurity
      module EndpointCollection
        interface _Route
          def dispatcher?: () -> bool
          def verb: () -> String
          def path: () -> _RoutePath
        end

        interface _RoutePath
          def spec: () -> _RouteSpec
        end

        interface _RouteSpec
          def to_s: () -> String
        end

        class RailsRoutesSerializer
          FORMAT_SUFFIX: String

          @routes: Array[_Route]

          def initialize: (Array[_Route] routes) -> void

          def to_enum: () -> Enumerator[Core::Telemetry::Event::AppEndpointsLoaded::endpoint]

          def serialize_route: (_Route route) -> Core::Telemetry::Event::AppEndpointsLoaded::endpoint
        end
      end
    end
  end
end
