module Datadog
  module Tracing
    module Contrib
      module Rails
        module Configuration
          class Settings < Contrib::Configuration::Settings
            def initialize: (?::Hash[untyped, untyped] options) -> void
          end
        end
      end
    end
  end
end
