module Datadog
  module Utils
    # Traces generated by the client internals
    module InternalTraces
      def self.included(klass)
        klass.extend(ClassMethods)
      end

      # ClassMethods
      module ClassMethods
        attr_writer :internal_trace_service

        def internal_trace_service
          @internal_trace_service ||= 'datadog.unknown'.freeze
        end
      end

      INTERNAL_TAG = 'datadog.internal'.freeze

      def internal_span(name, *args)
        return yield unless Datadog.tracer.internal_traces

        Datadog.tracer.trace(name, *args) do |span|
          span.set_tag(INTERNAL_TAG, true)
          span.service = self.class.internal_trace_service
          yield
        end
      end

      def internal_span_when(condition, name, *args, &block)
        return yield unless Datadog.tracer.internal_traces

        condition = condition.call if condition.respond_to?(:send)
        return yield unless condition

        internal_span(name, *args, &block)
      end

      def internal_child_span(name, *args, &block)
        return yield unless Datadog.tracer.internal_traces

        internal_span_when(-> { Datadog.tracer.active_span }, name, *args, &block)
      end

      def with_active_internal_span
        return unless Datadog.tracer.internal_traces

        span = Datadog.tracer.active_span
        yield(span) if span && span.get_tag(INTERNAL_TAG)
      end
    end
  end
end
