module Datadog
  module OpenFeature
    module Transport
      module HTTP
        module API
          EXPOSURES: ::String

          def self?.defaults: () -> untyped
        end
      end
    end
  end
end
