module Datadog
  module OpenFeature
    module Transport
      module HTTP
        class Client
          include ::Datadog::OpenFeature::Transport::HTTP::Exposures::Client

          attr_reader api: Core::Transport::HTTP::API::Instance
          attr_reader logger: Core::Logger

          def initialize: (Core::Transport::HTTP::API::Instance, logger: Core::Logger?) -> void

          def send_request: (Transport::Exposures::Request) { (Core::Transport::HTTP::API::Instance, Core::Transport::HTTP::Env) -> Core::Transport::Response } -> Core::Transport::Response

          private

          def build_env: (Transport::Exposures::Request) -> Core::Transport::HTTP::Env
        end
      end
    end
  end
end
