module Datadog
  module OpenFeature
    module Transport
      module HTTP
        module Exposures
          module Client
            def send_exposures_payload: (Transport::Exposures::Request) -> Core::Transport::Response

            private

            def send_request: (Transport::Exposures::Request) { (OpenFeature::Transport::HTTP::Exposures::API::Instance, Core::Transport::HTTP::Env) -> Core::Transport::Response } -> Core::Transport::Response
          end

          module API
            class Spec < Datadog::Core::Transport::HTTP::API::Spec
              attr_accessor endpoint: Transport::HTTP::Exposures::API::Endpoint?

              def send_exposures: (Core::Transport::HTTP::Env) { (Core::Transport::HTTP::Env) -> Core::Transport::Response } -> Core::Transport::Response
            end

            class Instance < Datadog::Core::Transport::HTTP::API::Instance
              def send_exposures: (Core::Transport::HTTP::Env) -> Core::Transport::Response
            end

            class Endpoint < Datadog::Core::Transport::HTTP::API::Endpoint
              HEADER_CONTENT_TYPE: ::String

              HEADER_SUBDOMAIN: ::String

              SUBDOMAIN_VALUE: ::String

              attr_reader encoder: Core::Encoding::Encoder

              def initialize: (::String, Core::Encoding::Encoder) -> void

              def call: (Core::Transport::HTTP::Env) { (Core::Transport::HTTP::Env) -> Core::Transport::Response } -> Core::Transport::Response
            end
          end
        end
      end
    end
  end
end
