module Datadog
  module DI
    module Transport
      module HTTP
        module API
          DIAGNOSTICS: String
          INPUT: String
          LEGACY_INPUT: String

          def self?.defaults: () -> untyped
        end
      end
    end
  end
end
