module Datadog
  module DI
    module Transport
      module HTTP
        class Client
          @api: untyped

          @logger: untyped

          attr_reader api: untyped

          attr_reader logger: untyped

          def initialize: (untyped api, logger: untyped) -> void

          def send_request: (untyped request) { (untyped, untyped) -> untyped } -> untyped

          def build_env: (untyped request) -> untyped
        end
      end
    end
  end
end
