module Datadog
  module Kit
    module AppSec
      module Events
        LOGIN_SUCCESS_EVENT: ::String

        LOGIN_FAILURE_EVENT: ::String

        SIGNUP_EVENT: ::String

        USER_LOGIN_KEYS: Array[String | Symbol]

        def self.track_login_success: (?::Datadog::Tracing::TraceOperation? trace, ?::Datadog::Tracing::SpanOperation? span, user: Hash[Symbol, String], **Hash[Symbol | String, String] others) -> void

        def self.track_login_failure: (?::Datadog::Tracing::TraceOperation? trace, ?::Datadog::Tracing::SpanOperation? span, user_exists: bool, ?user_id: String?, **Hash[Symbol | String, String] others) -> void

        def self.track_signup: (?::Datadog::Tracing::TraceOperation? trace, ?::Datadog::Tracing::SpanOperation? span, user: Hash[Symbol, String], **Hash[Symbol | String, String] others) -> void

        def self.track: (String event, ?::Datadog::Tracing::TraceOperation? trace, ?::Datadog::Tracing::SpanOperation? span, **Hash[Symbol, String] others) -> void

        private

        def self.set_trace_and_span_context: (String method, ?::Datadog::Tracing::TraceOperation? trace, ?::Datadog::Tracing::SpanOperation? span) { (::Datadog::Tracing::TraceOperation, ::Datadog::Tracing::SpanOperation) -> void } -> void

        def self.check_trace_span_integrity: (::Datadog::Tracing::TraceOperation trace, ::Datadog::Tracing::SpanOperation span) -> void
      end
    end
  end
end
