# frozen_string_literal: true

require "spec_helper"
require "tmpdir"
require "date"
require_relative "../../../tasks/lib/release_prep/changelog"

RSpec.describe ReleasePrep::Changelog do
  let(:changelog_fixture) do
    <<~MD
      # CHANGELOG

      ## [Unreleased]

      ## [2.42.0] - 2026-08-31

      ### Added

      * Tracing: Add a thing. ([#6300][])

      [Unreleased]: https://github.com/DataDog/dd-trace-rb/compare/v2.42.0...master
      [2.42.0]: https://github.com/DataDog/dd-trace-rb/compare/v2.41.0...v2.42.0

      <!--- The following link definition list is generated by PimpMyChangelog --->
      [#6300]: https://github.com/DataDog/dd-trace-rb/issues/6300
      [@staleauthor]: https://github.com/staleauthor
    MD
  end

  around do |example|
    Dir.mktmpdir do |dir|
      @dir = dir
      example.run
    end
  end

  def write_changelog(content = nil)
    content ||= changelog_fixture

    path = File.join(@dir, "CHANGELOG.md")
    File.write(path, content)
    path
  end

  def fragment(number, type: "Fixed", product: "Tracing", message: "Fix a bug.", author: nil)
    entry = {
      "type" => type,
      "product" => product,
      "pull_request" => "https://github.com/DataDog/dd-trace-rb/pull/#{number}",
      "message" => message,
    }
    entry["author"] = author if author
    ReleasePrep::Fragment.new("unreleased/20260906120000.json", entry)
  end

  subject(:changelog) { described_class.new(path: write_changelog) }

  describe "#release" do
    before do
      allow(Date).to receive(:today).and_return(Date.new(2026, 9, 9))
    end

    it "publishes the rendered fragments as a new version and regenerates the link-definition block" do
      fragments = ReleasePrep::Fragments.new([
        fragment("6142", type: "Added", message: "Add a feature."),
        fragment("6143", type: "Fixed", product: "AppSec", message: "Fix a bug.", author: "@tester"),
      ])

      changelog.release("2.43.0", fragments)

      expected = <<~MD
        # CHANGELOG

        ## [Unreleased]

        ## [2.43.0] - 2026-09-09

        ### Added

        * Tracing: Add a feature. ([#6142][])

        ### Fixed

        * AppSec: Fix a bug. ([#6143][]) ([@tester][])

        ## [2.42.0] - 2026-08-31

        ### Added

        * Tracing: Add a thing. ([#6300][])

        [Unreleased]: https://github.com/DataDog/dd-trace-rb/compare/v2.43.0...master
        [2.43.0]: https://github.com/DataDog/dd-trace-rb/compare/v2.42.0...v2.43.0
        [2.42.0]: https://github.com/DataDog/dd-trace-rb/compare/v2.41.0...v2.42.0

        <!--- The following link definition list is generated by PimpMyChangelog --->
        [#6142]: https://github.com/DataDog/dd-trace-rb/issues/6142
        [#6143]: https://github.com/DataDog/dd-trace-rb/issues/6143
        [#6300]: https://github.com/DataDog/dd-trace-rb/issues/6300
        [@staleauthor]: https://github.com/staleauthor
        [@tester]: https://github.com/tester
      MD

      expect(File.read(File.join(@dir, "CHANGELOG.md"))).to eq(expected.chomp)
    end

    it "fails loudly when the [Unreleased] compare link is missing" do
      changelog = described_class.new(path: write_changelog("## [Unreleased]\n"))

      expect { changelog.release("2.43.0", ReleasePrep::Fragments.new([fragment("6142")])) }.to raise_error(SystemExit)
    end

    it "fails loudly when the [Unreleased] marker is missing" do
      changelog = described_class.new(path: write_changelog("# CHANGELOG\n"))

      expect { changelog.release("2.43.0", ReleasePrep::Fragments.new([fragment("6142")])) }.to raise_error(SystemExit)
    end

    it "fails loudly rather than splicing into the footer when only the compare link matches" do
      footer_only = <<~MD
        # CHANGELOG

        ## [2.42.0] - 2026-08-31

        [Unreleased]: https://github.com/DataDog/dd-trace-rb/compare/v2.42.0...master
      MD
      changelog = described_class.new(path: write_changelog(footer_only))

      expect { changelog.release("2.43.0", ReleasePrep::Fragments.new([fragment("6142")])) }.to raise_error(SystemExit)
    end
  end

  describe "#format" do
    it "relinkifies the whole file, regenerating the link-definition block, and is idempotent" do
      changelog.format

      expected = <<~MD
        # CHANGELOG

        ## [Unreleased]

        ## [2.42.0] - 2026-08-31

        ### Added

        * Tracing: Add a thing. ([#6300][])

        [Unreleased]: https://github.com/DataDog/dd-trace-rb/compare/v2.42.0...master
        [2.42.0]: https://github.com/DataDog/dd-trace-rb/compare/v2.41.0...v2.42.0

        <!--- The following link definition list is generated by PimpMyChangelog --->
        [#6300]: https://github.com/DataDog/dd-trace-rb/issues/6300
        [@staleauthor]: https://github.com/staleauthor
      MD

      expect(File.read(File.join(@dir, "CHANGELOG.md"))).to eq(expected.chomp)

      changelog.format
      expect(File.read(File.join(@dir, "CHANGELOG.md"))).to eq(expected.chomp)
    end
  end
end
