module Datadog
  module Tracing
    module Contrib
      module Kafka
        module Events
          module Producer
            module DeliverMessages
              include Kafka::Event

              EVENT_NAME: "deliver_messages.producer.kafka"

              def self?.on_start: (Tracing::SpanOperation span, String _event, String _id, ::Hash[Symbol, any] _payload) -> void

              def self?.on_finish: (Tracing::SpanOperation span, String _event, String _id, ::Hash[Symbol, any] payload) -> void

              def self?.span_name: () -> untyped

              def self?.span_options: () -> untyped
            end
          end
        end
      end
    end
  end
end
