# This file is a hack for the grpc protoc autogenerated gen/test_service_services_pb.rb files to work,
# since they add the following import line: require 'test_service_pb' and they wouldn't work otherwise.
if RUBY_VERSION < '2.3'
  require_relative 'datadog/tracing/contrib/grpc/support/gen/grpc-1.19.0/test_service_pb'
else
  require_relative 'datadog/tracing/contrib/grpc/support/gen/test_service_pb'
end
