# This file is a hack for the grpc protoc autogenerated gen/test_service_services_pb.rb files to work,
# since they add the following import line: require 'test_service_pb' and they wouldn't work otherwise.
require_relative 'datadog/tracing/contrib/grpc/support/gen/test_service_pb'
