require 'datadog/demo_env'

source 'https://rubygems.org'

gem 'ostruct'
gem 'rake'
gem 'hanami',       '~> 1.3'
gem 'hanami-model', '~> 1.3'
gem 'dry-container', '~> 0.8.0'
gem 'dry-configurable', '~> 0.12.0'

gem 'sqlite3'
gem 'puma'
gem 'unicorn'
gem 'webrick'
gem 'pry-byebug'

gem *Datadog::DemoEnv.gem_datadog_auto_instrument
gem 'google-protobuf', '~> 3.0'

group :development do
  # Code reloading
  # See: https://guides.hanamirb.org/projects/code-reloading
  gem 'shotgun', platforms: :ruby
  gem 'hanami-webconsole'
end

group :test, :development do
  gem 'dotenv', '~> 2.4'
end

group :development, :test do
  if RUBY_VERSION >= '3.1'
    gem "debug", platforms: %i,mri mingw x64_mingw,
  else
    gem "byebug", platforms: %w,mri,
  end
end

group :test do
  gem 'rspec'
  # gem 'capybara'
end

group :production do
  # gem 'puma'
end
