require 'datadog/demo_env'

source 'https://rubygems.org'

gem 'rake'
gem 'hanami',       '~> 1.3'
gem 'hanami-model', '~> 1.3'
gem 'dry-container', '~> 0.8.0'

gem 'sqlite3'
gem 'puma'
gem 'unicorn'
gem 'webrick'
gem 'pry-byebug'

gem_spec = Datadog::DemoEnv.gem_spec('datadog')
req = {require: 'datadog/auto_instrument'}
opts = if gem_spec.last.is_a?(Hash)
  gem_spec.pop.merge(req)
else
  req
end
gem_spec << opts
gem 'datadog', *gem_spec
gem 'google-protobuf', '~> 3.0'

group :development do
  # Code reloading
  # See: https://guides.hanamirb.org/projects/code-reloading
  gem 'shotgun', platforms: :ruby
  gem 'hanami-webconsole'
end

group :test, :development do
  gem 'dotenv', '~> 2.4'
end

group :test do
  gem 'rspec'
  # gem 'capybara'
end

group :production do
  # gem 'puma'
end
