module Datadog
  extend Core::Extensions
  extend Core::Configuration

  # Extended in datadog/tracing/contrib/extensions.rb
  extend Tracing::Contrib::Extensions::Helpers
  extend Tracing::Contrib::Extensions::Configuration
end
