module Datadog
  extend Core::Extensions
  extend Core::Configuration

  DATADOG_ENV: Core::Configuration::ConfigHelper

  # Extended in datadog/tracing/contrib/extensions.rb
  extend Tracing::Contrib::Extensions::Helpers
  extend Tracing::Contrib::Extensions::Configuration
end
