module Datadog
  module Tracing
    module Contrib
      module Qless
        module QlessJob
          def around_perform: (untyped job) -> untyped

          def after_fork: () -> (nil | untyped)

          private

          def span_options: () -> { service: untyped }

          def datadog_configuration: () -> untyped
        end
      end
    end
  end
end
