module Datadog
  module Tracing
    module Contrib
      module Qless
        module TracerCleaner
          def around_perform: (untyped job) -> untyped

          private

          def forked?: () -> untyped

          def datadog_configuration: () -> untyped
        end
      end
    end
  end
end
