module Datadog
  module SymbolDatabase
    class Component
      EXTRACT_DEBOUNCE_INTERVAL: Integer

      @settings: untyped
      @agent_settings: untyped
      @logger: untyped
      @extractor: Extractor
      @uploader: Uploader
      @scope_batcher: ScopeBatcher
      @last_upload_time: Time?
      @last_upload_scope_count: Integer?
      @last_upload_time_cv: Thread::ConditionVariable
      @mutex: Thread::Mutex
      @upload_in_progress: bool
      @upload_in_progress_cv: Thread::ConditionVariable
      @shutdown: bool
      @scheduler_mutex: Thread::Mutex
      @scheduler_cv: Thread::ConditionVariable
      @scheduled_at: Float?
      @scheduler_signaled: bool
      @scheduler_thread: Thread?
      @hot_load_buffer: Array[Module]
      @hot_load_buffer_mutex: Thread::Mutex
      @hot_load_tracepoint: TracePoint?
      @initial_extraction_done: bool

      def self.build: (untyped settings, untyped agent_settings, untyped logger) -> Component?

      def initialize: (untyped settings, untyped agent_settings, untyped logger) -> void

      attr_reader settings: untyped
      attr_reader last_upload_time: Time?
      attr_reader last_upload_scope_count: Integer?
      attr_reader upload_in_progress: bool

      def schedule_deferred_upload: () -> void

      def shutdown?: () -> bool

      def start_upload: () -> void

      def stop_upload: () -> void

      def wait_for_idle: (?timeout: Numeric) -> bool

      def shutdown!: () -> void

      private

      def self.environment_supported?: (untyped logger) -> bool

      def ensure_scheduler_thread: () -> void

      def scheduler_loop: () -> void

      def extract_and_upload: () -> void

      def extract_hot_load_buffer: () -> Array[Scope]

      def install_hot_load_hook: () -> void

      def enqueue_hot_load: (Module mod) -> void

      def log_scope_tree: (Scope scope, Integer depth) -> void

      def count_targetable_methods: (Array[Scope] file_scopes) -> Integer
    end
  end
end
