module Datadog
  module SymbolDatabase
    class Component
      EXTRACT_DEBOUNCE_INTERVAL: ::Numeric
      MODULE_SINGLETON_CLASS_PRED: ::UnboundMethod

      @settings: Datadog::Core::Configuration::Settings
      @agent_settings: Datadog::Core::Configuration::AgentSettings
      @logger: SymbolDatabase::Logger
      @telemetry: Datadog::Core::Telemetry::Component?
      @extractor: Extractor
      @uploader: Uploader
      @scope_batcher: ScopeBatcher
      @last_upload_time: ::Time?
      @last_upload_scope_count: ::Integer?
      @last_upload_time_cv: ::Thread::ConditionVariable
      @mutex: ::Thread::Mutex
      @upload_in_progress: bool
      @upload_in_progress_cv: ::Thread::ConditionVariable
      @shutdown: bool
      @scheduler_mutex: ::Thread::Mutex
      @scheduler_cv: ::Thread::ConditionVariable
      @scheduled_at: ::Float?
      @scheduler_signaled: bool
      @scheduler_thread: ::Thread?
      @owner_pid: ::Integer
      @hot_load_buffer: ::Array[::Module]
      @hot_load_buffer_mutex: ::Thread::Mutex
      @hot_load_tracepoint: ::TracePoint?
      @initial_extraction_done: bool
      @di_active: (^() -> bool)?
      @upload_pending: bool

      def self.build: (Datadog::Core::Configuration::Settings settings, Datadog::Core::Configuration::AgentSettings agent_settings, ::Logger logger, ?telemetry: Datadog::Core::Telemetry::Component?, ?di_active: (^() -> bool)?) -> Component?

      def initialize: (Datadog::Core::Configuration::Settings settings, Datadog::Core::Configuration::AgentSettings agent_settings, SymbolDatabase::Logger logger, ?telemetry: Datadog::Core::Telemetry::Component?, ?di_active: (^() -> bool)?) -> void

      attr_reader settings: Datadog::Core::Configuration::Settings
      attr_reader logger: SymbolDatabase::Logger
      attr_reader last_upload_time: ::Time?
      attr_reader last_upload_scope_count: ::Integer?
      attr_reader upload_in_progress: bool

      def schedule_deferred_upload: () -> void

      def shutdown?: () -> bool

      def start_upload: () -> void

      def stop_upload: () -> void

      def resume_pending_upload: () -> void

      def stop_for_di_disable: () -> void

      def wait_for_idle: (?timeout: ::Numeric) -> bool

      def shutdown!: () -> void

      def after_fork!: () -> void

      private

      def upload_allowed?: () -> bool

      def deferred_by_di_gate?: () -> bool

      def self.environment_supported?: (SymbolDatabase::Logger logger) -> bool

      def ensure_scheduler_thread: () -> void

      def scheduler_loop: () -> void

      def extract_and_upload: () -> void

      def extract_hot_load_buffer: () -> ::Array[Scope]

      def install_hot_load_hook: () -> void

      def enqueue_hot_load: (::Module mod) -> void

      def log_scope_tree: (Scope scope, ::Integer depth) -> void

      def count_targetable_methods_in_scope: (Scope file_scope) -> ::Integer
    end
  end
end
