module Datadog
  module SymbolDatabase
    class Component
      EXTRACT_DEBOUNCE_INTERVAL: Integer

      self.@uploaded_this_process: bool
      self.@upload_done_mutex: Thread::Mutex
      self.@upload_done_cv: Thread::ConditionVariable

      def self.upload_done_mutex: () -> Thread::Mutex
      def self.upload_done_cv: () -> Thread::ConditionVariable
      def self.uploaded_this_process?: () -> bool
      def self.mark_uploaded: () -> void
      def self.reset_uploaded_this_process_for_tests!: () -> void

      @settings: untyped
      @agent_settings: untyped
      @logger: untyped
      @extractor: Extractor
      @uploader: Uploader
      @scope_batcher: ScopeBatcher
      @last_upload_time: Time?
      @last_upload_scope_count: Integer?
      @mutex: Thread::Mutex
      @upload_in_progress: bool
      @upload_in_progress_cv: Thread::ConditionVariable
      @shutdown: bool
      @scheduler_mutex: Thread::Mutex
      @scheduler_cv: Thread::ConditionVariable
      @scheduled_at: Float?
      @scheduler_signaled: bool
      @scheduler_thread: Thread?

      def self.build: (untyped settings, untyped agent_settings, untyped logger) -> Component?

      def initialize: (untyped settings, untyped agent_settings, untyped logger) -> void

      attr_reader settings: untyped
      attr_reader last_upload_time: Time?
      attr_reader last_upload_scope_count: Integer?
      attr_reader upload_in_progress: bool

      def schedule_deferred_upload: () -> void

      def shutdown?: () -> bool

      def start_upload: () -> void

      def stop_upload: () -> void

      def wait_for_idle: (?timeout: Numeric) -> bool

      def shutdown!: () -> void

      private

      def self.environment_supported?: (untyped logger) -> bool

      def ensure_scheduler_thread: () -> void

      def scheduler_loop: () -> void

      def extract_and_upload: () -> void

      def log_scope_tree: (Scope scope, Integer depth) -> void

      def count_targetable_methods: (Array[Scope] file_scopes) -> Integer
    end
  end
end
