module Datadog
  module SymbolDatabase
    class MethodRecord < ::Struct[untyped]
      attr_accessor name: ::Symbol

      attr_accessor source_file: ::String

      attr_accessor start_line: ::Integer

      attr_accessor end_line: ::Integer

      attr_accessor targetable_lines: Array[Hash[::Symbol, ::Integer]]?

      attr_accessor visibility: ::String

      attr_accessor arity: ::Integer

      attr_accessor parameters: Array[Symbol]

      attr_accessor user_code: bool

      def self.new: (
        name: ::Symbol,
        source_file: ::String,
        start_line: ::Integer,
        end_line: ::Integer,
        targetable_lines: Array[Hash[::Symbol, ::Integer]]?,
        visibility: ::String,
        arity: ::Integer,
        parameters: Array[Symbol],
        user_code: bool
      ) -> MethodRecord
    end
  end
end
