module Datadog
  module SymbolDatabase
    class ScopeBatcher
      MAX_SCOPES: Integer

      INACTIVITY_TIMEOUT: Float

      MAX_FILES: Integer

      @uploader: Uploader

      @logger: Logger

      @telemetry: untyped

      @on_upload: Proc?

      @timer_enabled: bool

      @scopes: Array[Scope]

      @mutex: Mutex

      @timer_cv: Thread::ConditionVariable

      @timer_thread: Thread?

      @timer_stopped: bool

      @timer_signaled: bool

      @file_count: Integer

      @uploaded_modules: Set[String?]

      def initialize: (Uploader uploader, logger: Logger, ?telemetry: untyped, ?on_upload: Proc?, ?timer_enabled: bool) -> void

      def add_scope: (Scope scope) -> void

      def flush: () -> void

      def shutdown: () -> void

      def reset: () -> void

      def perform_upload: (Array[Scope]? scopes) -> void

      def scopes_pending?: () -> bool

      def size: () -> Integer

      private

      def ensure_timer_running: () -> void

      def timer_loop: () -> void
    end
  end
end
