module Datadog
  module SymbolDatabase
    class Symbol
      @symbol_type: String

      @name: String

      @line: Integer

      @type: String?

      @language_specifics: language_specifics?

      def initialize: (
        symbol_type: String,
        name: String,
        line: Integer,
        ?type: String?,
        ?language_specifics: language_specifics?
      ) -> void

      attr_reader symbol_type: String

      attr_reader name: String

      attr_reader line: Integer

      attr_reader type: String?

      attr_reader language_specifics: language_specifics?

      def to_h: () -> Hash[::Symbol, untyped]

      def to_json: (?untyped _state) -> String
    end
  end
end
