module Datadog
  module SymbolDatabase
    module Transport
      module Symbols
        class Request < Core::Transport::Request
          @form: Hash[untyped, untyped]

          attr_reader form: Hash[untyped, untyped]

          def initialize: (Hash[untyped, untyped] form) -> void
        end

        class Client < Core::Transport::HTTP::Client
          def build_env: (Request request) -> Core::Transport::HTTP::Env
        end

        class Transport < Core::Transport::Transport
          def send_symbols: (Hash[untyped, untyped] form) -> (Core::Transport::HTTP::Response | Core::Transport::InternalErrorResponse)
        end
      end
    end
  end
end
