# frozen_string_literal: true

require "date"
require_relative "../release_prep"

module ReleasePrep
  class Changelog
    PREVIOUS_VERSION_PATTERN = %r{\[Unreleased\]: #{Regexp.escape(REPO_URL)}/compare/v(.+?)\.\.\.master}
    UNRELEASED_FOOTER_PATTERN = %r{\[Unreleased\]: #{Regexp.escape(REPO_URL)}/compare/.*?\.\.\.master}

    def initialize(path: "CHANGELOG.md")
      @path = path
    end

    def release(version, fragments)
      source = File.read(@path)
      previous = previous_version_in(source)
      inserted = insert_version_in(source, version, fragments.render)

      File.write(@path, rewrite_footer_in(linkify_in(inserted), version, previous))
    end

    def format
      File.write(@path, linkify_in(File.read(@path)))
    end

    private

    def previous_version_in(source)
      match = source.match(PREVIOUS_VERSION_PATTERN)
      ReleasePrep.fail!("Could not find the [Unreleased] compare link in #{@path}") unless match

      match[1]
    end

    def insert_version_in(source, version, content)
      match = source.match(/\n## \[Unreleased\]/)
      ReleasePrep.fail!("Could not find [Unreleased] marker in #{@path}") unless match

      section = "\n## [#{version}] - #{Date.today}\n\n#{content}".rstrip
      source.insert(match.end(0), "\n#{section}")
    end

    def rewrite_footer_in(source, version, previous)
      replacement =
        "[Unreleased]: #{REPO_URL}/compare/v#{version}...master\n" \
        "[#{version}]: #{REPO_URL}/compare/v#{previous}...v#{version}"

      unless source.match?(UNRELEASED_FOOTER_PATTERN)
        ReleasePrep.fail!("Could not find [Unreleased] compare link in #{@path}")
      end

      source.sub(UNRELEASED_FOOTER_PATTERN, replacement)
    end

    # Linkification ported verbatim from the unmaintained pimpmychangelog gem
    # (0.1.3, Pimper/Parser) that this replaced; changelog_spec pins the exact
    # output bytes. Definitions regenerate from a scan of the WHOLE text —
    # including the previous definition block — so stale definitions survive
    # until their token disappears from the content.
    def linkify_in(text)
      content = text.split(SEPARATOR).first
      linkified = content.gsub(ISSUE_NUMBER_REGEXP, '\1[#\2][]\3').gsub(CONTRIBUTOR_REGEXP, '\1[@\2][]\3')

      linkified + (content.match?(/\n\n\Z/) ? "" : "\n") + link_definitions_in(text)
    end

    def link_definitions_in(text)
      issues = text.scan(/#(\d+)/).flatten.uniq.sort_by(&:to_i)
      contributors = text.scan(/@([\w-]+)/).flatten.uniq.sort
      return "" if issues.empty? && contributors.empty?

      issue_lines = issues.map { |issue| "[##{issue}]: https://github.com/#{REPO}/issues/#{issue}" }
      contributor_lines = contributors.map { |contributor| "[@#{contributor}]: https://github.com/#{contributor}" }

      ([SEPARATOR] + issue_lines + contributor_lines).join("\n")
    end

    # The separator string is kept verbatim from pimpmychangelog: the real
    # CHANGELOG.md contains it and must keep being recognized.
    SEPARATOR = "<!--- The following link definition list is generated by PimpMyChangelog --->"
    ISSUE_NUMBER_REGEXP = /(^|[^\[])#(\d+)($|[^\]])/
    CONTRIBUTOR_REGEXP = /(^|[^\[])@([\w-]+)($|[^\]])/
  end
end
