module Datadog
  module Tracing
    module Contrib
      module GRPC
        module Patcher
          include Contrib::Patcher

          def self?.target_version: () -> untyped

          def self?.patch: () -> untyped

          def self?.prepend_interceptor: () -> untyped
        end
      end
    end
  end
end
