module Datadog
  module CI
    module Contrib
      module Cucumber
        module Instrumentation
          def self.included: (untyped base) -> untyped
          module InstanceMethods
            attr_reader datadog_formatter: untyped

            def formatters: () -> untyped
          end
        end
      end
    end
  end
end
