require 'datadog/demo_env'

source 'https://rubygems.org' do
  # Framework dependent gems
  # gem 'rails', '5.2.2'

  google_protobuf_versions = [
    '~> 3.0',
    '!= 3.7.0.rc.2',
    '!= 3.7.0.rc.3',
    '!= 3.7.0',
    '!= 3.7.1',
    '!= 3.8.0.rc.1'
  ]

  # gem 'rack', '2.1.4' # Ruby 2.2 compatibility
  gem 'actioncable', '5.2.2'
  gem 'actionmailer', '5.2.2'
  gem 'actionpack', '5.2.2'
  gem 'actionview', '5.2.2'
  gem 'activejob', '5.2.2'
  gem 'activemodel', '5.2.2'
  gem 'activerecord', '5.2.2'
  gem 'railties', '5.2.2'

  gem 'mysql2'
  gem 'puma'
  gem 'unicorn'

  # Choose correct specs for 'ddtrace' demo environment
  gem 'ddtrace', *Datadog::DemoEnv.gem_spec('ddtrace')

  gem 'dogstatsd-ruby'
  gem 'ffi'
  gem 'google-protobuf', *google_protobuf_versions # Ruby 2.2 compatibility
  # gem 'rbtrace'
  # gem 'ruby-prof'

  # Fixes conflict with profiling (patch overwrite in Thread)
  # Upgrade this to latest when this patch is merged & released.
  # https://github.com/rollbar/rollbar-gem/pull/1018
  gem 'rollbar', git: 'https://github.com/rollbar/rollbar-gem.git', ref: '310a9d1743bb44031480b49e8e0cef79ddc870c3'

  # Gems which give aide to higher performance
  gem 'hiredis', '~> 0.6', platform: :ruby
  gem 'multi_json'
  gem 'oj', '3.3', platform: :ruby

  gem 'active_model_serializers', '0.9.3'
  gem 'activerecord-import' # Speeds up mass imports
  gem 'aws-sdk', '< 2.0'
  gem 'bcrypt-ruby', platform: :ruby
  gem 'connection_pool'
  gem 'devise'
  gem 'faker', require: false # Make up fake data to put in models for load testing
  gem 'geoip'
  gem 'hawk-auth'
  gem 'httparty'
  gem 'ipaddress'
  # gem 'i18n', '1.5.1' # Ruby 2.2 compatibility
  # gem 'newrelic_rpm', platform: :ruby
  gem 'rabl', platform: :ruby
  gem 'rack-cors'
  gem 'rake'
  gem 'redis'
  gem 'resque'
  # gem 'resque-pool' # Incompatible with Redis 4.0+
  gem 'resque-scheduler'
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :jruby]
  gem 'validates_timeliness', '~> 3.0.8' # Date comparisons
  gem 'versionist'
  gem 'warden'

  group :development do
    gem 'annotate'
    gem 'awesome_print'
    gem 'bullet'
  end

  group :test do
    gem 'ci_reporter_rspec'
    gem 'database_cleaner'
    gem 'factory_girl_rails', '4.5.0'
    gem 'rspec'
    gem 'rspec-collection_matchers'
    gem 'rspec-rails'
    gem 'shoulda-matchers', '4.0.1'
    gem 'simplecov', require: false # Will install simplecov-html as a dependency
    gem 'timecop'
    gem 'webmock'
  end

  group :test, :development do
    # gem 'pry-rails', platform: :ruby
    # gem 'pry-rescue', platform: :ruby
    # gem 'pry-stack_explorer', platform: :ruby
    # gem 'pry-byebug', platform: :ruby
    gem 'byebug', platform: :ruby
    gem 'mock_redis', '0.19.0'
    gem 'parallel_tests'

    gem 'listen'
  end
end
