module Datadog
  module Tracing
    module DataStreams
      def self.checkpoint_produce: (type: untyped, destination: untyped, ?tags: ::Array[untyped]) ?{ (untyped, untyped) -> untyped } -> untyped

      def self.checkpoint_consume: (type: untyped, source: untyped, ?tags: ::Array[untyped]) ?{ (untyped) -> untyped } -> untyped
    end
  end
end
