module Datadog
  module Tracing
    module Metadata
      include Metadata::Tagging
      include Metadata::Errors
      include Metadata::Metastruct
      prepend Metadata::Analytics
    end
  end
end
