module Datadog
  module Tracing
    class OTelThreadContext
      UNKNOWN_LOCAL_ROOT_SPAN_ID: Integer

      @enabled: bool?

      interface _TracingSettings
        def otel_thread_context_enabled: () -> bool
      end

      def initialize: (_TracingSettings tracing_settings) -> void

      def subscribe_to_tracer_events!: (TraceOperation::Events events) -> void

      def set: (trace_id: Integer, span_id: Integer, local_root_span_id: Integer) -> bool

      def after_fork: () -> void

      def clear: () -> bool

      def supported?: () -> bool

      def _native_supported?: () -> bool

      def _native_enable: () -> bool

      def _native_set: (Integer trace_id, Integer span_id, Integer local_root_span_id) -> bool

      def _native_clear: () -> bool

      private

      def enable!: () -> bool
    end
  end
end
