module Datadog
  module Tracing
    class OTelThreadContext
      UNKNOWN_LOCAL_ROOT_SPAN_ID: Integer

      interface _TracingSettings
        def otel_thread_context_enabled: () -> bool
      end

      @span_before_start: ^(SpanOperation, TraceOperation) -> void
      @span_finished: ^(Span?, TraceOperation) -> void

      def self.build: (_TracingSettings tracing_settings) -> OTelThreadContext?

      def initialize: () -> void

      def subscribe_to_tracer_events!: (TraceOperation::Events events) -> void

      def set: (trace_id: Integer, span_id: Integer, local_root_span_id: Integer) -> bool

      def after_fork: () -> void

      def clear: () -> bool

      def supported?: () -> bool

      def update_from_trace_op: (TraceOperation trace_op) -> void

      def _native_supported?: () -> bool

      def _native_enable: () -> bool

      def _native_set: (Integer trace_id, Integer span_id, Integer local_root_span_id) -> bool

      def _native_clear: () -> bool
    end
  end
end
