module Datadog
  module Tracing
    module Pipeline
      self.@mutex: Mutex
      self.@processors: Array[^(TraceSegment trace) -> TraceSegment?]

      def self.before_flush: (*untyped processors) ?{ () -> untyped } -> untyped

      def self.process!: (untyped traces) -> untyped

      def self.processors=: (untyped value) -> untyped

      def self.apply_processors!: (untyped trace) -> untyped
    end
  end
end
