module Datadog
  module Tracing
    class SpanOperation
      include Metadata
      include Metadata::Tagging
      include Metadata::Errors
      prepend Metadata::Analytics
      
      @logger: Core::Logger
      
      attr_reader logger: Core::Logger

      attr_reader links: untyped

      attr_reader span_events: untyped

      attr_reader end_time: ::Time

      attr_reader id: untyped

      attr_reader name: untyped

      attr_reader parent_id: untyped

      attr_reader resource: untyped

      attr_reader service: untyped

      attr_reader start_time: ::Time

      attr_reader trace_id: untyped

      attr_reader type: untyped

      attr_accessor status: untyped

      def initialize: (
          String name,
          ?events: Events,
          ?on_error: on_error,
          ?parent_id: Integer,
          ?resource: String,
          ?service: (String | nil),
          ?start_time: (Time | nil),
          ?tags: (Hash[String, (String|Numeric)] | nil),
          ?trace_id: (Integer | nil),
          ?type: (String | nil),
          ?links: (Array[SpanLink] | nil),
          ?span_events: (Array[SpanEvent] | nil),
          ?id: (Integer | nil)
      ) -> void

      def name=: (untyped name) -> untyped

      def type=: (untyped `type`) -> untyped

      def service=: (untyped service) -> untyped

      def resource=: (untyped resource) -> untyped

      def measure: () { (untyped) -> untyped } -> untyped

      def start: (?untyped? start_time) -> self

      def stop: (?Time? stop_time, ?exception: Exception) -> self?

      def started?: () -> untyped

      def stopped?: () -> untyped

      def start_time=: (untyped time) -> untyped

      def end_time=: (untyped time) -> untyped

      def finish: (?untyped? end_time) -> untyped

      def finished?: () -> untyped

      def duration: () -> untyped

      def set_error: (untyped e) -> untyped

      def to_s: () -> ::String

      def to_hash: () -> untyped

      def pretty_print: (untyped q) -> untyped

      class Events
        include Tracing::Events

        DEFAULT_ON_ERROR: on_error
	
	attr_reader logger: Core::Logger

        attr_reader after_finish: untyped

        attr_reader after_stop: untyped

        attr_reader before_start: untyped

        def initialize: (?logger: Core::Logger, ?on_error: on_error) -> void

        def on_error: () -> OnError

        class AfterFinish < Tracing::Event
          def initialize: () -> void
        end

        class AfterStop < Tracing::Event
          def initialize: () -> void
        end

        class BeforeStart < Tracing::Event
          def initialize: () -> void
        end

        class OnError
          def initialize: (untyped default, ?logger: Core::Logger) -> void
	
          attr_reader logger: Core::Logger

          def wrap_default: () { (untyped, untyped) -> untyped } -> untyped

          def publish: (*untyped args) -> true
        end
      end

      class AlreadyStartedError < StandardError
        def message: () -> "Cannot measure an already started span!"
      end

      private

      attr_reader events: untyped

      attr_reader parent: untyped

      attr_reader span: untyped

      module RefineNil
      end

      def build_span: () -> untyped

      def parent=: (untyped parent) -> untyped

      def duration_marker: () -> untyped

      def start_time_nano: () -> untyped

      def duration_nano: () -> untyped
    end
  end
end
