module Datadog
  module Tracing
    class Span
      include Metadata

      attr_accessor end_time: (Time | nil)
      attr_accessor id: Integer
      attr_accessor meta: Hash[String, String]
      attr_accessor metrics: Hash[String, Float]
      attr_accessor name: String
      attr_accessor parent_id: Integer
      attr_accessor resource: String
      attr_accessor service: (String | nil)
      attr_accessor links: Array[untyped]
      attr_accessor events: Array[untyped]
      attr_accessor type: (String | nil)
      attr_accessor start_time: (Time | nil)
      attr_accessor status: Integer
      attr_accessor trace_id: Integer
      attr_writer duration: (Float | nil)
      attr_reader metastruct: Hash[String | Symbol, untyped]

      def initialize: (
          String name,
          ?duration: (Float | nil),
          ?end_time: (Time | nil),
          ?id: (Integer | nil),
          ?meta: (Hash[String, String] | nil),
          ?metrics: (Hash[String, Float] | nil),
          ?metastruct: Hash[String | Symbol, untyped],
          ?parent_id: Integer,
          ?resource: String,
          ?service: (String | nil),
          ?start_time: (Time | nil),
          ?status: Integer,
          ?type: (String | nil),
          ?trace_id: (Integer | nil),
          ?service_entry: (bool | nil),
          ?links: (Array[untyped] | nil),
          ?events: (Array[untyped] | nil)
        ) -> void

      def started?: -> bool
      def stopped?: -> bool
      def duration: -> (Float | nil)
      def set_error: (Exception e) -> void
      def ==: (Span other) -> bool
      def to_s: -> String
      def to_hash: -> Hash[Symbol, untyped]
      def pretty_print: (PP q) -> void

      private

      def duration_nano: -> Integer?

      def service_entry?: -> bool

      def start_time_nano: -> Integer?
    end
  end
end
