module Datadog
  module Tracing
    module Utils
      extend Datadog::Core::Utils::Forking
      RUBY_MAX_ID: untyped
      RUBY_ID_RANGE: ::Range[::Integer]
      EXTERNAL_MAX_ID: untyped
      def self.next_id: () -> untyped

      def self.id_rng: () -> untyped

      def self.reset!: () -> untyped

      def self.serialize_attribute: (untyped key, untyped value) -> (untyped | ::Array[::Array[untyped]])

      module TraceId
        MAX: untyped
        def self?.next_id: () -> untyped

        def self?.to_high_order: (untyped trace_id) -> untyped

        def self?.to_low_order: (untyped trace_id) -> untyped

        def self?.concatenate: (untyped high_order, untyped low_order) -> untyped
      end
    end
  end
end