module Datadog
  module Tracing
    module Workers
      class AsyncTransport
        DEFAULT_BUFFER_MAX_SIZE: 1000

        DEFAULT_FLUSH_INTERVAL: 1

        DEFAULT_TIMEOUT: 5

        BACK_OFF_RATIO: ::Float

        BACK_OFF_MAX: 5

        SHUTDOWN_TIMEOUT: 1

        attr_reader trace_buffer: untyped

        def initialize: (?::Hash[untyped, untyped] options) -> void
        def callback_traces: () -> (true | untyped)
        def start: () -> untyped
        def stop: () -> (nil | true)
        def join: () -> untyped
        def enqueue_trace: (untyped trace) -> (nil | untyped)

        private

        alias flush_data callback_traces

        def perform: () -> untyped
      end
    end
  end
end
