module Datadog
  module DataStreams
    module Transport
      module HTTP
        module API
          V01: ::String

          def self?.defaults: () -> ::Hash[::String, Stats::API::Spec]
        end
      end
    end
  end
end
