module Datadog
  module AppSec
    module Contrib
      module Integration
        # NOTE: This is a workaround to allow a class metaclass to be used.
        #       In current RBS we can't point to the metaclass (self) directly and
        #       especially when usage comes from included/extended methods.
        type klass = ::Object

        class RegisteredIntegration < ::Struct[[::Symbol, klass, ::Hash[::Symbol, untyped]]]
          def self.new: (::Symbol name, klass klass, ::Hash[::Symbol, untyped] options) -> instance

          attr_accessor name: ::Symbol

          attr_accessor klass: klass

          attr_accessor options: ::Hash[::Symbol, untyped]
        end

        module ClassMethods
          def register_as: (::Symbol name, ?::Hash[::Symbol, untyped] options) -> void

          def compatible?: () -> bool
        end

        self.@registry: ::Hash[::Symbol, RegisteredIntegration]

        def self.included: (::Module base) -> void

        def self.register: (klass integration, ::Symbol name, ::Hash[::Symbol, untyped] options) -> RegisteredIntegration

        def self.registry: () -> ::Hash[::Symbol, RegisteredIntegration]
      end
    end
  end
end
