module Datadog
  module Tracing
    module Contrib
      module Sidekiq
        module Distributed
          class Propagation < Tracing::Distributed::Propagation
            def initialize: (
              propagation_style_inject: ::Array[::String],
              propagation_style_extract: ::Array[::String],
              propagation_extract_first: bool,
              propagation_behavior_extract: String
            ) -> void
          end
        end
      end
    end
  end
end
