module Datadog
  module Tracing
    module Contrib
      module Propagation
        module SqlComment
          class Mode < ::Struct[untyped]
            def initialize: (string mode, bool append) -> void

            def enabled?: -> bool
            def service?: -> bool
            def full?: -> bool
            def prepend?: -> bool
            def append?: -> bool
          end
        end
      end
    end
  end
end
