# All steps required to execute the `*.feature` files in this repository.
# The step declarations are automatically generated by `cucumber`.
# Only the body of each function has to be implemented.

Given("DD_SPAN_SAMPLING_RULES is set to") do |json_config|
  Datadog.configure do |c|
    c.sampling_rules json_config
  end
end

Given("a span for service {string} and name {string}") do |service, name|
  @name = name
  @service = service
end

When("I sample the span") do
  Datadog::Tracing.trace(@name, service: @service) do |span|
    @span = span # saves span for verification
    # User code would go here
  end
end

Then("the _dd.span_sampling metrics should be") do |expected_metrics|
  expected_metrics.each_line do |line|
    name, value = line.strip.split('=')
    expect(@span.get_metric(name)).to eq(Float(value))
  end
end

Given("the trace is dropped") do
  @trace.reject!
end

Given("the trace is kept") do
  @trace.keep!
end
