module Datadog
  module Tracing
    module Contrib
      module Rack
        module Ext
          ENV_ENABLED: ::String

          ENV_DISTRIBUTED_TRACING: ::String

          ENV_ANALYTICS_ENABLED: ::String

          ENV_ANALYTICS_SAMPLE_RATE: ::String

          RACK_ENV_REQUEST_SPAN: ::String

          SPAN_HTTP_PROXY_REQUEST: ::String

          SPAN_HTTP_PROXY_QUEUE: ::String

          SPAN_REQUEST: ::String

          TAG_COMPONENT: ::String

          TAG_COMPONENT_HTTP_PROXY: ::String

          TAG_OPERATION_REQUEST: ::String

          TAG_OPERATION_HTTP_PROXY_REQUEST: ::String

          TAG_OPERATION_HTTP_PROXY_QUEUE: ::String

          TAG_OPERATION_HTTP_SERVER_QUEUE: ::String

          WEBSERVER_APP: ::String

          DEFAULT_PEER_WEBSERVER_SERVICE_NAME: ::String

          HEADER_X_DD_PROXY: ::String

          HEADER_X_DD_PROXY_REQUEST_TIME_MS: ::String

          HEADER_X_DD_PROXY_PATH: ::String

          HEADER_X_DD_PROXY_RESOURCE_PATH: ::String

          HEADER_X_DD_PROXY_HTTPMETHOD: ::String

          HEADER_X_DD_PROXY_DOMAIN_NAME: ::String

          HEADER_X_DD_PROXY_STAGE: ::String

          HEADER_X_DD_PROXY_ACCOUNT_ID: ::String

          HEADER_X_DD_PROXY_API_ID: ::String

          HEADER_X_DD_PROXY_REGION: ::String

          HEADER_X_DD_PROXY_USER: ::String

          PROXY_AWS_APIGATEWAY: ::String

          PROXY_AWS_HTTPAPI: ::String

          SPAN_AWS_APIGATEWAY: ::String

          SPAN_AWS_HTTPAPI: ::String

          PROXY_SPAN_NAMES: Hash[::String, ::String]

          TAG_INFERRED_SPAN: ::String
        end
      end
    end
  end
end
