module Datadog
  module Tracing
    module Contrib
      module Rack
        module Header
          class RequestHeaderCollection < Datadog::Core::HeaderCollection
            def initialize: (::Rack::env env) -> void
            def get: (::String header_name) -> ::String?
            alias [] get
            def key?: (::String header_name) -> bool
          end

          def self.to_rack_header: (::String name) -> ::String
        end
      end
    end
  end
end
