module Datadog
  module Tracing
    module Transport
      module HTTP
        module API
          class Spec
            def initialize: () { (untyped) -> untyped } -> void
          end
        end
      end
    end
  end
end
