module Datadog
  module Core
    module Configuration
      module Assets
        type env_var = String
        type config_value = Hash[Symbol, Array[String]]

        type supported_config = Hash[env_var, config_value]
        type aliases = Hash[env_var, Array[env_var]]
        type deprecations = Hash[env_var, String]

        SUPPORTED_CONFIG_DATA: {
          supportedConfigurations: supported_config,
          aliases: aliases,
          deprecations: deprecations
        }
        ALIAS_TO_CANONICAL: Hash[env_var, env_var]
      end
    end
  end
end
