module Datadog
  module AppSec
    module Contrib
      module Rack
        class RequestMiddleware
          include ::Rack::Middleware

          attr_reader logger: untyped
        end
      end
    end
  end
end
