module Datadog
  module AppSec
    module Contrib
      module Rack
        class RequestBodyMiddleware
          @app: ::Rack::app

          def initialize: (::Rack::app app, ?::Hash[::Symbol, untyped] opt) -> void

          def call: (::Rack::env env) -> ::Rack::response
        end
      end
    end
  end
end
