module Datadog
  module AppSec
    module Contrib
      module Rack
        RESPONSE_HEADERS_TAGS: ::Array[::String]

        WAF_VENDOR_HEADERS_TAGS: ::Array[::String]

        class RequestMiddleware
          def initialize: (untyped app, ?::Hash[untyped, untyped] opt) -> untyped

          attr_reader logger: untyped

          def call: (untyped env) -> untyped
        end
      end
    end
  end
end
