module Datadog
  module AppSec
    module Contrib
      module Rack
        module Request
          def self.query: (untyped request) -> untyped

          def self.headers: (untyped request) -> untyped

          def self.body: (untyped request) -> untyped

          def self.url: (untyped request) -> untyped

          def self.cookies: (untyped request) -> untyped

          def self.form_hash: (untyped request) -> untyped

          def self.client_ip: (untyped request) -> (nil | untyped)
        end
      end
    end
  end
end
