module Datadog
  module Tracing
    module Contrib
      module Sequel
        module Utils
          type jdbc_metadata = { host: String?, port: String?, database: String? }

          MAX_JDBC_URI_BYTES: Integer
          JDBC_URI_PATTERN: Regexp
          DATABASE_PROPERTY_PATTERN: Regexp
          LIBRARIES_PROPERTY_PATTERN: Regexp
          RFC_3986_URI_DELIMITER_PATTERN: Regexp
          HOST_AND_PORT_PATTERN: Regexp

          def self.adapter_name: (untyped database) -> untyped
          def self.database_type: (untyped database) -> untyped

          def self.parse_jdbc_uri: (String uri) -> jdbc_metadata

          def self.parse_opts: (untyped sql, untyped opts, untyped db_opts, ?untyped? dataset) -> { name: untyped, query: untyped, prepared_name: untyped, database: untyped, host: untyped }

          def self.connection_metadata: (::Sequel::Database db) -> jdbc_metadata

          def self.set_common_tags: (untyped span, untyped db) -> untyped

          private

          def self.jdbc_metadata_from_connection: (::Sequel::Database db) -> jdbc_metadata?

          def self.host_and_port_from_authority: (String authority) -> [String, String?]?

          def self.database_from_path: (String? path) -> String?

          def self.database_from_properties: (String? properties) -> String?

          def self.datadog_configuration: () -> untyped

          def self.analytics_enabled?: () -> untyped

          def self.analytics_sample_rate: () -> untyped
        end
      end
    end
  end
end
