module Datadog
  module Security
    module Contrib
      module Configuration
        class Settings
          include Datadog::Configuration::Base

          # through Datadog::Configuration::Base
          include Datadog::Core::Environment::VariableHelpers
          extend Datadog::Core::Environment::VariableHelpers
          extend Datadog::Configuration::Options::ClassMethods
        end
      end
    end
  end
end
