module Datadog
  module Tracing
    module Contrib
      module Hanami
        class ActionTracer
          @app: ::Rack::app
          # TODO: Replace with Hanami::Action once we add a Hanami RBS stub.
          @action: untyped

          def initialize: (::Rack::app app, untyped action) -> void

          def call: (::Rack::env env) -> ::Rack::response

          private

          def configuration: () -> untyped
        end
      end
    end
  end
end
