module Datadog
  module Tracing
    module Contrib
      module Hanami
        module RouterTracing
          def call: (::Rack::env env) -> ::Rack::response

          def configuration: () -> untyped
        end
      end
    end
  end
end
