module Datadog
  module AppSec
    module Contrib
      module Devise
        module Ext
          EVENT_LOGIN_SUCCESS: ::String

          EVENT_LOGIN_FAILURE: ::String

          EVENT_SIGNUP: ::String

          TAG_USR_ID: ::String

          TAG_SESSION_ID: ::String

          TAG_LOGIN_SUCCESS_TRACK: ::String

          TAG_LOGIN_SUCCESS_USR_LOGIN: ::String

          TAG_LOGIN_FAILURE_TRACK: ::String

          TAG_LOGIN_FAILURE_USR_LOGIN: ::String

          TAG_LOGIN_FAILURE_USR_EXISTS: ::String

          TAG_LOGIN_FAILURE_USR_ID: ::String

          TAG_SIGNUP_TRACK: ::String

          TAG_SIGNUP_USR_LOGIN: ::String

          TAG_SIGNUP_USR_ID: ::String

          TAG_DD_USR_ID: ::String

          TAG_DD_USR_LOGIN: ::String

          TAG_DD_LOGIN_SUCCESS_MODE: ::String

          TAG_DD_LOGIN_FAILURE_MODE: ::String

          TAG_DD_SIGNUP_MODE: ::String
        end
      end
    end
  end
end
