module Datadog
  module AppSec
    module Contrib
      module Devise
        module Patcher
          GUARD_ONCE_PER_APP: ::Hash[any, ::Datadog::Core::Utils::OnlyOnce]

          def self?.patched?: () -> bool?

          def self?.target_version: () -> ::Gem::Version?

          def self?.patch: () -> bool
        end
      end
    end
  end
end
