module Datadog
  module AppSec
    module Contrib
      module Devise
        AUTOMATED_USER_EVENT_TAGGING_BLOCK: untyped
        module AuthenticablePatch
          def validate: (untyped resource) ?{ () -> untyped } -> untyped
        end

        module ResgistrationControllerPatch
          def create: () -> untyped
        end

        module Patcher
          include Datadog::AppSec::Contrib::Patcher

          def self?.patched?: () -> untyped

          def self?.target_version: () -> untyped

          def self?.patch: () -> untyped

          def self?.patch_authenticable_strategy: () -> untyped

          def self?.patch_registration_controller: () -> untyped
        end
      end
    end
  end
end
