# Select base image
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Add gem
COPY . /vendor/dd-trace-rb

# Install dependencies
# Setup specific version of ddtrace, if specified.
ENV DD_DEMO_ENV_GEM_LOCAL_DDTRACE /vendor/dd-trace-rb

# Build the ddtrace profiling native extension
RUN cd /vendor/dd-trace-rb && bundle install && bundle exec rake compile

RUN bundle install
