require 'datadog/demo_env'

source 'https://rubygems.org' do
  gem 'puma'
  gem 'unicorn'
  gem 'rack'
  if RUBY_VERSION < '2.3'
    gem 'redis', '< 4.1.1' # 4.1.1 "claims" to support 2.2 but is actually broken
  else
    gem 'redis'
  end
  if RUBY_VERSION < '2.2'
    gem 'sidekiq', '< 5' # 5.0.3 checks for older Rubies and breaks, but does not declare it on the gemspec :(
  else
    gem 'sidekiq'
  end
  gem 'resque'
  gem 'rake'

  gem 'dogstatsd-ruby'
  gem 'google-protobuf'
  # Choose correct specs for 'ddtrace' demo environment
  gem 'ddtrace', *Datadog::DemoEnv.gem_spec('ddtrace')

  # Development
  gem 'pry-byebug'
  # gem 'pry-stack_explorer', platform: :ruby
  # gem 'rbtrace'
  # gem 'ruby-prof'

  gem 'rspec'
  gem 'rspec-wait'
  gem 'webrick' if RUBY_VERSION >= '2.3' # Older Rubies can just use the built-in version of webrick
end
