require 'datadog/demo_env'

source "https://rubygems.org"

gem 'puma'
gem 'unicorn'
gem 'passenger'
gem 'rack'
gem 'rackup' if RUBY_VERSION >= '2.4'  # The `rackup` is its own gem since Rack 3.0

if RUBY_VERSION < '2.3'
  gem 'redis', '< 4.1.1' # 4.1.1 "claims" to support 2.2 but is actually broken
else
  # Known compatibility issue: https://github.com/redis/redis-rb/issues/1142
  gem 'redis', '< 5'
end
if RUBY_VERSION < '2.2'
  gem 'sidekiq', '< 5' # 5.0.3 checks for older Rubies and breaks, but does not declare it on the gemspec :(
else
  gem 'sidekiq'
end
gem 'resque'
gem 'rake'

gem 'dogstatsd-ruby'
# Choose correct specs for 'datadog' demo environment
gem 'datadog', *Datadog::DemoEnv.gem_spec('datadog')

# Needed for datadog profiling
google_protobuf_versions = [
  '~> 3.0',
  '!= 3.7.0.rc.2',
  '!= 3.7.0.rc.3',
  '!= 3.7.0',
  '!= 3.7.1',
  '!= 3.8.0.rc.1',
  '!= 3.24.0.rc.1',
]
if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.4')
  gem 'google-protobuf', *google_protobuf_versions
else
  # Bundler resolves incorrect version (too new, incompatible with Ruby <= 2.3)
  gem 'google-protobuf', *google_protobuf_versions, '< 3.19.2'
end

# Development
gem 'pry-byebug' if RUBY_VERSION >= '2.3.0' && RUBY_ENGINE != 'truffleruby' && RUBY_VERSION < '3.2.0'
gem 'pry-nav' if RUBY_VERSION < '2.3.0'
# gem 'pry-stack_explorer', platform: :ruby
# gem 'rbtrace'
# gem 'ruby-prof'

gem 'rspec'
gem 'rspec-wait'
gem 'webrick' if RUBY_VERSION >= '2.3' # Older Rubies can just use the built-in version of webrick
