module Datadog
  module Security
    module Contrib
      module Rack
        class Integration
          include Datadog::Security::Contrib::Integration

          # through Datadog::Security::Contrib::Integration
          extend Datadog::Security::Contrib::Integration::ClassMethods

          MINIMUM_VERSION: untyped

          def self.version: () -> untyped

          def self.loaded?: () -> bool

          def self.compatible?: () -> bool

          def auto_instrument?: () -> bool

          def default_configuration: () -> untyped

          def patcher: () -> untyped
        end
      end
    end
  end
end
