module Datadog
  module AppSec
    module Contrib
      module RestClient
        module RequestSSRFDetectionPatch : ::RestClient::Request
          REDIRECT_STATUS_CODES: Range[Integer]

          type headers = ::Hash[String, String]

          def execute: () ?{ (*untyped) -> untyped } -> ::RestClient::Response

          def process_response: (::RestClient::Response response, sample_body: bool) -> void

          private

          def mark_body_sampling!: (Context context) -> bool

          def parse_request_body: (::RestClient::Payload::Base? body, content_type: String?) -> Datadog::Helpers::json?

          def parse_response_body: (Utils::HTTP::Body::body body, headers: headers, context: Context) -> Datadog::Helpers::json?

          def readable_body?: (Utils::HTTP::Body::body body) -> bool

          def read_body: (::RestClient::Payload::Base? body, limit: Integer) -> String?
                       | (Utils::HTTP::Body::body body, limit: Integer) -> String?

          def normalize_request_headers: () -> headers

          def normalize_response_headers: (::RestClient::Response response) -> headers

          def handle: (SecurityEngine::result result, context: Context) -> void
        end
      end
    end
  end
end
