module Datadog
  module AppSec
    module Contrib
      module RestClient
        module RequestSSRFDetectionPatch : ::RestClient::Request
          type headers = ::Hash[::String, ::String]

          def execute: () ?{ (*untyped) -> untyped } -> ::RestClient::Response

          private

          def mark_body_sampling!: (Context context) -> bool

          def parse_body: (::String body, content_type: ::String?) -> ::Helpers::json?

          def normalize_request_headers: () -> headers

          def normalize_response_headers: (::RestClient::Response response) -> headers

          def handle: (SecurityEngine::result result, context: Context) -> void
        end
      end
    end
  end
end
