module Datadog
  module Configuration
    class OptionDefinition
      IDENTITY: untyped

      attr_reader default: untyped

      attr_reader delegate_to: untyped

      attr_reader depends_on: untyped

      attr_reader lazy: untyped

      attr_reader name: untyped

      attr_reader on_set: untyped

      attr_reader resetter: untyped

      attr_reader setter: untyped

      def initialize: (untyped name, ?::Hash[untyped, untyped] meta) { () -> untyped } -> untyped

      def build: (untyped context) -> untyped

      class Builder
        attr_reader helpers: untyped

        def initialize: (untyped name, ?::Hash[untyped, untyped] options) { (untyped) -> untyped } -> untyped

        def depends_on: (*untyped values) -> untyped

        def default: (?untyped? value) { () -> untyped } -> untyped

        def delegate_to: () { () -> untyped } -> untyped

        def helper: (untyped name, *untyped _args) { () -> untyped } -> untyped

        def lazy: (?bool value) -> untyped

        def on_set: () { () -> untyped } -> untyped

        def resetter: () { () -> untyped } -> untyped

        def setter: () { () -> untyped } -> untyped

        def apply_options!: (?::Hash[untyped, untyped] options) -> (nil | untyped)

        def to_definition: () -> untyped

        def meta: () -> { default: untyped, delegate_to: untyped, depends_on: untyped, lazy: untyped, on_set: untyped, resetter: untyped, setter: untyped }
      end
    end
  end
end
