module Datadog
  module Configuration
    class Settings
      include Base

      def initialize: (*untyped _) -> untyped

      def logger=: (untyped logger) -> untyped

      def runtime_metrics: (?untyped? options) -> untyped

      def tracer: (?untyped? options) -> untyped

      def tracer=: (untyped tracer) -> untyped
    end
  end
end
