module Datadog
  module DataStreams
    module Transport
      module Stats
        class EncodedParcel
          include Core::Transport::Parcel

          @data: ::String

          attr_reader data: ::String

          def initialize: (::String data) -> void
        end

        class Request < Core::Transport::Request
        end

        class Transport < Core::Transport::Transport
          def send_stats: (::Hash[::String, untyped] payload) -> (Core::Transport::HTTP::Response | Core::Transport::InternalErrorResponse)
        end
      end
    end
  end
end
