module Datadog
  module Tracing
    module Contrib
      module Sidekiq
        module ServerInternalTracer
          module ScheduledPoller
            def enqueue: () -> untyped

            private

            def wait: () -> untyped
          end
        end
      end
    end
  end
end
