module Datadog
  module AppSec
    module APISecurity
      module RouteExtractor
        SINATRA_ROUTE_KEY: String

        SINATRA_ROUTE_SEPARATOR: String

        GRAPE_ROUTE_KEY: String

        RAILS_ROUTE_KEY: String

        RAILS_ROUTE_URI_PATTERN_KEY: String

        RAILS_ROUTES_KEY: String

        RAILS_PATH_PARAMS_KEY: String

        RAILS_FORMAT_SUFFIX: String

        def self.route_pattern: (APISecurity::_Request request) -> String?
      end
    end
  end
end
