module Datadog
  module AppSec
    module Contrib
      module Rails
        module Request
          def self.parsed_body: (untyped request) -> ::Hash[::String, untyped]?

          def self.route_params: (untyped request) -> ::Hash[::Symbol, untyped]
        end
      end
    end
  end
end
