module Datadog
  module AIGuard
    module Contrib
      module RubyLLM
        module ChatInstrumentation : RubyLLM::Chat
          private

          def handle_tool_calls: (::RubyLLM::Message response) ?{ () -> untyped } -> (::RubyLLM::Message | ::RubyLLM::Tool::Halt)
        end
      end
    end
  end
end
