module Datadog
  module AIGuard
    module Contrib
      module RubyLLM
        module ChatInstrumentation
          def self.evaluate: (::Array[::RubyLLM::Message] messages) -> (AIGuard::Evaluation::Result | AIGuard::Evaluation::NoOpResult)

          def complete: () ?{ () -> untyped } -> untyped

          def handle_tool_calls: (untyped response) ?{ () -> untyped } -> untyped

          def messages: () -> ::Array[::RubyLLM::Message]
        end
      end
    end
  end
end
