module Datadog
  module AIGuard
    module Contrib
      module RubyLLM
        module MessageRedactor
          def self?.redact: (
            Array[::RubyLLM::Message] messages,
            with: Array[Evaluation::Message]
          ) -> Array[::RubyLLM::Message]
        end
      end
    end
  end
end
