module Datadog
  module AIGuard
    module Contrib
      module RubyLLM
        module ProviderInstrumentation : ::RubyLLM::Provider
          def complete: (Array[::RubyLLM::Message] messages, **untyped options) ?{ (untyped chunk) -> untyped } -> ::RubyLLM::Message
        end
      end
    end
  end
end
