module Datadog
  module Core
    module Telemetry
      module Event
        class AppStarted < Base
          def initialize: (components: Datadog::Core::Configuration::Components) -> void

          def type: () -> "app-started"

          def payload: () -> { products: untyped, configuration: untyped, install_signature: untyped }
	  
          def app_started?: -> bool

          private

          def products: (Datadog::Core::Configuration::Components components) -> Hash[Symbol, Hash[Symbol, Hash[Symbol, String | Integer] | bool | nil]]

          TARGET_OPTIONS: Array[String]
          def configuration: (untyped settings, Core::Configuration::AgentSettings agent_settings) -> Array[Hash[Symbol, untyped]]

          def agent_transport: (Core::Configuration::AgentSettings agent_settings) -> String

          def conf_value: (String name, untyped value, Integer seq_id, String origin) -> Hash[Symbol, untyped]

          def to_value: (Object value) -> Object

          def install_signature: (untyped settings) -> Hash[Symbol, Object]

          def get_telemetry_origin: (untyped settings, String config_path) -> String
        end
      end
    end
  end
end
