module Datadog
  module Core
    module Telemetry
      module Event
        class AppDependenciesLoaded < Base
          type dependency = Hash[Symbol, String]

          def type: () -> "app-dependencies-loaded"

          def payload: () -> { dependencies: Array[dependency] }

          private

          def dependencies: -> Array[dependency]
        end
      end
    end
  end
end
