module Datadog
  module Core
    module Telemetry
      module Event
        class AppEndpointsLoaded < Base
          type endpoint = {
            type: String,
            resource_name: String,
            operation_name: String,
            method: String,
            path: String
          }

          @endpoints: Array[endpoint]
          @is_first: bool

          def initialize: (Array[endpoint] endpoints, is_first: bool) -> void

          def type: () -> "app-endpoints"

          def payload: () -> Hash[Symbol, bool | Array[endpoint]]
        end
      end
    end
  end
end
