module Datadog
  module Core
    module Telemetry
      class Event
        class AppIntegrationsChange < Base
          def type: () -> "app-integrations-change"

          def payload: () -> { integrations: untyped }

          private

          def integrations: () -> untyped

          def patch_error: (untyped integration) -> (untyped | ::String)
        end
      end
    end
  end
end
