module Datadog
  module Core
    module Telemetry
      module Event
        class AppStarted < Base
          type install_signature = {
            install_id: ::String?,
            install_type: ::String?,
            install_time: ::String?
          }

          type telemetry_products = {
            appsec: {
              enabled: bool
            },
            profiler: {
              enabled: bool,
              ?error: {
                code: ::Integer,
                message: ::String?
              }
            },
            dynamic_instrumentation: {
              enabled: bool
            }
          }

          @configuration: ::Array[telemetry_configuration]
          @install_signature: install_signature
          @products: telemetry_products

          def initialize: (components: Datadog::Core::Configuration::Components) -> void

          def type: () -> "app-started"

          def current_configuration: () -> ::Array[telemetry_configuration]

          def payload: () -> { products: untyped, configuration: untyped, install_signature: untyped }

          def app_started?: -> bool?

          private
          TARGET_OPTIONS: ::Array[::String]

          def products: (Datadog::Core::Configuration::Components components) -> telemetry_products

          def configuration: (untyped settings, Core::Configuration::AgentSettings agent_settings) -> ::Array[telemetry_configuration]

          def agent_transport: (Core::Configuration::AgentSettings agent_settings) -> String

          def conf_value: (::String name, telemetry_value value, Configuration::Option::Precedence::Value precedence) -> telemetry_configuration

          def unknown_conf_value: (::String name, telemetry_value value) -> telemetry_configuration

          def build_conf_value: (::String name, telemetry_value value, ::String origin, ::Integer seq_id) -> telemetry_configuration

          def to_telemetry_value: (any value) -> telemetry_value

          def install_signature: (untyped settings) -> install_signature

          def get_telemetry_payload: (untyped settings, ::String config_path) -> ::Array[telemetry_configuration]

          def option_telemetry_name: (Configuration::Option option) -> ::String

          def resolve_option: (untyped settings, ::String config_path) -> Configuration::Option
        end
      end
    end
  end
end
