module Datadog
  module Core
    module Telemetry
      module Event
        class AppExtendedHeartbeat < AppStarted
          @configuration: ::Array[telemetry_configuration]

          def initialize: (settings: untyped, agent_settings: Core::Configuration::AgentSettings) -> void
          def type: () -> "app-extended-heartbeat"
          def payload: () -> { configuration: ::Array[telemetry_configuration] }
          def app_started?: () -> false
        end
      end
    end
  end
end
