module Datadog
  module Core
    module Telemetry
      module Event
        class Base
          def payload: () -> (Hash[Symbol, untyped] | Array[Hash[Symbol, untyped]])
          def type: -> String
          def ==: (untyped other) -> untyped
          alias eql? ==
          def hash: () -> untyped
        end
      end
    end
  end
end
