module Datadog
  module Core
    module Telemetry
      module Event
        module ConfigurationValue
          def self.convert: (any value) -> telemetry_value
        end
      end
    end
  end
end
