module Datadog
  module Core
    module Telemetry
      class Event
        class GenerateMetrics < Base
          @namespace: untyped

          @metric_series: untyped

          attr_reader namespace: untyped

          attr_reader metric_series: untyped

          def type: () -> "generate-metrics"

          def initialize: (untyped namespace, untyped metric_series) -> void

          def payload: () -> { namespace: untyped, series: untyped }

          def ==: (untyped other) -> untyped

          alias eql? ==

          def hash: () -> untyped
        end
      end
    end
  end
end
