module Datadog
  module Core
    module Telemetry
      module Event
        class SynthAppClientConfigurationChange < AppStarted
          def type: -> ("app-client-configuration-change" | "app-started")

          def payload: () -> { ?products: untyped, configuration: untyped, ?install_signature: untyped }

          def reset?: -> bool

          def reset!: -> void
        end
      end
    end
  end
end
