module Datadog
  module Kit
    module Events
      def self.track_login: (Datadog::Tracing::TraceOperation trace, success: bool, user: Hash[::Symbol, ::String | nil], **::Hash[::Symbol, ::String | nil] others) -> void

      def self.track: (::String | ::Symbol event, Datadog::Tracing::TraceOperation trace, **::Hash[::Symbol, ::String | nil] others) -> void
    end
  end
end
