module Datadog
  module Tracing
    module Contrib
      module Racecar
        module Patcher
          include Contrib::Patcher

          def self?.target_version: () -> untyped

          def self?.patch: () -> void

          def self?.patch_consumer: () -> void

          def self?.patch_producer: () -> void
        end
      end
    end
  end
end
