module Datadog
  module Core
    module Native
      class RuntimeError < ::RuntimeError
      end

      class ArgumentError < ::ArgumentError
      end

      class TypeError < ::TypeError
      end
    end
  end
end
