module Datadog
  module Tracing
    module Contrib
      module Sinatra
        class TracerMiddleware
          @app: ::Rack::app

          def initialize: (::Rack::app app, ?::Hash[::Symbol, untyped] opt) -> void
          def call: (::Rack::env env) -> ::Rack::response

          private

          def analytics_enabled?: () -> untyped

          def analytics_sample_rate: () -> untyped

          def configuration: () -> untyped
        end
      end
    end
  end
end
