module Datadog
  module Tracing
    module Contrib
      module Configuration
        class Resolver[Matcher, Key, Config]
          attr_reader configurations: Hash[Key, Config]

          def initialize: () -> void
          def add: (Matcher matcher, Config value) -> Config?
          def get: (Matcher matcher) -> Config?
          def resolve: (Key value) -> Config?
          def parse_matcher: (Matcher matcher) -> Key
          def ordered_config: () -> Array[[Key, Config]]
        end
      end
    end
  end
end
