module Datadog
  module AppSec
    module Contrib
      module Rails
        module Reactive
          module Action
            def self.publish: (untyped op, untyped request) -> untyped

            def self.subscribe: (untyped op, untyped waf_context) { (untyped) -> untyped } -> untyped
          end
        end
      end
    end
  end
end
