module Datadog
  module AppSec
    module Contrib
      module Rails
        module Reactive
          module Action
            ADDRESSES: ::Array[::String]

            def self.publish: (AppSec::Reactive::Engine engine, AppSec::Contrib::Rails::Gateway::Request request) -> untyped

            def self.subscribe: (AppSec::Reactive::Engine engine, untyped waf_context) { (untyped) -> untyped } -> untyped
          end
        end
      end
    end
  end
end
