module Datadog
  module DI
    class CaptureExpression
      @name: String
      @expr: DI::EL::Expression
      @limits: CaptureLimits?

      def initialize: (name: String, expr: DI::EL::Expression, ?limits: CaptureLimits?) -> void

      attr_reader name: String
      attr_reader expr: DI::EL::Expression
      attr_reader limits: CaptureLimits?
    end

    class CaptureLimits
      @max_reference_depth: Integer?
      @max_collection_size: Integer?
      @max_length: Integer?
      @max_field_count: Integer?

      def initialize: (?max_reference_depth: Integer?, ?max_collection_size: Integer?, ?max_length: Integer?, ?max_field_count: Integer?) -> void

      attr_reader max_reference_depth: Integer?
      attr_reader max_collection_size: Integer?
      attr_reader max_length: Integer?
      attr_reader max_field_count: Integer?

      def self.resolve: (expr_limits: CaptureLimits?, probe: Probe, settings: untyped) -> Hash[Symbol, Integer]
    end
  end
end
