module Datadog
  module DI
    class Context
      @probe: Probe

      @settings: Datadog::Core::Configuration::Settings

      @serializer: Serializer

      @locals: Hash[Symbol, any]?

      @target_self: any

      @path: String?

      @caller_locations: Array[Thread::Backtrace::Location]?

      @serialized_entry_args: Hash[Symbol, any]?

      @entry_capture_expressions: Hash[String, any]?
      @entry_capture_evaluation_errors: Array[Hash[Symbol, String]]?

      @return_value: any

      @duration: Float?

      @exception: Exception?

      def initialize: (probe: Probe, settings: Datadog::Core::Configuration::Settings, serializer: Serializer, ?locals: Hash[Symbol, any]?, ?target_self: any?, ?path: String?, ?caller_locations: Array[Thread::Backtrace::Location]?, ?serialized_entry_args: Hash[Symbol, any]?, ?entry_capture_expressions: Hash[String, any]?, ?entry_capture_evaluation_errors: Array[Hash[Symbol, String]]?, ?return_value: any?, ?duration: Float?, ?exception: Exception?) -> void

      attr_reader probe: Probe

      attr_reader settings: Datadog::Core::Configuration::Settings

      attr_reader serializer: Serializer

      attr_reader locals: Hash[Symbol, any]?

      attr_reader target_self: any
      attr_reader path: String?
      attr_reader caller_locations: Array[Thread::Backtrace::Location]?

      attr_reader serialized_entry_args: Hash[Symbol, any]?
      attr_reader entry_capture_expressions: Hash[String, any]?
      attr_reader entry_capture_evaluation_errors: Array[Hash[Symbol, String]]?
      attr_reader return_value: any
      attr_reader duration: Float?
      attr_reader exception: Exception?

      def serialized_locals: () -> Hash[Symbol, any]?

      def fetch: ((Symbol | String) var_name) -> any

      def fetch_ivar: ((Symbol | String) var_name) -> any
    end
  end
end
