module Datadog
  module DI
    class Correlation
      DEFAULT_MAX_ENTRIES: Integer

      @max_entries: Integer

      @lock: ::Thread::Mutex

      @sampling_unit_decisions: Hash[Integer, bool]

      @cap_scopes: Hash[Integer, Set[String]]

      def initialize: (?max_entries: Integer) -> void

      def emit?: (Probe probe, SamplingUnit sampling_unit) -> bool

      private

      attr_reader lock: ::Thread::Mutex

      attr_reader sampling_unit_decisions: Hash[Integer, bool]

      attr_reader cap_scopes: Hash[Integer, Set[String]]

      attr_reader max_entries: Integer

      def per_probe: (Probe probe) -> bool

      def sampling_unit_decision: (Integer key) { () -> bool } -> bool

      def cap_admit: (Integer scope, String probe_id) -> bool

      def evict: [K, V] (Hash[K, V] map) -> void
    end
  end
end
