module Datadog
  module DI
    class Error < StandardError
      class InternalError < Error
      end
      class MissingLineNumber < Error
      end
      class AgentCommunicationError < Error
      end
      class DITargetNotDefined < Error
      end
      class DITargetNotInRegistry < Error
      end
      class ProbePreviouslyFailed < Error
      end
      class MultiplePathsMatch < Error
      end
      class InvalidExpression < Error
      end
      class BadVariableName < InvalidExpression
      end
      class ExpressionEvaluationError < Error
      end
    end
  end
end
