module Datadog
  module DI
    class ExecutionUnit
      @key: Integer?

      @scope: Integer?

      @source: Symbol

      def self.current: () -> ExecutionUnit

      def initialize: (Integer? key, Integer? scope, Symbol source) -> void

      attr_reader key: Integer?

      attr_reader scope: Integer?

      attr_reader source: Symbol
    end
  end
end
