module Datadog
  module DI
    class ExecutionUnit
      @key: untyped

      @scope: untyped

      @source: Symbol

      def self.current: () -> ExecutionUnit

      def initialize: (untyped key, untyped scope, Symbol source) -> void

      attr_reader key: untyped

      attr_reader scope: untyped

      attr_reader source: Symbol
    end
  end
end
