module Datadog
  module DI
    class GuardrailsTelemetry
      PROBE_TYPE_SNAPSHOT: String

      PROBE_TYPE_LOG: String

      EVENT_TYPE_SNAPSHOT: String

      EVENT_TYPE_LOG: String

      EVENT_TYPE_DIAGNOSTIC: String

      @telemetry: Core::Telemetry::Component?

      @skipped_tags: Hash[String, Hash[String, Hash[Symbol, String]]]

      def initialize: (telemetry: Core::Telemetry::Component?) -> void

      attr_reader telemetry: Core::Telemetry::Component?

      def self.probe_type_tag: (Probe probe) -> String

      def self.event_type_tag: (Symbol event_type) -> String

      def skipped: (reason: String, probe_type: String) -> void

      def dropped: (reason: String, event_type: String, ?bytes: Integer?) -> void

      private

      def skipped_tags: (String reason, String probe_type) -> Hash[Symbol, String]
    end
  end
end
