module Datadog
  module DI
    class GuardrailsTelemetry
      PROBE_TYPE_SNAPSHOT: String

      PROBE_TYPE_LOG: String

      EVENT_TYPE_SNAPSHOT: String

      EVENT_TYPE_DIAGNOSTIC: String

      @settings: Datadog::Core::Configuration::Settings

      @logger: DI::Logger

      @telemetry: Core::Telemetry::Component?

      @skipped_tags_memo: Hash[String, Hash[String, Hash[Symbol, String]]]

      @dropped_tags_memo: Hash[String, Hash[String, Hash[Symbol, String]]]

      def initialize: (settings: Datadog::Core::Configuration::Settings, logger: DI::Logger, telemetry: Core::Telemetry::Component?) -> void

      attr_reader settings: Datadog::Core::Configuration::Settings

      attr_reader logger: DI::Logger

      attr_reader telemetry: Core::Telemetry::Component?

      attr_reader skipped_tags_memo: Hash[String, Hash[String, Hash[Symbol, String]]]

      attr_reader dropped_tags_memo: Hash[String, Hash[String, Hash[Symbol, String]]]

      def self.probe_type_tag: (Probe probe) -> String

      def self.event_type_tag: (Symbol event_type) -> String

      def skipped: (reason: String, probe: Probe) -> void

      def dropped: (reason: String, event_type: String, ?bytes: Integer?) -> void

      private

      def inc_guardrails_metric: (String metric_name, Integer value, tags: Hash[Symbol, String]) -> void

      def report_emission_failure: (String metric_name, Exception exc) -> void

      def skipped_tags: (String reason, String probe_type) -> Hash[Symbol, String]

      def dropped_tags: (String reason, String event_type) -> Hash[Symbol, String]
    end
  end
end
