module Datadog
  module DI
    class Logger
      extend Forwardable

      @settings: Datadog::Core::Configuration::Settings

      @target: ::Logger

      def initialize: (Datadog::Core::Configuration::Settings settings, ::Logger target) -> void

      attr_reader settings: Datadog::Core::Configuration::Settings

      attr_reader target: ::Logger

      def debug: () { (?) -> untyped } -> void
      def trace: () { (?) -> untyped } -> void
    end
  end
end
