module Datadog
  module DI
    class Logger
      @trace_logging: bool

      @target: ::Logger

      def initialize: (Datadog::Core::Configuration::Settings settings, ::Logger target) -> void

      attr_reader trace_logging: bool

      attr_reader target: ::Logger

      def debug: () { () -> String } -> void
      def trace: () { () -> String } -> void
    end
  end
end
