module Datadog
  module DI
    class ProbeManager
      @settings: Datadog::Core::Configuration::Settings

      @instrumenter: Instrumenter

      @probe_notification_builder: ProbeNotificationBuilder

      @probe_notifier_worker: ProbeNotifierWorker

      @logger: DI::Logger

      @telemetry: Core::Telemetry::Component?

      @probe_repository: ProbeRepository

      @definition_trace_point: TracePoint

      def initialize: (Datadog::Core::Configuration::Settings settings, Instrumenter instrumenter, ProbeNotificationBuilder probe_notification_builder, ProbeNotifierWorker probe_notifier_worker, DI::Logger logger, ProbeRepository probe_repository, ?telemetry: Core::Telemetry::Component?) -> void

      attr_reader logger: DI::Logger

      attr_reader telemetry: Core::Telemetry::Component?

      attr_reader probe_repository: ProbeRepository

      def stop: () -> void

      def reopen: () -> void

      def close: () -> void

      def clear_hooks: () -> void

      attr_reader settings: Datadog::Core::Configuration::Settings

      attr_reader instrumenter: Instrumenter

      attr_reader probe_notification_builder: ProbeNotificationBuilder

      attr_reader probe_notifier_worker: ProbeNotifierWorker

      def add_probe: (Probe probe) -> bool

      def remove_probe: (String probe_id) -> void

      private
      def install_pending_method_probes: (Module cls) -> void

      public
      def install_pending_line_probes: (String? path) -> void

      def probe_executed_callback: (Context context) -> void

      def probe_condition_evaluation_failed_callback: (Context context, EL::Expression expr, Exception exc) -> void

      def probe_disabled_callback: (Probe probe, Float duration) -> void

      attr_reader definition_trace_point: TracePoint
    end
  end
end
