module Datadog
  module DI
    class ProbeManager
      @settings: untyped

      @instrumenter: untyped

      @probe_notification_builder: untyped

      @probe_notifier_worker: untyped

      @logger: untyped

      @telemetry: untyped

      @installed_probes: untyped

      @pending_probes: untyped

      @failed_probes: untyped

      @lock: untyped

      @definition_trace_point: untyped

      def initialize: (untyped settings, untyped instrumenter, untyped probe_notification_builder, untyped probe_notifier_worker, untyped logger, ?telemetry: untyped?) -> void

      attr_reader logger: untyped

      attr_reader telemetry: untyped
      def close: () -> untyped

      def clear_hooks: () -> untyped

      attr_reader settings: untyped

      attr_reader instrumenter: untyped

      attr_reader probe_notification_builder: untyped

      attr_reader probe_notifier_worker: untyped

      def installed_probes: () -> untyped

      def pending_probes: () -> untyped
      def failed_probes: () -> untyped
      def add_probe: (untyped probe) -> untyped

      private
      def do_add_probe: (untyped probe) -> untyped

      public
      def remove_other_probes: (untyped probe_ids) -> untyped

      private
      def install_pending_method_probes: (untyped cls) -> untyped

      public
      def install_pending_line_probes: (untyped path) -> untyped
      def probe_executed_callback: (probe: untyped, **untyped opts) -> untyped
      attr_reader definition_trace_point: untyped
    end
  end
end
