module Datadog
  module DI
    class ProbeNotificationBuilder
      NANOSECONDS: Integer
      MILLISECONDS: Integer
      
      @serializer: Serializer

      def initialize: (untyped settings, Serializer serializer) -> void

      attr_reader settings: untyped
      attr_reader serializer: Serializer

      def build_received: (Probe probe) -> Hash[Symbol,untyped]

      def build_installed: (Probe probe) -> Hash[Symbol,untyped]

      def build_emitting: (Probe probe) -> Hash[Symbol,untyped]

      def build_errored: (Probe probe, Exception exception) -> Hash[Symbol,untyped]

      def build_executed: (Context context) -> Hash[Symbol,untyped]

      def build_snapshot: (Context context) -> Hash[Symbol,untyped]
      def build_snapshot_base: (Context context, ?evaluation_errors: Array[untyped]?, ?captures: untyped?, ?message: String?) -> Hash[Symbol,untyped]

      def build_condition_evaluation_failed: (Context context, untyped expr, untyped exception) -> Hash[Symbol,untyped]

      def build_status: (Probe probe, message: untyped, status: untyped) -> Hash[Symbol,untyped]

      def format_caller_locations: (Array[untyped] callers) -> Array[Hash[Symbol,untyped]]

      def evaluate_template: (untyped template, Context context) -> [String, Array[String]]

      def tag_process_tags!: (Hash[Symbol | String, untyped] payload, Core::Configuration::Settings settings) -> void

      def timestamp_now: () -> Integer

      def get_local_variables: (TracePoint trace_point) -> Hash[Symbol,untyped]
      
      def active_trace: () -> Datadog::Tracing::TraceSegment?
      def active_span: () -> Datadog::Tracing::SpanOperation?

      def tags: () -> untyped
      
      def serialized_tags: () -> untyped
    end
  end
end
