module Datadog
  module DI
    module ProbeBuilder
      PROBE_TYPES: { "LOG_PROBE" => :log }

      CAPTURE_EXPRESSION_NAME_PATTERN: Regexp

      EVALUATE_AT_STRINGS: Hash[String, Symbol]

      def self?.build_from_remote_config: (Hash[String, any] config, logger: DI::Logger) -> Probe

      def self?.build_template_segments: (Array[Hash[String, any]]? segments) -> Array[String | DI::EL::Expression]?

      def self?.build_capture_expressions: (Array[Hash[String, any]]? raw) -> Array[CaptureExpression]

      def self?.dedup_capture_expressions: (Array[CaptureExpression] capture_expressions, String? probe_id, DI::Logger logger) -> Array[CaptureExpression]

      def self?.build_capture_limits: (Hash[String, any]? raw) -> CaptureLimits?

      def self?.parse_evaluate_at: (String? raw, String? probe_id, DI::Logger logger) -> Symbol
    end
  end
end
