module Datadog
  module DI
    class ProcResponder
      @executed_proc: Proc

      @failed_proc: Proc?

      def initialize: (Proc executed_proc, ?Proc? failed_proc) -> void

      attr_reader executed_proc: Proc

      attr_reader failed_proc: Proc?

      def probe_executed_callback: (Context context) -> any

      def probe_condition_evaluation_failed_callback: (Context context, Exception exc) -> any

      def probe_disabled_callback: (Probe probe, Float duration) -> void
    end
  end
end
