module Datadog
  module DI
    module Remote
      PRODUCT: "LIVE_DEBUGGING"

      def self.products: () -> ::Array[String]

      def self.capabilities: () -> ::Array[Integer]

      def self.handle_rc_enablement: (bool enabled) -> void

      def self.explicitly_disabled?: () -> bool

      def self.receivers: (Core::Telemetry::Component? telemetry) -> ::Array[Core::Remote::Dispatcher::Receiver]

      def self.receiver: (?::Array[String] products) { (Core::Remote::Configuration::Repository, ::Array[Core::Remote::Configuration::Repository::change]) -> void } -> ::Array[Core::Remote::Dispatcher::Receiver]

      private

      def self.parse_content: (untyped content) -> Hash[String, untyped]

      def self.add_probe: (untyped content, Component component) -> void
      def self.remove_probe: (untyped previous_content, Component component) -> void
    end
  end
end
