module Datadog
  module DI
    module Remote
      PRODUCT: "LIVE_DEBUGGING"

      def self.products: () -> ::Array[untyped]

      def self.capabilities: () -> ::Array[untyped]

      def self.receivers: (untyped telemetry) -> untyped

      def self.receiver: (?::Array[untyped] products) { (?) -> untyped } -> ::Array[untyped]

      private

      def self.parse_content: (untyped content) -> untyped
      
      def self.add_probe: (untyped content, untyped component) -> void
      def self.remove_probe: (untyped previous_content, untyped component) -> void
    end
  end
end
