module Datadog
  module DI
    class SamplingUnit
      @key: Integer?

      def self.current: () -> SamplingUnit

      def initialize: (Integer? key) -> void

      attr_reader key: Integer?
    end
  end
end
