module Datadog
  module DI
    class Serializer
      @settings: untyped

      @redactor: untyped

      def initialize: (untyped settings, untyped redactor) -> void

      attr_reader settings: Datadog::Core::Configuration::Settings

      attr_reader redactor: Datadog::DI::Redactor
      
      def serialize_args: (untyped args, untyped kwargs) -> untyped
      def serialize_vars: (untyped vars) -> untyped
      def serialize_value: (untyped value, ?name: String, ?depth: Integer) -> untyped

      private
      def class_name: (untyped cls) -> untyped
    end
  end
end
