module Datadog
  module DI
    class Serializer
      MAX_MESSAGE_COLLECTION_SIZE: Integer
      MAX_MESSAGE_ATTRIBUTE_COUNT: Integer
      SERIALIZABLE_FATAL_EXCEPTION_CLASSES: ::Array[singleton(::Exception)]

      @@flat_registry: ::Array[{condition: ::Proc?, proc: ^(Serializer serializer, untyped value, name: ::Symbol?, depth: ::Integer, ?attribute_count: ::Integer?) -> untyped}]

      @settings: Datadog::Core::Configuration::Settings

      @redactor: Redactor

      @telemetry: Core::Telemetry::Component?

      def initialize: (Datadog::Core::Configuration::Settings settings, Redactor redactor, ?telemetry: Core::Telemetry::Component?) -> void

      attr_reader settings: Datadog::Core::Configuration::Settings

      attr_reader redactor: Datadog::DI::Redactor

      attr_reader telemetry: Core::Telemetry::Component?

      def combine_args: (Array[untyped] args, Hash[Symbol, untyped] kwargs, untyped target_self) -> Hash[Symbol, untyped]
      def serialize_args: (Array[any] args, Hash[Symbol, any] kwargs, any instance_vars, ?depth: Integer, ?attribute_count: Integer?, ?length: Integer?, ?collection_size: Integer?) -> Hash[Symbol, any]
      def serialize_vars: (Hash[Symbol, any] vars, ?depth: Integer, ?attribute_count: Integer?, ?length: Integer?, ?collection_size: Integer?) -> Hash[Symbol, any]
      def serialize_value: (any value, ?name: (Symbol | String)?, ?depth: Integer, ?attribute_count: Integer?, ?length: Integer?, ?collection_size: Integer?, ?type: Class?) -> Hash[Symbol, any]
      def serialize_value_for_message: (untyped value, ?::Integer depth) -> String?

      def self.register: (?condition: Proc?) {
        (Serializer serializer, untyped value, name: ::Symbol?, depth: ::Integer, ?attribute_count: ::Integer?) -> untyped } -> void

      private
      def max_capture_collection_size_for_message: () -> Integer

      def max_capture_attribute_count_for_message: () -> Integer
      def class_name: (Class cls) -> String

      def serialize_string_or_symbol_for_message: (String | Symbol value) -> String?

      def escape_binary_string: (String binary_string) -> String
    end
  end
end
