module Datadog
  module Tracing
    module Transport
      class SerializableTrace
        @native_events_supported: bool

        attr_reader trace: TraceSegment

        def initialize: (untyped trace, native_events_supported: bool) -> void

        def to_msgpack: (?untyped? packer) -> untyped

        def to_json: (*untyped args) -> untyped
      end

      class SerializableSpan
        @native_events_supported: bool
        @trace_id: Integer

        attr_reader span: Span

        def initialize: (untyped span, native_events_supported: bool) -> void

        def to_msgpack: (?untyped? packer) -> untyped

        def to_json: (*untyped args) -> untyped

        def time_nano: (untyped time) -> untyped

        def to_hash: () -> untyped

        def duration_nano: (untyped duration) -> untyped
      end
    end
  end
end
