module Datadog
  module Tracing
    module Transport
      module SpanEvents
        @native_events_supported: bool

        private

        def logger: () -> Datadog::Core::Logger
        def native_events_supported?: () -> bool
      end
    end
  end
end
