module Datadog
  module Tracing
    module Transport
      module SpanEventsNegotiation
        @native_events_supported: bool

        private

        def native_events_supported?: () -> bool
      end
    end
  end
end
