module Datadog
  module Tracing
    module Transport
      module Traces
        class Parcel < Core::Transport::Parcel
          @trace_count: untyped

          attr_reader trace_count: untyped

          def initialize: (untyped data, trace_count: Integer, ?content_type: untyped?, ?content_encoding: untyped?) -> void
        end
        class Request < Datadog::Core::Transport::Request
        end
        module Response
          attr_reader service_rates: untyped

          attr_reader trace_count: untyped
        end
        class Chunker
          @encoder: untyped

          @logger: untyped

          @native_events_supported: bool

          @max_size: untyped
          DEFAULT_MAX_PAYLOAD_SIZE: untyped

          attr_reader encoder: untyped

          attr_reader max_size: untyped

          attr_reader logger: untyped
          def initialize: (untyped encoder, logger: untyped, native_events_supported: untyped, ?max_size: untyped) -> void
          def encode_in_chunks: (untyped traces) -> untyped

          private

          def encode_one: (untyped trace) -> (nil | untyped)
        end
        module Encoder
          def self?.encode_trace: (untyped encoder, untyped trace, logger: untyped, native_events_supported: untyped) -> untyped
        end
        class Transport < Core::Transport::Transport
          @native_events_supported: bool

          def send_traces: (Array[Tracing::TraceOperation] traces) -> untyped

          def stats: () -> untyped
	  
          # Traces transport overrides HTTP client
          # Instance variable type replacement is not permitted by steep.
          #@client: Tracing::Transport::HTTP::Client
          def client: () -> Tracing::Transport::HTTP::Client

          private

          def native_events_supported?: () -> bool
        end
      end
    end
  end
end
