# frozen_string_literal: true

# This file is auto-generated from `supported-configurations.json` by `rake local_config_map:generate`.
# Do not change manually! Please refer to `docs/AccessEnvironmentVariables.md` for more information.

module Datadog
  module Core
    module Configuration
      SUPPORTED_CONFIGURATIONS =
        {"DD_AGENT_HOST" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_API_KEY" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_API_SECURITY_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_API_SECURITY_ENDPOINT_COLLECTION_ENABLED" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_API_SECURITY_REQUEST_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_API_SECURITY_SAMPLE_DELAY" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APM_TRACING_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_AUTOMATED_USER_EVENTS_TRACKING" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_AUTO_USER_INSTRUMENTATION_MODE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_HTTP_BLOCKED_TEMPLATE_HTML" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_HTTP_BLOCKED_TEMPLATE_JSON" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_HTTP_BLOCKED_TEMPLATE_TEXT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_MAX_STACK_TRACES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_MAX_STACK_TRACE_DEPTH" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_MAX_STACK_TRACE_DEPTH_TOP_PERCENT" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_OBFUSCATION_PARAMETER_KEY_REGEXP" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_OBFUSCATION_PARAMETER_VALUE_REGEXP" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_RASP_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_RULES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_SCA_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_STACK_TRACE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_TRACE_RATE_LIMIT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_WAF_DEBUG" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_APPSEC_WAF_TIMEOUT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_CRASHTRACKING_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_DATA_STREAMS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_DBM_PROPAGATION_MODE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_DISABLE_DATADOG_RAILS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_DYNAMIC_INSTRUMENTATION_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_DYNAMIC_INSTRUMENTATION_PROBE_FILE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_DYNAMIC_INSTRUMENTATION_REDACTED_IDENTIFIERS" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_DYNAMIC_INSTRUMENTATION_REDACTED_TYPES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_ENV" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_ERROR_TRACKING_HANDLED_ERRORS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_ERROR_TRACKING_HANDLED_ERRORS_INCLUDE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_EXPERIMENTAL_FLAGGING_PROVIDER_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_EXPERIMENTAL_PROPAGATE_PROCESS_TAGS_ENABLED",
         "DD_GIT_COMMIT_SHA" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_GIT_REPOSITORY_URL" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_HEALTH_METRICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_INJECTION_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_INJECT_FORCE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_INSTRUMENTATION_INSTALL_ID" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_INSTRUMENTATION_INSTALL_TIME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_INSTRUMENTATION_INSTALL_TYPE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_INSTRUMENTATION_TELEMETRY_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_INTEGRATION_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_LOGS_INJECTION" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_METRIC_AGENT_PORT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_ALLOCATION_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_DIR_INTERRUPTION_WORKAROUND_ENABLED" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_ENDPOINT_COLLECTION_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_EXPERIMENTAL_HEAP_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_EXPERIMENTAL_HEAP_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_EXPERIMENTAL_HEAP_SIZE_ENABLED" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_GC_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_GVL_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_HEAP_CLEAN_AFTER_GC_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_MAX_FRAMES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_NATIVE_FILENAMES_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_NO_SIGNALS_WORKAROUND_ENABLED" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_OVERHEAD_TARGET_PERCENTAGE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_PREVIEW_OTEL_CONTEXT_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_SIGHANDLER_SAMPLING_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_SKIP_MYSQL2_CHECK" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_TIMELINE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_UPLOAD_PERIOD" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_PROFILING_UPLOAD_TIMEOUT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_REDIS_COMMAND_ARGS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_REMOTE_CONFIGURATION_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_REMOTE_CONFIG_BOOT_TIMEOUT_SECONDS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_RODA_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_RODA_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_RUNTIME_METRICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_SERVICE" => [{version: "B", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_SITE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_SPAN_SAMPLING_RULES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_SPAN_SAMPLING_RULES_FILE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TAGS" => [{version: "B", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TELEMETRY_AGENTLESS_URL" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TELEMETRY_DEPENDENCY_COLLECTION_ENABLED" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TELEMETRY_HEARTBEAT_INTERVAL" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TELEMETRY_LOG_COLLECTION_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TELEMETRY_METRICS_AGGREGATION_INTERVAL" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TELEMETRY_METRICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_128_BIT_TRACEID_GENERATION_ENABLED" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_CABLE_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_CABLE_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_CABLE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_MAILER_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_MAILER_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_MAILER_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_PACK_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_PACK_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_PACK_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_VIEW_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_VIEW_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTION_VIEW_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_JOB_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_JOB_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_JOB_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_MODEL_SERIALIZERS_ANALYTICS_ENABLED" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_MODEL_SERIALIZERS_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_MODEL_SERIALIZERS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_RECORD_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_RECORD_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_RECORD_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_SUPPORT_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_SUPPORT_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ACTIVE_SUPPORT_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_AGENT_PORT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_AGENT_TIMEOUT_SECONDS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_AGENT_URL" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_AWS_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_AWS_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_AWS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_AWS_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_AWS_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_BAGGAGE_TAG_KEYS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_CLIENT_IP_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_CLIENT_IP_HEADER" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_CONCURRENT_RUBY_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DALLI_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DALLI_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DALLI_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DALLI_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DALLI_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DEBUG" => [{version: "B", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DELAYED_JOB_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DELAYED_JOB_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_DELAYED_JOB_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ELASTICSEARCH_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ELASTICSEARCH_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ELASTICSEARCH_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ELASTICSEARCH_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ELASTICSEARCH_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ENABLED" => [{version: "B", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ETHON_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ETHON_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ETHON_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ETHON_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_ETHON_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_EXCON_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_EXCON_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_EXCON_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_EXCON_ERROR_STATUS_CODES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_EXCON_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_EXCON_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_FARADAY_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_FARADAY_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_FARADAY_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_FARADAY_ERROR_STATUS_CODES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_FARADAY_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_FARADAY_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPE_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPE_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPE_ERROR_STATUS_CODES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPHQL_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPHQL_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPHQL_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPHQL_ERROR_EXTENSIONS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPHQL_ERROR_TRACKING" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRAPHQL_WITH_UNIFIED_TRACER" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRPC_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRPC_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRPC_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRPC_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_GRPC_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HANAMI_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HEADER_TAGS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPCLIENT_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPCLIENT_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPCLIENT_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPCLIENT_ERROR_STATUS_CODES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPCLIENT_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPCLIENT_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPRB_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPRB_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPRB_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPRB_ERROR_STATUS_CODES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPRB_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTPRB_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTP_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTP_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTP_CLIENT_ERROR_STATUSES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTP_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTP_ERROR_STATUS_CODES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_HTTP_SERVER_ERROR_STATUSES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_KAFKA_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_KAFKA_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_KAFKA_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_KARAFKA_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_LOGRAGE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MEMCACHED_COMMAND_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MONGO_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MONGO_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MONGO_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MONGO_JSON_COMMAND" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MONGO_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MONGO_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MYSQL2_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MYSQL2_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MYSQL2_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MYSQL2_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_MYSQL2_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_NATIVE_SPAN_EVENTS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_NET_HTTP_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_NET_HTTP_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_OPENSEARCH_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_OPENSEARCH_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_OPENSEARCH_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_OPENSEARCH_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_OPENSEARCH_RESOURCE_PATTERN" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_OPENSEARCH_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PEER_SERVICE_DEFAULTS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PEER_SERVICE_MAPPING" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PG_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PG_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PG_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PG_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PG_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PRESTO_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PRESTO_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PRESTO_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PRESTO_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PRESTO_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PROPAGATION_EXTRACT_FIRST" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PROPAGATION_STYLE" => [{version: "B", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PROPAGATION_STYLE_EXTRACT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_PROPAGATION_STYLE_INJECT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_QUE_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_QUE_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_QUE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_QUE_TAG_ARGS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_QUE_TAG_DATA_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RACECAR_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RACECAR_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RACECAR_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RACK_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RACK_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RACK_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RAILS_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RAILS_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RAILS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RAKE_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RAKE_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RAKE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RATE_LIMIT" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REDIS_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REDIS_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REDIS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REDIS_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REDIS_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REPORT_HOSTNAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RESOURCE_RENAMING_ALWAYS_SIMPLIFIED_ENDPOINT" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RESOURCE_RENAMING_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RESQUE_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RESQUE_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RESQUE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REST_CLIENT_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REST_CLIENT_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REST_CLIENT_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REST_CLIENT_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_REST_CLIENT_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_RODA_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SAMPLE_RATE" => [{version: "B", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SAMPLING_RULES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SEMANTIC_LOGGER_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SEQUEL_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SEQUEL_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SEQUEL_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SHORYUKEN_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SHORYUKEN_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SHORYUKEN_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SIDEKIQ_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SIDEKIQ_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SIDEKIQ_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SINATRA_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SINATRA_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SINATRA_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SNEAKERS_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SNEAKERS_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SNEAKERS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_STARTUP_LOGS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_STRIPE_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_STRIPE_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_STRIPE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SUCKER_PUNCH_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SUCKER_PUNCH_ANALYTICS_SAMPLE_RATE" =>
          [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_SUCKER_PUNCH_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_TEST_MODE_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_TRILOGY_ANALYTICS_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_TRILOGY_ANALYTICS_SAMPLE_RATE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_TRILOGY_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_TRILOGY_PEER_SERVICE" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_TRILOGY_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_WATERDROP_ENABLED" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_TRACE_X_DATADOG_TAGS_MAX_LENGTH" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "DD_VERSION" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "OTEL_LOG_LEVEL" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "OTEL_PROPAGATORS" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "OTEL_RESOURCE_ATTRIBUTES" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "OTEL_SERVICE_NAME" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "OTEL_TRACES_EXPORTER" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "OTEL_TRACES_SAMPLER" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}],
         "OTEL_TRACES_SAMPLER_ARG" => [{version: "A", type: nil, propertyKeys: [nil], defaultValue: nil}]}.freeze

      ALIASES =
        {"DD_DISABLE_DATADOG_RAILS" => ["DISABLE_DATADOG_RAILS"],
         "DD_PROFILING_GVL_ENABLED" => ["DD_PROFILING_PREVIEW_GVL_ENABLED"],
         "DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED" => ["DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED"],
         "DD_SERVICE" => ["OTEL_SERVICE_NAME"],
         "DD_TAGS" => ["OTEL_RESOURCE_ATTRIBUTES"],
         "DD_TRACE_DEBUG" => ["OTEL_LOG_LEVEL"],
         "DD_TRACE_ENABLED" => ["OTEL_TRACES_EXPORTER"],
         "DD_TRACE_PROPAGATION_STYLE" => ["OTEL_PROPAGATORS"],
         "DD_TRACE_SAMPLE_RATE" => ["OTEL_TRACES_SAMPLER"]}.freeze

      DEPRECATIONS =
        ["DD_PROFILING_PREVIEW_GVL_ENABLED", "DISABLE_DATADOG_RAILS"].freeze

      ALIAS_TO_CANONICAL =
        {"DD_PROFILING_PREVIEW_GVL_ENABLED" => "DD_PROFILING_GVL_ENABLED",
         "DD_TRACE_EXPERIMENTAL_RUNTIME_ID_ENABLED" => "DD_RUNTIME_METRICS_RUNTIME_ID_ENABLED",
         "DISABLE_DATADOG_RAILS" => "DD_DISABLE_DATADOG_RAILS",
         "OTEL_LOG_LEVEL" => "DD_TRACE_DEBUG",
         "OTEL_PROPAGATORS" => "DD_TRACE_PROPAGATION_STYLE",
         "OTEL_RESOURCE_ATTRIBUTES" => "DD_TAGS",
         "OTEL_SERVICE_NAME" => "DD_SERVICE",
         "OTEL_TRACES_EXPORTER" => "DD_TRACE_ENABLED",
         "OTEL_TRACES_SAMPLER" => "DD_TRACE_SAMPLE_RATE"}.freeze
    end
  end
end
