module Datadog
  module AppSec
    module Monitor
      module Gateway
        module TelemetryWatcher
          def self.watch: () -> void

          def self.watch_user_lifecycle: (?Instrumentation::Gateway gateway) -> void

          def self.watch_authenticated_request: (?Instrumentation::Gateway gateway) -> void
        end
      end
    end
  end
end
