module Datadog
  module AppSec
    module Monitor
      module Gateway
        module Watcher
          ARBITRARY_VALUE: ::String

          EVENT_LOGIN_SUCCESS: ::String

          EVENT_LOGIN_FAILURE: ::String

          WATCHED_LOGIN_EVENTS: ::Array[::String]

          WATCH_USER_ID_ONCE: Core::Utils::OnlyOnce
          WATCH_USER_LOGIN_ONCE: Core::Utils::OnlyOnce

          def self.watch: () -> untyped

          def self.watch_user_id: (?Instrumentation::Gateway gateway) -> void

          def self.watch_user_login: (?Instrumentation::Gateway gateway) -> void
        end
      end
    end
  end
end
