module Datadog
  module AppSec
    module Contrib
      module Rack
        module Gateway
          class Request < Instrumentation::Gateway::Argument
            @env: ::Hash[::String, top]

            attr_reader env: ::Hash[::String, top]

            def initialize: (::Hash[::String, top] env) -> void

            def request: () -> ::Rack::Request

            def query: () -> ::Hash[::String, top]

            def headers: () -> ::Hash[::String, ::String]

            def body: () -> ::String

            def method: () -> ::String

            def url: () -> ::String

            def cookies: () -> ::Hash[::String, ::String]

            def host: () -> ::String

            def user_agent: () -> ::String

            def remote_addr: () -> ::String

            def form_hash: () -> ::Hash[::String, top]

            def client_ip: () -> ::String?
          end
        end
      end
    end
  end
end
