module Datadog
  module AppSec
    module Contrib
      module Rack
        module Gateway
          module Watcher
            def self.watch: () -> untyped

            def self.watch_request: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> untyped

            def self.watch_response: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> untyped

            def self.watch_request_body: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> untyped

            private

            def self.active_trace: () -> (nil | untyped)

            def self.active_span: () -> (nil | untyped)
          end
        end
      end
    end
  end
end
