module Datadog
  module AppSec
    module Contrib
      module Rack
        module Gateway
          module Watcher
            def self.watch: () -> void

            def self.watch_request: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> void

            def self.watch_response: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> void

            def self.watch_request_body: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> void

            def self.watch_request_finish: (?Datadog::AppSec::Instrumentation::Gateway gateway) -> void
          end
        end
      end
    end
  end
end
