module Datadog
  module Tracing
    module Distributed
      class Baggage
        BAGGAGE_KEY : "baggage"
        DD_TRACE_BAGGAGE_MAX_ITEMS : 64
        DD_TRACE_BAGGAGE_MAX_BYTES : 8192
        BAGGAGE_TAG_KEYS_MATCH_ALL : Array[String]
        SAFE_CHARACTERS_KEY : "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789$!#&'*+-.^_`|~"
        SAFE_CHARACTERS_VALUE : "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789$!#&'()*+-./:<>?@[]^_`{|}~"

        @baggage_key: ::String
        @fetcher: singleton(Distributed::Fetcher)
        @baggage_tag_keys: ::Array[::String]

        def initialize: (fetcher: untyped, ?baggage_key: ::String, ?baggage_tag_keys: untyped) -> void

        def inject!: (untyped digest, untyped data) -> (nil | untyped)

        def extract: (untyped data) -> (nil | untyped)


        private

        def encode_item: (String item, String safe_characters) -> string

        def parse_baggage_header: (String baggage_header) -> Hash[String, String]

        def build_baggage_tags: (Hash[String, String] baggage) -> Hash[String, String]

        def record_telemetry_metric: (String metric_name, Integer value, Hash[String, String] tags) -> void
        end
    end
  end
end
