module Datadog
  module Tracing
    module Distributed
      class TraceState
        def self.from_digest: (TraceDigest digest, ?propagate_sampling: bool) -> TraceState
        def self.extract: (::String? tracestate) -> TraceState
        def self.split: (::String? tracestate) -> ::Array[::String]?

        attr_reader tracestate: ::String?
        attr_reader datadog: Datadog
        attr_reader open_telemetry: OpenTelemetry

        def initialize: (?tracestate: ::String?, ?datadog: Datadog?, ?open_telemetry: OpenTelemetry?) -> void
        def build: -> ::String?

        private

        def select_leading_vendors: -> ::Array[::String]
        def add_leading_vendor: (::Array[::String] leading_vendors, Datadog | OpenTelemetry state) -> void
      end
    end
  end
end
