module Datadog
  module OpenTracer
    class DistributedHeaders
      def initialize: (untyped carrier) -> void

      def valid?: () -> untyped

      def trace_id: () -> untyped

      def parent_id: () -> untyped

      def sampling_priority: () -> (nil | untyped)

      def origin: () -> untyped

      private

      def id: (untyped header) -> (nil | untyped)
    end
  end
end
