module Datadog
  module OpenTracer
    module RackPropagator
      extend Propagator

      BAGGAGE_PREFIX: "ot-baggage-"

      BAGGAGE_PREFIX_FORMATTED: "HTTP_OT_BAGGAGE_"
      def self.inject: (untyped span_context, untyped carrier) -> nil
      def self.extract: (untyped carrier) -> untyped

      private

      def self.baggage_header?: (untyped header) -> untyped

      def self.header_to_baggage: (untyped key) -> untyped
    end
  end
end
