module Datadog
  module OpenTracer
    class Scope < ::OpenTracing::Scope
      attr_reader manager: untyped

      attr_reader span: untyped

      def initialize: (manager: untyped, span: untyped) -> void
    end
  end
end
