module Datadog
  module OpenTracer
    class Span < ::OpenTracing::Span
      attr_reader datadog_span: untyped

      def initialize: (datadog_span: untyped, span_context: untyped) -> void
      def operation_name=: (untyped name) -> untyped
      def context: () -> untyped
      def set_tag: (untyped key, untyped value) -> untyped
      def set_baggage_item: (untyped key, untyped value) -> untyped
      def get_baggage_item: (untyped key) -> untyped
      def log: (?event: untyped?, ?timestamp: untyped, **untyped fields) -> untyped
      def log_kv: (?timestamp: untyped, **untyped fields) -> (untyped | nil)
      def finish: (?end_time: untyped) -> untyped
    end
  end
end
