module Datadog
  module OpenTracer
    class SpanContext < ::OpenTracing::SpanContext
      attr_reader datadog_context: untyped

      attr_reader datadog_trace_digest: untyped

      def initialize: (datadog_context: untyped, ?datadog_trace_digest: untyped?, ?baggage: ::Hash[untyped, untyped]) -> void
    end
  end
end
