module Datadog
  module OpenTracer
    module TextMapPropagator
      extend Propagator

      BAGGAGE_PREFIX: "ot-baggage-"
      def self.inject: (untyped span_context, untyped carrier) -> nil
      def self.extract: (untyped carrier) -> untyped

      private

      def self.headers_to_trace_digest: (untyped headers) -> (nil | untyped)

      def self.baggage_item?: (untyped item) -> untyped

      def self.item_to_baggage: (untyped key) -> untyped
    end
  end
end
