module Datadog
  module OpenTracer
    class ThreadLocalScope < Scope
      attr_reader finish_on_close: untyped

      def initialize: (manager: untyped, span: untyped, ?finish_on_close: bool) -> void
      def close: () -> (nil | untyped)
    end
  end
end
