module Datadog
  module AppSec
    module Contrib
      module AwsLambda
        module Gateway
          class Request < ::Struct[untyped]
            attr_accessor host: ::String?

            attr_accessor user_agent: ::String?

            attr_accessor remote_addr: ::String?

            attr_accessor headers: ::Hash[::String, ::String]

            def self.new: (
              ?host: ::String?,
              ?user_agent: ::String?,
              ?remote_addr: ::String?,
              ?headers: ::Hash[::String, ::String]
            ) -> Request
          end
        end
      end
    end
  end
end
