module Datadog
  module Tracing
    module Contrib
      module Aws
        module Patcher
          include Contrib::Patcher

          def self?.target_version: () -> untyped

          def self?.patch: () -> untyped

          def self?.add_plugin: (*untyped targets) -> untyped

          def self?.loaded_constants: () -> untyped

          def self?.get_option: (untyped option) -> untyped
        end
      end
    end
  end
end
