module Datadog
  module Tracing
    module Contrib
      module ActiveStorage
        module Events
          module DownloadChunk
            include ActiveStorage::Event
            extend ActiveSupport::Notifications::Event

            EVENT_NAME: "service_download_chunk.active_storage"

            def self?.event_name: () -> ::String

            def self?.span_name: () -> ::String

            def self?.span_type: () -> ::String

            def self?.process: (Event::span span, any _event, any _id, Event::payload payload) -> void
          end
        end
      end
    end
  end
end
