module Datadog
  module Tracing
    module Contrib
      module Rack
        module Configuration
          class Settings < Contrib::Configuration::Settings
            DEFAULT_HEADERS: { response: ::Array["Content-Type" | "X-Request-ID"] }
          end
        end
      end
    end
  end
end
