module Datadog
  module Kit
    module Tracing
      module MethodTracer : Module
        def self.trace_method: (Module klass, Symbol method_name, ?String? span_name, ?dynamic: bool) -> void
        def trace_method: (Symbol method_name, ?String? span_name, ?dynamic: bool) -> void
      end
    end
  end
end
