module Datadog
  module Tracing
    module Contrib
      module Rails
        module Patcher
          include Contrib::Patcher

          BEFORE_INITIALIZE_ONLY_ONCE_PER_APP: untyped

          AFTER_INITIALIZE_ONLY_ONCE_PER_APP: untyped

          def self?.target_version: () -> untyped

          def self?.patch: () -> untyped

          def self?.patch_before_initialize: () -> untyped

          def self?.before_initialize: (untyped app) -> untyped

          def self?.add_middleware: (untyped app) -> untyped

          def self?.add_logger: (untyped app) -> untyped

          def self?.patch_after_initialize: () -> untyped

          def self?.after_initialize: (untyped app) -> untyped
          def self?.setup_tracer: () -> untyped
        end
      end
    end
  end
end
