module Datadog
  module Debugger
    class Component
      def self.build: (Datadog::Core::Configuration::Settings settings) -> Datadog::Debugger::Component?

      private

      def shutdown!: () -> untyped
    end
  end
end
