module Datadog
  module Profiling
    class BacktraceLocation
      attr_reader base_label: untyped

      attr_reader lineno: untyped

      attr_reader path: untyped

      attr_reader hash: untyped

      def initialize: (untyped base_label, untyped lineno, untyped path) -> void

      def ==: (untyped other) -> untyped

      def eql?: (untyped other) -> untyped
    end
  end
end
