module Datadog
  module Profiling
    class Buffer < Core::Buffer::ThreadSafe
      def initialize: (*untyped args) -> void

      def cache: (untyped cache_name) -> untyped

      def string_table: () -> untyped

      def drain!: () -> untyped
    end
  end
end
