module Datadog
  module Profiling
    module Component
      def self.build_profiler_component: (
        settings: untyped,
        agent_settings: Datadog::Core::Configuration::AgentSettingsResolver::AgentSettings,
        optional_tracer: Datadog::Tracing::Tracer?,
      ) -> Datadog::Profiling::Profiler?

      def self.build_profiler_exporter: (
        untyped settings,
        Datadog::Profiling::StackRecorder recorder,
        internal_metadata: ::Hash[::Symbol, ::String | bool | ::Numeric],
      ) -> Datadog::Profiling::Exporter

      def self.build_profiler_transport: (
        untyped settings,
        Datadog::Core::Configuration::AgentSettingsResolver::AgentSettings agent_settings
      ) -> untyped

      def self.enable_gc_profiling?: (untyped settings) -> bool
      def self.get_allocation_sample_every: (untyped settings) -> ::Integer
      def self.enable_allocation_profiling?: (untyped settings, ::Integer allocation_sample_every) -> bool
      def self.enable_heap_profiling?: (untyped settings, bool allocation_profiling_enabled) -> bool

      def self.no_signals_workaround_enabled?: (untyped settings) -> bool

      def self.incompatible_libmysqlclient_version?: (untyped settings) -> bool
    end
  end
end
