module Datadog
  module Profiling
    # Type alias and native (C-only) method declarations for this class.
    # Instance-level types live inline in the `.rb` file.
    class HttpTransport
      type exporter_configuration_array = [:agentless, Integer, bool, String, String] | [:agent, Integer, bool, String]

      def self._native_validate_exporter: (exporter_configuration_array exporter_configuration) -> [:ok | :error, ::String?]

      def self._native_do_export: (
        exporter_configuration_array exporter_configuration,
        Datadog::Profiling::Flush flush,
      ) -> [:ok | :error, ::Integer | ::String]
    end
  end
end
