module Datadog
  module Profiling
    class Profiler
      include Datadog::Core::Utils::Forking

      private

      attr_reader worker: Datadog::Profiling::Collectors::CpuAndWallTimeWorker
      attr_reader scheduler: Datadog::Profiling::Scheduler

      public

      def initialize: (
        worker: Datadog::Profiling::Collectors::CpuAndWallTimeWorker,
        scheduler: Datadog::Profiling::Scheduler
      ) -> void

      def start: () -> void

      def shutdown!: () -> void

      private

      def stop_worker: () -> void
      def stop_scheduler: () -> void
      def component_failed: (:worker | :scheduler failed_component) -> void
    end
  end
end
