module Datadog
  module Profiling
    class Profiler
      include Datadog::Core::Utils::Forking

      private

      attr_reader worker: untyped # TODO: Change this to CpuAndWallTimeWorker once legacy profiler is retired
      attr_reader scheduler: Datadog::Profiling::Scheduler

      public

      def initialize: (
        worker: Datadog::Profiling::Collectors::OldStack | Datadog::Profiling::Collectors::CpuAndWallTimeWorker,
        scheduler: Datadog::Profiling::Scheduler,
      ) -> void

      def start: () -> void

      def shutdown!: () -> void
    end
  end
end
