module Datadog
  module Profiling
    class Scheduler < Core::Worker
      include Core::Workers::Polling

      def initialize: (
        exporter: Datadog::Profiling::Exporter,
        transport: Datadog::Profiling::HttpTransport,
        ?fork_policy: untyped,
        ?interval: ::Numeric,
        ?enabled: bool,
      ) -> void

      def start: (?on_failure_proc: ::Proc?) -> void

      def reset_after_fork: () -> void
      def mark_profiler_failed: () -> true
    end
  end
end
