module Datadog
  module DI
    module EL
      class Evaluator
        MATCHES_TIMEOUT_SECONDS: Float

        @context: Context

        @regexps: Array[Regexp]?

        def initialize: (Context context) -> void

        def evaluate: (Context compiled) -> untyped

        def regexps: () -> Array[Regexp]

        def regexps=: (Array[Regexp]) -> Array[Regexp]

        def self.compile_regexp: (String needle) -> Regexp

        def ref: ((Symbol | String) var) -> untyped

        def iref: ((Symbol | String) var) -> untyped

        def len: (untyped var, (Symbol | String) var_name) -> Integer

        def is_empty: (untyped var, (Symbol | String) var_name) -> bool

        def is_undefined: (untyped var, (Symbol | String) var_name) -> bool

        def contains: (untyped haystack, untyped needle) -> bool

        def matches: (String haystack, String needle) -> bool

        def matches_compiled: (untyped haystack, Integer index) -> bool

        private def apply_match: (Regexp re, untyped haystack) -> bool

        def getmember: (untyped object, (Symbol | String) field) -> untyped

        def index: (Array[untyped] | Hash[untyped, untyped] array_or_hash, untyped index_or_key) -> untyped

        def substring: (String object, Integer from, Integer to) -> String?

        def starts_with: (untyped haystack, String needle) -> bool

        def ends_with: (untyped haystack, String needle) -> bool

        def all: (Array[untyped] | Hash[untyped, untyped] collection) { (?) -> untyped } -> bool

        def any: (Array[untyped] | Hash[untyped, untyped] collection) { (?) -> untyped } -> bool

        def filter: (Array[untyped] | Hash[untyped, untyped] collection) { (?) -> untyped } -> (Array[untyped] | Hash[untyped, untyped])

        def instanceof: (untyped object, String cls_name) -> bool
      end
    end
  end
end
