module Datadog
  module DI
    module EL
      class Evaluator
        MATCHES_TIMEOUT_SECONDS: ::Float

        @context: Context

        @regexps: ::Array[::Regexp]

        def initialize: (?::Array[::Regexp] regexps) -> void

        def evaluate: (Context compiled) -> any

        def regexps: () -> ::Array[::Regexp]

        def self.compile_regexp: (::String needle) -> ::Regexp

        def ref: ((Symbol | String) var) -> any

        def iref: ((Symbol | String) var) -> any

        def len: (any var, (Symbol | String) var_name) -> Integer

        def is_empty: (any var, (Symbol | String) var_name) -> bool

        def is_undefined: (any var, (Symbol | String) var_name) -> bool

        def contains: (any haystack, any needle) -> bool

        def matches: (String haystack, String needle) -> bool

        def matches_compiled: (::String haystack, ::Integer index) -> bool

        private def bounded_match?: (::Regexp re, ::String haystack) -> bool

        def getmember: (any object, (Symbol | String) field) -> any

        def index: (Array[any] | Hash[any, any] array_or_hash, any index_or_key) -> any

        def substring: (String object, Integer from, Integer to) -> String?

        def starts_with: (any haystack, String needle) -> bool

        def ends_with: (any haystack, String needle) -> bool

        def all: (Array[any] | Hash[any, any] collection) { (?) -> any } -> bool

        def any: (Array[any] | Hash[any, any] collection) { (?) -> any } -> bool

        def filter: (Array[any] | Hash[any, any] collection) { (?) -> any } -> (Array[any] | Hash[any, any])

        def instanceof: (any object, String cls_name) -> bool
      end
    end
  end
end
