module Datadog
  module DI
    module EL
      class Expression
        @dsl_expr: String

        @evaluator: Evaluator

        @redaction_identifier: ::String?

        def initialize: (::String dsl_expr, ::String compiled_expr, ?::Array[::Regexp] regexps, ?redaction_identifier: ::String?) -> void

        attr_reader dsl_expr: String

        attr_reader evaluator: Evaluator

        attr_reader redaction_identifier: ::String?

        def evaluate: (Context context) -> any

        def satisfied?: (Context context) -> bool
      end
    end
  end
end
