module Datadog
  module DI
    module EL
      class Expression
        @dsl_expr: String

        @evaluator: Evaluator

        def initialize: (::String dsl_expr, ::String compiled_expr, ?::Array[::Regexp] regexps) -> void

        attr_reader dsl_expr: String

        attr_reader evaluator: Evaluator

        def evaluate: (Context context) -> untyped

        def satisfied?: (Context context) -> bool
      end
    end
  end
end
