module Datadog
  module DI
    module EL
      class Expression
        @compiled_expr: untyped

        def initialize: (untyped compiled_expr) -> void

        attr_reader compiled_expr: untyped

        def ==: (untyped other) -> untyped

        def evaluate: (untyped context) -> untyped

        def satisfied?: (untyped context) -> untyped
      end
    end
  end
end
