module Datadog
  module Tracing
    module Contrib
      module MongoDB
        module Configuration
          class Settings < Contrib::Configuration::Settings
            DEFAULT_QUANTIZE: { show: ::Array[:collection | :database | :operation] }
          end
        end
      end
    end
  end
end
