module Datadog
  module Tracing
    module Contrib
      module Kafka
        module ConsumerGroupEvent
          def process: (untyped span, untyped _event, untyped _id, untyped payload) -> untyped
        end
      end
    end
  end
end
