module Datadog
  module Core
    module Diagnostics
      module Health
        class Metrics < Core::Metrics::Client
          include Tracing::Diagnostics::Health::Metrics
        end
      end
    end
  end
end
