module Datadog
  module Tracing
    module Contrib
      module Propagation
        module SqlComment
          def self.annotate!: (untyped span_op, untyped mode) -> (nil | untyped)
          def self.prepend_comment: (String sql, SpanOperation span_op, TraceOperation trace_op, untyped mode) -> String

          def self.datadog_configuration: () -> untyped
        end
      end
    end
  end
end
