module Datadog
  module OpenFeature
    module Binding
      class Evaluator
        @ufc_json: ::String?

        def initialize: (::String? ufc_json) -> void

        def get_assignment: (
          ::String flag_key,
          ::OpenFeature::SDK::EvaluationContext? evaluation_context,
          ::Symbol expected_type,
          ::Integer time
        ) -> ResolutionDetails

        private

        def generate: (::Symbol expected_type) -> untyped
      end
    end
  end
end
