module Datadog
  module OpenFeature
    module Binding
      class ResolutionDetails
        attr_reader value: untyped

        attr_reader reason: ::Symbol?

        attr_reader variant: untyped

        attr_reader error_code: ::Symbol?

        attr_reader error_message: ::String?

        attr_reader allocation_key: ::String?

        attr_reader do_log: bool?

        def initialize: (
          value: untyped,
          ?variant: untyped,
          ?error_code: ::Symbol?,
          ?error_message: ::String?,
          ?reason: ::Symbol?,
          ?allocation_key: ::String?,
          ?do_log: bool?
        ) -> void
      end

      class Evaluator
        @ufc_json: ::String?

        def initialize: (::String? ufc_json) -> void

        def get_assignment: (
          ::String flag_key,
          ::OpenFeature::SDK::EvaluationContext? evaluation_context,
          ::Symbol expected_type
        ) -> ResolutionDetails

        private

        def generate: (::Symbol expected_type) -> untyped
      end
    end
  end
end
