issuer: https://token.actions.githubusercontent.com

subject_pattern: "repo:DataDog/dd-trace-rb:ref:refs/heads/master"

claim_pattern:
  event_name: schedule|workflow_dispatch
  repository: DataDog/dd-trace-rb
  job_workflow_ref: DataDog/dd-trace-rb/\.github/workflows/update-latest-dependency\.yml@refs/heads/master

permissions:
  contents: write
  pull_requests: write
