module Datadog
  module CI
    module Contrib
      module Minitest
        module Configuration
          class Settings < Datadog::Tracing::Contrib::Configuration::Settings
          end
        end
      end
    end
  end
end
