module Datadog
  module AIGuard
    module Ext
      SPAN_NAME: ::String
      TARGET_TAG: ::String
      TOOL_NAME_TAG: ::String
      ACTION_TAG: ::String
      REASON_TAG: ::String
      BLOCKED_TAG: ::String
      EVENT_TAG: ::String
      SERVICE_ENTRY_EXECUTED_TAG: ::String
      METASTRUCT_TAG: ::String
      HTTP_USERAGENT_TAG: ::String
      HTTP_CLIENT_IP_TAG: ::String
      NETWORK_CLIENT_IP_TAG: ::String
      SERVICE_ENTRY_ATTRIBUTE_KEYS: ::Array[::String]
      STASH_TAG_PREFIX: ::String
    end
  end
end
