module Datadog
  module AppSec
    module Contrib
      module Rails
        module Patches
          module ProcessActionPatch
            def process_action: (*untyped args) -> untyped

            private

            def request: () -> ::ActionDispatch::Request
          end
        end
      end
    end
  end
end
