module Datadog
  module AppSec
    module Contrib
      module Rails
        module Patches
          module RenderToBodyPatch
            def render_to_body: (?::Hash[::Symbol, any] options) -> untyped

            private

            def request: () -> ::ActionDispatch::Request
          end
        end
      end
    end
  end
end
