module Datadog
  module Tracing
    module Contrib
      module Qless
        module Configuration
          class Settings < Contrib::Configuration::Settings
          end
        end
      end
    end
  end
end
