module Datadog
  module OpenTelemetry
    class Logs
      include SignalConfiguration

      EXPORTER_NONE: ::String

      @logger: Core::Logger
      @settings: Core::Configuration::Settings
      @agent_host: ::String?
      @agent_ssl: bool

      def self.initialize!: (Core::Configuration::Components components) -> bool

      def initialize: (Core::Configuration::Components components) -> void

      def configure_logs_sdk: () -> void

      private

      def configure_log_record_processor: (untyped provider) -> void

      def default_logs_endpoint: () -> ::String

      def configure_otlp_exporter: (untyped provider) -> void
    end
  end
end
