module Datadog
  module OpenTelemetry
    class Metrics
      EXPORTER_NONE: ::String

      def self.initialize!: (Core::Configuration::Components components) -> bool

      def initialize: (Core::Configuration::Components components) -> void

      def configure_metrics_sdk: () -> void

      private

      def create_resource: () -> ::OpenTelemetry::SDK::Resources::Resource

      def configure_metric_reader: (::OpenTelemetry::SDK::Metrics::MeterProvider provider) -> void

      def default_metrics_endpoint: () -> ::String

      def configure_otlp_exporter: (::OpenTelemetry::SDK::Metrics::MeterProvider provider) -> void

      def get_metrics_config_with_fallback: (any metrics_config, any exporter_config, ::Symbol option_name, ?any computed_default) -> any
    end
  end
end
