module Datadog
  module OpenTelemetry
    module SignalConfiguration
      private

      def create_resource: () -> ::OpenTelemetry::SDK::Resources::Resource

      def config_or_exporter_fallback: (signal: ::Symbol, option_name: ::Symbol, ?computed_default: any) -> any
    end
  end
end
