# TODO: Fix and remove `ignore 'lib/datadog/core/utils/at_fork_monkey_patch.rb` from `Steep`
module Datadog
  module Core
    module Utils
      module AtForkMonkeyPatch
        @at_fork_blocks: Hash[Symbol, Array[Callback]]

        class Callback
          attr_reader block: Proc
          attr_reader group: Object?

          def initialize: (Proc block, ?Object? group) -> void
        end

        def self.supported?: () -> (false | true)

        def self.apply!: () -> (false | true)

        def self.run_at_fork_blocks: (Symbol stage, snapshot: Hash[Symbol, Array[Callback]], ?started: Hash[Object, bool]) -> void

        def self.run_parent_cleanup: (Hash[Symbol, Array[Callback]] snapshot, Hash[Object, bool] started, Exception fork_error) -> void

        def self.at_fork: (Symbol stage) { () -> untyped } -> Proc

        def self.at_fork_blocks: (before: Proc, parent: Proc, child: Proc) -> Hash[Symbol, Proc]

        def self.remove_at_fork: (Symbol stage, Proc block) -> void

        def self.snapshot_at_fork_blocks: () -> Hash[Symbol, Array[Callback]]

        def self.replace_at_fork_blocks: (Hash[Symbol, Array[Callback]] snapshot) -> void

        module KernelMonkeyPatch
          def fork: () ?{ () -> untyped } -> untyped
        end

        module ProcessMonkeyPatch
          def _fork: () -> Integer

          def daemon: (*untyped args) -> untyped
        end
      end
    end
  end
end
