module Datadog
  module Core
    module Utils
      # Helper methods for encoding and decoding base64
      module Base64
        def self.encode64: (String bin) -> String

        def self.strict_encode64: (String bin) -> String

        def self.strict_decode64: (String str) -> untyped
      end
    end
  end
end
