module Datadog
  module Core
    module Utils
      module Compression
        def self?.gzip: (untyped string, ?level: untyped? level, ?strategy: untyped? strategy) -> untyped

        def self?.gunzip: (untyped string, ?untyped encoding) -> untyped
      end
    end
  end
end
