module Datadog
  module Core
    module Utils
      module Duration
        def self.call: (String value, ?base: ::Symbol) -> Numeric

        private

        def self.cast: (untyped str, bool is_float) -> (::Integer | ::Float)
      end
    end
  end
end
