module Datadog
  module Core
    module Utils
      class LRUCache
        extend Forwardable

        @store: ::Hash[any, any]

        @max_size: ::Integer

        def initialize: (::Integer max_size) -> void

        def []: (any key) -> any

        def []=: (any key, any value) -> any

        def clear: () -> void

        def empty?: () -> bool
      end
    end
  end
end
