module Datadog
  module Core
    module Utils
      class ObjectSet
        def initialize: (?::Integer seed) ?{ () -> untyped } -> untyped

        def fetch: (*untyped args) { (untyped, untyped) -> untyped } -> untyped

        def length: () -> untyped

        def objects: () -> untyped

        def freeze: () -> untyped
      end
    end
  end
end
