module Datadog
  module Core
    module Utils
      class OnlyOnce
        @ran_once: bool
        @mutex: Thread::Mutex

        def initialize: () -> untyped

        def run: () { () -> untyped } -> untyped

        def ran?: () -> untyped

        def reset: -> void
      end
    end
  end
end
