module Datadog
  module Core
    module Utils
      class OnlyOnce
        @ran_once: bool
        @mutex: Thread::Mutex

        def initialize: () -> void

        def run: () { () -> untyped } -> untyped

        def ran?: () -> bool

        private

        def reset_ran_once_state_for_tests: () -> void
      end
    end
  end
end
