module Datadog
  module Core
    module Utils
      class Sequence
        @seed: ::Integer
        @current: ::Integer
        @next_item: (^(::Integer) -> ::Integer)?

        def initialize: (?::Integer seed) ?{ (::Integer) -> ::Integer } -> void

        def next: () -> ::Integer

        def reset!: () -> void
      end
    end
  end
end
