module Datadog
  module Core
    module Utils
      class Sequence
        @seed: ::Integer
        @current: ::Integer
        @next_item: (^(::Integer) -> ::Integer)?

        def initialize: (?::Integer seed) ?{ (::Integer) -> ::Integer } -> untyped

        def next: () -> untyped

        def reset!: () -> void
      end
    end
  end
end
