module Datadog
  module Core
    module Utils
      class Sequence
        def initialize: (?::Integer seed) ?{ () -> untyped } -> untyped

        def next: () -> untyped

        def reset!: () -> void
      end
    end
  end
end
