module Datadog
  module Core
    module Utils
      class StringTable
        def initialize: () -> untyped

        def fetch: (untyped string) -> untyped

        def fetch_string: (untyped string) -> (nil | untyped)

        def []: (untyped id) -> untyped

        def strings: () -> untyped
      end
    end
  end
end
