module Datadog
  module AppSec
    module Contrib
      module Rack
        module Reactive
          module RequestBody
            ADDRESSES: ::Array[::String]

            def self.publish: (AppSec::Reactive::Engine engine, AppSec::Contrib::Rack::Gateway::Response request) -> untyped

            def self.subscribe: (AppSec::Reactive::Engine engine, untyped waf_context) { (untyped) -> untyped } -> untyped
          end
        end
      end
    end
  end
end
