#!/usr/bin/env ruby

if local_gem_path = ENV['DD_DEMO_ENV_GEM_LOCAL_DATADOG']
  puts "\n== Building profiler native extension =="
  # The root Gemfile's lockfile is not regenerated by dependency automation and
  # cooldown-excludes fresh first-party releases; the per-ruby gemfile's is.
  gemfile = "#{local_gem_path}/gemfiles/ruby-#{RUBY_VERSION.split('.').take(2).join('.')}.gemfile"
  success =
    system("export BUNDLE_GEMFILE=#{gemfile} && cd #{local_gem_path} && bundle install && bundle exec rake clean compile")
  raise 'Failure to compile profiler native extension' unless success
else
  puts "\n== Skipping build of profiler native extension, no DD_DEMO_ENV_GEM_LOCAL_DATADOG set =="
end
