module Datadog
  module AppSec
    module ActionsHandler
      class SerializableBacktrace
        def initialize: (locations: ::Array[::Thread::Backtrace::Location], stack_id: String | Symbol | Integer) -> void
        def to_msgpack: (?untyped? packer) -> void
      end
    end
  end
end
