module Datadog
  module AppSec
    module ActionsHandler
      module StackTraceCollection
        type stack_frame = Hash[Symbol, String | Integer | nil]

        def self.collect: (Integer max_depth, Float top_percent) -> Array[stack_frame]
      end
    end
  end
end
