module Datadog
  module Tracing
    module Contrib
      module ActionView
        class Integration
          include Contrib::Integration

          MINIMUM_VERSION: untyped

          def self.version: () -> (untyped | untyped | nil)

          def self.loaded?: () -> untyped

          def self.compatible?: () -> untyped
          def auto_instrument?: () -> untyped

          def new_configuration: () -> untyped

          def patcher: () -> untyped
        end
      end
    end
  end
end
