module Datadog
  module Tracing
    module Contrib
      module ActionView
        module Patcher
          include Contrib::Patcher

          def self?.target_version: () -> untyped

          def self?.patch: () -> untyped

          def self?.patch_renderer: () -> untyped
        end
      end
    end
  end
end
