module Datadog
  module OpenFeature
    module Hooks
      class SpanEnrichmentHook
        MAX_SERIAL_IDS: ::Integer

        MAX_SUBJECTS: ::Integer

        MAX_EXPERIMENTS_PER_SUBJECT: ::Integer

        MAX_DEFAULTS: ::Integer

        MAX_DEFAULT_VALUE_LENGTH: ::Integer

        TAG_FLAGS_ENC: ::String

        TAG_SUBJECTS_ENC: ::String

        TAG_RUNTIME_DEFAULTS: ::String

        @store: AccumulatorStore

        @mutex: Thread::Mutex

        @closed: bool

        @logger: Core::Logger

        def initialize: (AccumulatorStore accumulator_store, logger: Core::Logger) -> void

        def capture: (
          flag_key: ::String,
          variant: ::String?,
          value: untyped,
          serial_id: ::Integer?,
          do_log: bool,
          targeting_key: ::String?
        ) -> void

        def shutdown: () -> void

        private

        def state_for: (untyped trace_op) -> Accumulator

        def subscribe_root_finish: (untyped trace_op, Accumulator accumulator) -> void

        def write_tags_on_root: (untyped span_op, untyped trace_op, Accumulator accumulator) -> void
      end
    end
  end
end
