module Datadog
  module AppSec
    module Contrib
      module Sinatra
        module Reactive
          module Routed
            def self.publish: (untyped op, untyped data) -> untyped

            def self.subscribe: (untyped op, untyped waf_context) { (untyped) -> untyped } -> untyped
          end
        end
      end
    end
  end
end
