module Datadog
  module DI
    module Transport
      module Diagnostics
        class Request < Datadog::Core::Transport::Request
        end

        class Transport < Core::Transport::Transport
          def send_diagnostics: (untyped payload) -> untyped
        end
      end
    end
  end
end
