module Datadog
  module DI
    module Transport
      module Diagnostics
        class Request < Datadog::Core::Transport::Request
        end

        class Transport < Core::Transport::Transport
          def send_diagnostics: (Array[Hash[Symbol, untyped]] payload) -> Core::Transport::Response
        end
      end
    end
  end
end
