module Datadog
  module DI
    module Transport
      module Diagnostics
        class Request < Datadog::Core::Transport::Request
        end

        class Transport < Core::Transport::Transport
          def send_diagnostics: (Array[Hash[Symbol, any]] payload) -> (Core::Transport::HTTP::Response | Core::Transport::InternalErrorResponse)
        end
      end
    end
  end
end
