module Datadog
  module DI
    module Transport
      module HTTP
        def self?.new: (untyped klass) { (?) -> untyped } -> untyped
        def self?.diagnostics: (agent_settings: untyped, **untyped options) ?{ (untyped) -> untyped } -> untyped
        def self?.input: (agent_settings: untyped, **untyped options) ?{ (untyped) -> untyped } -> untyped

        def self?.default_headers: () -> untyped

        def self?.default_adapter: () -> untyped
      end
    end
  end
end
