module Datadog
  module DI
    module Transport
      module Input
        class Request < Datadog::Core::Transport::Request
          @serialized_tags: untyped

          attr_reader serialized_tags: untyped

          def initialize: (untyped parcel, untyped serialized_tags) -> void
        end

        class Transport < Core::Transport::Transport
          @telemetry: Datadog::Core::Telemetry::Component?

          MAX_SERIALIZED_SNAPSHOT_SIZE: ::Integer
          MAX_CHUNK_SIZE: ::Integer
          DEFAULT_CHUNK_SIZE: ::Integer

          attr_reader telemetry: Datadog::Core::Telemetry::Component?

          def initialize: (
            Datadog::Core::Transport::HTTP::API::Map apis,
            ::String default_api,
            logger: Datadog::Core::Logger,
            ?telemetry: Datadog::Core::Telemetry::Component?
          ) -> void

          def send_input: (untyped payload, untyped tags, on_serialization_error: ^(String, Exception) -> void) -> untyped

          def send_input_chunk: (untyped chunked_payload, untyped serialized_tags) -> untyped

          def encoder: () -> singleton(Core::Encoding::JSONEncoder)
        end
      end
    end
  end
end
