module Datadog
  module DI
    module Transport
      module Input
        class Request < Datadog::Core::Transport::Request
          @serialized_tags: untyped

          attr_reader serialized_tags: untyped

          def initialize: (untyped parcel, untyped serialized_tags) -> void
        end

        class Transport < Core::Transport::Transport
          MAX_SERIALIZED_SNAPSHOT_SIZE: ::Integer
          MAX_CHUNK_SIZE: ::Integer
          DEFAULT_CHUNK_SIZE: ::Integer

          def send_input: (untyped payload, untyped tags) -> untyped

          def send_input_chunk: (untyped chunked_payload, untyped serialized_tags) -> untyped
        end
      end
    end
  end
end
