name: Check for missing documentation for library configuration options

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      # A workaround to trigger the workflow for pull requests from forked repository,
      # which does not have access to secrets.
      #
      # This is also useful for testing the workflow without opening a pull request.
      - tmp/*
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Default permissions for all jobs
permissions: {}

jobs:
  run:
    runs-on: ubuntu-22.04
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Restore bundle cache
        uses: ./.github/actions/bundle-restore
        with:
          lockfile: ${{ needs.build.outputs.lockfile }}
          cache-key: ${{ needs.build.outputs.cache-key }}

      - name: Check for missing documentation
        run: bundle exec ruby .github/scripts/check_config_doc.rb