name: Check for missing documentation for library configuration options

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      # A workaround to trigger the workflow for pull requests from forked repository,
      # which does not have access to secrets.
      #
      # This is also useful for testing the workflow without opening a pull request.
      - tmp/*
  pull_request:
    branches:
      - master

# Default permissions for all jobs
permissions: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

#      - name: Set up Ruby
#        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
#        with:
#          ruby-version: "3.4"

      - name: Check for missing documentation
        run: ruby .github/scripts/check_config_doc.rb