name: "Generate Supported Versions"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: "3.3"

      - name: Update latest
        run: bundle exec ruby .github/scripts/update_supported_versions.rb

      - run: git diff

      - name: Get GitHub Token via dd-octo-sts
        id: generate-token
        uses: DataDog/dd-octo-sts-action@96a25462dbcb10ebf0bfd6e2ccc917d2ab235b9a # v1.0.4
        with:
          scope: DataDog/dd-trace-rb
          policy: self.generate-supported-versions

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: auto-generate/update-supported-versions
          title: '[🤖] Update Supported Versions'
          base: master
          labels: dev/internal, integrations
          commit-message: "Test creating supported versions"
          delete-branch: true
          sign-commits: true
          body: |
            This is a PR to update the table for supported integration versions.
            The supported versions markdown is generated from the minimum and maximum tested versions of each integration,
            as defined from the `gemfile.lock` gem declarations.

            Workflow run: [Generate Supported Versions](https://github.com/DataDog/dd-trace-rb/actions/workflows/generate-supported-versions.yml)

            This should be tied to tracer releases, or triggered manually.
