name: Lock Dependencies

on: # yamllint disable-line rule:truthy
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Default permissions for all jobs
permissions: {}

jobs:
  dependency:
    name: Dependency changes
    runs-on: ubuntu-24.04
    outputs:
      changes: ${{ steps.changes.outputs.dependencies }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: .github/dependency_filters.yml

  lock:
    runs-on: ubuntu-24.04
    needs: dependency
    if: ${{ needs.dependency.outputs.changes == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        engine:
          # ADD NEW RUBIES HERE
          - name: ruby
            version: "4.0"
          - name: ruby
            version: "3.4"
          - name: ruby
            version: "3.3"
          - name: ruby
            version: "3.2"
          - name: ruby
            version: "3.1"
          - name: ruby
            version: "3.0"
          - name: ruby
            version: "2.7"
          - name: ruby
            version: "2.6"
          - name: ruby
            version: "2.5"
    container:
      image: ghcr.io/datadog/images-rb/engines/${{ matrix.engine.name }}:${{ matrix.engine.version }}-gnu-gcc
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.engine.name }}-${{ matrix.engine.version }}.gemfile
        BUNDLE_WITHOUT: check
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - run: |
          ruby -v
          gem -v
          bundler -v
      - run: bundle lock --add-platform x86_64-linux aarch64-linux arm64-darwin x86_64-darwin
      - run: bundle install
      - run: bundle exec rake dependency:all
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: lock-dependency-${{ github.run_id }}-${{ matrix.engine.name }}-${{ matrix.engine.version }}
          path: |
            gemfiles/${{ matrix.engine.name }}-${{ matrix.engine.version }}.gemfile.lock
            gemfiles/${{ matrix.engine.name }}_${{ matrix.engine.version }}*
          retention-days: 1

  complete:
    name: Lock Dependencies (complete)
    runs-on: ubuntu-24.04
    needs:
      - lock
    steps:
      - run: echo "DONE!"
