name: Parametric Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
  schedule:
    - cron: "00 04 * * 2-6"

# Default permissions for all jobs
permissions: {}

env:
  SYSTEM_TESTS_REF: 'main' # This must always be set to `main` on dd-trace-rb's master branch

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-24.04
    outputs:
      changes: ${{ steps.changes.outputs.src }}
      FORCED_TESTS_LIST: ${{ steps.read_forced_tests_list.outputs.FORCED_TESTS_LIST }}
      ST_REF: ${{ steps.read_forced_tests_list.outputs.ST_REF }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - '.github/forced-tests-list.json'
              - '.github/workflows/**'
              - 'lib/**'
              - 'ext/**'
              - '*.gemspec'
              - 'Gemfile'
              - '*.gemfile'
              - 'lib-injection/**'
              - 'tasks/**'
      - name: Read forced-tests-list.json file
        id: read_forced_tests_list
        run: |
          {
            printf "FORCED_TESTS_LIST<<EOF\n"
            cat .github/forced-tests-list.json
            printf "\nEOF\n"
          } >> "$GITHUB_OUTPUT"
      # This may feel useless but we cannot access env in `with` block in parametric job, while we can access needs.changes.output
      - name: Outputs branch
        id: outputs_branch
        env:
          SYSTEM_TESTS_REF: ${{ env.SYSTEM_TESTS_REF }}
        run: echo "ST_REF=${SYSTEM_TESTS_REF}" >> "$GITHUB_OUTPUT"

  build-artifacts:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changes == 'true' }}
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - run: mkdir binaries/
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          path: binaries/dd-trace-rb/
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: system_tests_binaries
          path: binaries/

  parametric:
    name: Parametric Tests (with force tests)
    needs:
      - build-artifacts
      - changes
    if: ${{ needs.changes.outputs.changes == 'true' && needs.changes.outputs.FORCED_TESTS_LIST && !(fromJSON(needs.changes.outputs.FORCED_TESTS_LIST)['PARAMETRIC'] == null) }}
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: DataDog/system-tests/.github/workflows/run-parametric.yml@main

    with:
      library: ruby
      binaries_artifact: system_tests_binaries
      job_count: 8
      job_matrix: "[1,2,3,4,5,6,7,8]"
      ref: ${{ needs.changes.outputs.ST_REF }}
      force_execute_tests: ${{ toJSON(fromJSON(needs.changes.outputs.FORCED_TESTS_LIST)['PARAMETRIC'])}}

  parametric-without-force-tests:
    name: Parametric Tests (without force tests)
    needs:
      - build-artifacts
      - changes
    if: ${{ needs.changes.outputs.changes == 'true' && !(needs.changes.outputs.FORCED_TESTS_LIST && !(fromJSON(needs.changes.outputs.FORCED_TESTS_LIST)['PARAMETRIC'] == null)) }}
    secrets: inherit # zizmor: ignore[secrets-inherit]
    uses: DataDog/system-tests/.github/workflows/run-parametric.yml@main

    with:
      library: ruby
      binaries_artifact: system_tests_binaries
      job_count: 8
      job_matrix: "[1,2,3,4,5,6,7,8]"
      ref: ${{ needs.changes.outputs.ST_REF }}

  complete:
    name: Parametric Tests (complete)
    runs-on: ubuntu-24.04
    needs:
      - parametric
    steps:
      - run: echo "DONE!"
