name: Parametric Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
  schedule:
    - cron: "00 04 * * 2-6"

# Default permissions for all jobs
permissions: {}

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-24.04
    outputs:
      changes: ${{ steps.changes.outputs.src }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - name: Changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            src:
              - '.github/workflows/**'
              - 'lib/**'
              - 'ext/**'
              - '*.gemspec'
              - 'Gemfile'
              - '*.gemfile'
              - 'lib-injection/**'
              - 'tasks/**'

  build-artifacts:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changes == 'true' }}
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - run: mkdir binaries/
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          path: binaries/dd-trace-rb/
      - name: Upload artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: system_tests_binaries
          path: binaries/

  parametric:
    needs:
      - build-artifacts
      - changes
    if: ${{ needs.changes.outputs.changes == 'true' }}
    uses: DataDog/system-tests/.github/workflows/run-parametric.yml@main
    secrets: inherit # zizmor: ignore[secrets-inherit]
    with:
      library: ruby
      binaries_artifact: system_tests_binaries
      job_count: 8
      job_matrix: "[1,2,3,4,5,6,7,8]"

  complete:
    name: Parametric Tests (complete)
    runs-on: ubuntu-24.04
    needs:
      - parametric
    steps:
      - run: echo "DONE!"
