name: "Pull Request Labeler"

on: # yamllint disable-line rule:truthy
  - pull_request_target # zizmor: ignore[dangerous-triggers]

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
