name: "Release Library Injection"
on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*.*' # Exclude prerelease tags

jobs:
  build-and-publish-release-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version
        id: version
        run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Get version
        run: echo "The selected version is ${{ steps.version.outputs.version }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        run: docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Docker Build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/datadog/dd-trace-rb/dd-lib-ruby-init:${{ steps.version.outputs.version }}
          platforms: 'linux/amd64,linux/arm64/v8'
          # The build arguments must match what is defined in lib-injection/Dockerfile
          build-args: DATADOG_RUBY_GEM_VERSION=${{ steps.version.outputs.version }}
          context: ./lib-injection
