name: Check require encapsulation

on:
  push:
    branches:
      - "**"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  check-require-encapsulation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm -f .rspec
      - run: bundle exec rspec spec/require_encapsulation_check.rb
