name: System Tests

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: {}
  schedule:
    - cron: "00 04 * * 0-6"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/master' }}"

# Default permissions for all jobs
permissions: {}

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-24.04
    outputs:
      changes: ${{ steps.changes.outputs.src }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Changes
        uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            src:
              - '.github/forced-tests-list.cfg'
              - '.github/workflows/**'
              - 'lib/**'
              - 'ext/**'
              - '*.gemspec'
              - 'Gemfile'
              - '*.gemfile'
              - 'lib-injection/**'
              - 'tasks/**'

  build:
    needs:
      - changes
    if: ${{ needs.changes.outputs.changes == 'true' }}
    runs-on: ubuntu-24.04
    name: Build artifact
    permissions:
      packages: write
    outputs:
      forced_tests: ${{ steps.compute_forced_tests.outputs.forced_tests }}
    steps:
      - name: Checkout DataDog/dd-trace-rb
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: DataDog/dd-trace-rb
          fetch-depth: 2
          persist-credentials: false
          path: packaged/dd-trace-rb
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dd-trace-rb # The name must match the folder name so it extracts to binaries/dd-trace-rb on download
          path: packaged
      - id: compute_forced_tests
        run: |
          value=$(grep -v -E '^\s*#|^\s*$' packaged/dd-trace-rb/.github/forced-tests-list.cfg | paste -sd ',')
          echo "forced_tests=$value" >> "$GITHUB_OUTPUT"

  test:
    needs:
      - build
    uses: DataDog/system-tests/.github/workflows/system-tests.yml@a724f5b01554f65b27c4dca10bd0a27d28453bd6  # Automated: Updated by .github/workflows/update-system-tests.yml.
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      library: ruby
      binaries_artifact: dd-trace-rb
      desired_execution_time: 300 # 5 minutes
      scenarios_groups: tracer_release
      ref: a724f5b01554f65b27c4dca10bd0a27d28453bd6 # Automated: Updated by .github/workflows/update-system-tests.yml.
      force_execute: ${{ needs.build.outputs.forced_tests }}
      parametric_job_count: 8
      push_to_test_optimization: true
      skip_empty_scenarios: true

  complete:
    name: System Tests (complete)
    runs-on: ubuntu-24.04
    needs:
      - test
    steps:
      - run: echo "DONE!"
