name: Test for memory leaks

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: "${{ github.ref != 'refs/heads/master' }}"

# Default permissions for all jobs
permissions: {}

jobs:
  test-memcheck:
    runs-on: ubuntu-24.04
    env:
      BUNDLE_GEMFILE: gemfiles/ruby-3.4.gemfile
      BUNDLE_FROZEN: "true"
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: 3.4.1
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: latest
          cache-version: v2 # bump this to invalidate cache
      - run: sudo apt-get update && (sudo apt-get install -y valgrind || sleep 5 && sudo apt-get install -y valgrind) && valgrind --version
      - run: bundle exec rake compile spec:profiling:memcheck spec:core_with_libdatadog_api_memcheck
  test-asan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: asan-release
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: latest
          cache-version: v2 # bump this to invalidate cache
      - run: bundle exec rake spec:profiling:main
        env:
          RUBY_FREE_AT_EXIT: 1
          LSAN_OPTIONS: verbosity=0:log_threads=1:suppressions=${{ github.workspace }}/suppressions/lsan.supp
          ASAN_OPTIONS: detect_leaks=1

  complete:
    name: Test for memory leaks (complete)
    runs-on: ubuntu-24.04
    needs:
      - test-memcheck
      - test-asan
    steps:
      - run: echo "DONE!"
