name: Test with unstable Ruby VMs
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [head, jruby-head, truffleruby-head]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@77ca66ce2792fb05b8b204a203328e12593a64f3 # v1.72.1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake test:main
      - run: bundle exec rake spec:main
      - run: bundle exec rake spec:contrib
      - run: bundle exec rake spec:opentracer
