name: Appraisal

on:
  workflow_call:
    inputs:
      spec:
        required: true
        type: string
      engine_name:
        required: true
        type: string
      engine_version:
        required: true
        type: string
      appraisal:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test ${{ matrix.appraisal }} (${{ matrix.engine.name }}:${{ matrix.engine.version }} ${{ matrix.spec }})"
    strategy:
      fail-fast: false
      matrix:
        spec:
          - ${{ inputs.spec }}
        engine:
          - name: ${{ inputs.engine_name }}
            version: ${{ inputs.engine_version }}
        appraisal:
          - ${{ inputs.appraisal }}
    env:
      SKIP_SIMPLECOV: 1
      DD_INSTRUMENTATION_TELEMETRY_ENABLED: false
      DD_REMOTE_CONFIGURATION_ENABLED: false
    container:
      image: "ghcr.io/datadog/images-rb/engines/${{ matrix.engine.name }}:${{ matrix.engine.version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Bundle install
        run: bundle install
      - name: Appraisal install
        id: appraisal
        if: ${{ matrix.appraisal }}
        run: |
          BUNDLE_GEMFILE="gemfiles/${{ matrix.engine.name }}_${{ matrix.engine.version }}_$(echo ${{ matrix.appraisal }} | tr '-' '_').gemfile"
          echo "BUNDLE_GEMFILE=${BUNDLE_GEMFILE}" >> $GITHUB_OUTPUT
          export BUNDLE_GEMFILE
          bundle install
      - name: Run the test
        run: |
          if [ -n "${{ steps.appraisal.outputs.BUNDLE_GEMFILE }}" ]; then
            BUNDLE_GEMFILE="${{ steps.appraisal.outputs.BUNDLE_GEMFILE }}"
            export BUNDLE_GEMFILE
          fi
          bundle exec rake spec:${{ matrix.spec.task }}
