name: Appraisal

on:
  workflow_call:
    inputs:
      spec:
        required: true
        type: string
      engine_name:
        required: true
        type: string
      engine_version:
        required: true
        type: string
      appraisal:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    name: "spec:${{ matrix.spec }} ${{ matrix.engine.name }}:${{ matrix.engine.version }} group:${{ matrix.appraisal }} run"
    strategy:
      fail-fast: false
      matrix:
        spec:
          - ${{ inputs.spec }}
        engine:
          - name: ${{ inputs.engine_name }}
            version: ${{ inputs.engine_version }}
        appraisal:
          - ${{ inputs.appraisal }}
    env:
      SKIP_SIMPLECOV: 1
      DD_INSTRUMENTATION_TELEMETRY_ENABLED: false
      DD_REMOTE_CONFIGURATION_ENABLED: false
    container:
      image: "ghcr.io/datadog/images-rb/engines/${{ matrix.engine.name }}:${{ matrix.engine.version }}"
    steps:
      - uses: actions/checkout@v4
      - name: Bundle install
        run: bundle install
      - name: Bundle install
        id: bundle
        run: |
          if [ -n "${{ matrix.appraisal }}" ]; then
            BUNDLE_GEMFILE="gemfiles/${{ matrix.engine.name }}_${{ matrix.engine.version }}_$(echo ${{ matrix.appraisal }} | tr '-' '_').gemfile"
          elif [ "${{ matrix.engine.name }}" = "ruby" ]; then
            BUNDLE_GEMFILE="Gemfile-${{ matrix.engine.version }}"
          else
            BUNDLE_GEMFILE="Gemfile-${{ matrix.engine.name }}-${{ matrix.engine.version }}"
          fi
          echo "BUNDLE_GEMFILE=${BUNDLE_GEMFILE}" >> $GITHUB_OUTPUT
          env BUNDLE_GEMFILE="${BUNDLE_GEMFILE}" bundle install
      - name: Run the test
        run: |
          env BUNDLE_GEMFILE="${{ steps.bundle.outputs.BUNDLE_GEMFILE }}" bundle exec rake spec:${{ matrix.spec }}
