require 'datadog/demo_env'

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.0.5"

# Choose correct specs for 'datadog' demo environment
gem *Datadog::DemoEnv.gem_datadog_auto_instrument

gem 'dogstatsd-ruby'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", "~> 5.0"

gem 'unicorn'

# Use Resque for background job processing
gem 'resque', "~> 2"

# Redis is required for ActiveSupport::Cache::RedisCacheStore
gem 'redis', "~> 4"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

group :development, :test do
  if RUBY_VERSION >= '3.1'
    gem "debug", platforms: %i,mri mingw x64_mingw,
  else
    gem "byebug", platforms: %w,mri,
  end

  gem "rspec-rails", "~> 6.0.0"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

# Gems no longer included in Ruby 3.4
gem 'bigdecimal'
gem 'mutex_m'

# concurrent-ruby 1.3.5 removed dependency on logger, see:
# https://github.com/ruby-concurrency/concurrent-ruby/commit/d7ce956dacd0b772273d39b8ed31a30cff7ecf38
# Unfortunately this broke Rails because ActiveSupport used Logger
# before requiring logger.
# Since the failure happens rather early in rails bootstrapping,
# patching it is difficult, thus downgrade concurrent-ruby.
# The issue is fixed in 7-0-stable and should be shipped in the release
# after 7.0.8.7, at which point the pin of concurrent-ruby should be removed.
# See https://github.com/rails/rails/issues/54263
gem 'concurrent-ruby', '1.3.4'
