module Datadog
  module Tracing
    module Contrib
      module ActiveModelSerializers
        module Events
          module Render
            include ActiveModelSerializers::Event

            EVENT_NAME: "render.active_model_serializers"

            def self?.supported?: () -> untyped

            def self?.event_name: () -> untyped

            def self?.span_name: () -> untyped

            def self?.process: (untyped span, untyped _event, untyped _id, untyped payload) -> untyped
          end
        end
      end
    end
  end
end
