module Datadog
  module AppSec
    module SecurityEngine
      class Engine
        @waf_builder: WAF::HandleBuilder

        @handle_ref: ThreadSafeRef

        @ruleset_version: ::String

        @reconfigured_ruleset_version: ::String

        @default_ruleset: (::String | ::Symbol | ::File | ::StringIO | ::Hash[untyped, untyped])

        @default_ip_denylist: ::Array[::String]

        @default_user_id_denylist: ::Array[::String]

        @default_ip_passlist: ::Array[::String]

        DEFAULT_RULES_CONFIG_PATH: ::String
        TELEMETRY_ACTIONS: ::Array[::String]
        DIAGNOSTICS_CONFIG_KEYS: ::Array[::String]

        def initialize: (appsec_settings: Core::Configuration::Settings::_AppSec, telemetry: Core::Telemetry::Component) -> void

        def new_runner: () -> SecurityEngine::Runner

        def release_waf_handle: (WAF::Handle waf_handle) -> void

        def add_or_update_config: (::Hash[::String, untyped] config, path: ::String) -> WAF::diagnostics

        def remove_config_at_path: (::String path) -> void

        def reconfigure!: () -> void

        private

        def load_default_config: (telemetry: Core::Telemetry::Component) -> WAF::diagnostics

        def report_configuration_diagnostics: (WAF::diagnostics diagnostics, action: ::String, telemetry: Core::Telemetry::Component) -> void

        def increment_waf_metric: (::String metric_name, success: bool, ruleset_version: ::String, telemetry: Core::Telemetry::Component) -> void
      end
    end
  end
end
