module Datadog
  module AppSec
    module SecurityEngine
      class Runner
        type input_data = ::Hash[::String, any]

        @mutex: ::Mutex

        @handle_ref: ThreadSafeRef

        @waf_handle: WAF::Handle

        @waf_context: WAF::Context

        @ruleset_version: ::String

        @debug_tag: ::String

        SUCCESSFUL_EXECUTION_CODES: ::Array[::Symbol]

        attr_reader ruleset_version: ::String

        def initialize: (ThreadSafeRef handle_ref, ruleset_version: ::String) -> void

        def run: (input_data persistent_data, input_data ephemeral_data, ?::Integer timeout) -> SecurityEngine::result

        def waf_context: () -> WAF::Context

        def waf_addresses: () -> WAF::known_addresses

        def finalize!: () -> void

        private

        def try_run: (input_data persistent_data, input_data ephemeral_data, untyped timeout) -> WAF::Result

        def report_execution: (WAF::Result result) -> void
      end
    end
  end
end
