module Datadog
  module AppSec
    module SecurityEngine
      class Runner
        type input_data = ::Hash[::String, untyped]

        @mutex: ::Mutex

        @waf_handle: WAF::Handle

        @waf_context: WAF::Context

        @debug_tag: ::String

        SUCCESSFUL_EXECUTION_CODES: ::Array[::Symbol]

        def initialize: (RefCounter waf_ref_counter) -> void

        def run: (input_data persistent_data, input_data ephemeral_data, ?::Integer timeout) -> SecurityEngine::result

        def waf_context: () -> WAF::Context

        def finalize!: () -> void

        private

        def try_run: (input_data persistent_data, input_data ephemeral_data, untyped timeout) -> WAF::Result

        def report_execution: (WAF::Result result) -> void
      end
    end
  end
end
