module Datadog
  module AppSec
    module SecurityEngine
      class WAFHandleRegistry
        @current_handle: WAF::Handle

        @counters: ::Hash[WAF::Handle, ::Integer]

        @outstanding_handles: ::Array[WAF::Handle]

        @mutex: ::Mutex

        def initialize: (WAF::Handle current_handle) -> void

        def acquire_current_handle: () -> WAF::Handle

        def release_handle: (WAF::Handle handle) -> void

        def current_handle=: (WAF::Handle handle) -> WAF::Handle
      end
    end
  end
end
