module Datadog
  module Tracing
    module Contrib
      module Elasticsearch
        module Quantize
          PLACEHOLDER: "?"

          ID_PLACEHOLDER: "\\1?"

          EXCLUDE_KEYS: ::Array[untyped]

          SHOW_KEYS: ::Array[:_index | :_type | :_id]

          DEFAULT_OPTIONS: { exclude: untyped, show: untyped, placeholder: untyped }

          def self?.format_url: (untyped url) -> untyped

          def self?.format_body: (untyped body, ?::Hash[untyped, untyped] options) -> untyped

          def self?.format_body!: (untyped body, ?::Hash[untyped, untyped] options) -> untyped

          def self?.merge_options: (untyped original, untyped additional) -> untyped
          def self?.reserialize_json: (untyped string, ?untyped fail_value) { (untyped) -> untyped } -> untyped
          def self?.sanitize_fragment_with_id: (untyped url) -> untyped
        end
      end
    end
  end
end
